### ISSUE TITLE
dperf测试client统计是否存在问题

### ISSUE THREAD

**Issue by yfming** [baidu/dperf#102]
用了dperf测试cps，有几个问题想问一下。
client端一开始发包，前几秒只有发送，server端也没有收到报文，client也没有错误统计。
然后接下来是client端发包出现很多skErr统计
然后接下来才是正常收发新建统计正常了。
分别可以看下面的图：
<img width="1250" alt="图片" src="https://user-images.githubusercontent.com/25922534/163778211-849181de-ed84-4a28-90e5-fae94d22fdda.png">
<img width="1115" alt="图片" src="https://user-images.githubusercontent.com/25922534/163778222-1bdfd0ec-b951-4da6-b7c9-e5809f374c2c.png">
<img width="1234" alt="图片" src="https://user-images.githubusercontent.com/25922534/163778243-f07a575b-b9c6-464a-9f29-038d905a2eeb.png">

**Comment by pengjianzhang** [comment]
刚开始有一段时间是ARP，你可以通过slow start，wait 控制缓慢开启压力
main分支修复了一些统计时间准确性的问题，建议用main分支
