### ISSUE TITLE
Dpdk 20

### ISSUE THREAD

**Issue by penghaiheng** [baidu/dperf#106]
# dpdk-stable-20.11.5 installing : 
....
Installing lib/librte_kni.a to /home/dpdk-stable-20.11.5/mydpdk/lib/x86_64-linux-gnu
Installing lib/librte_kni.so.21.0 to /home/dpdk-stable-20.11.5/mydpdk/lib/x86_64-linux-gnu
Installing lib/librte_latencystats.a to /home/dpdk-stable-20.11.5/mydpdk/lib/x86_64-linux-gnu
...

# check  "librte_kni.so.21" file
dpdk/dpdk-stable-20.11.5/mydpdk/lib/x86_64-linux-gnu# ls -lh | grep librte_kni.so
lrwxrwxrwx 1 root root   16 4月  27 16:53 librte_kni.so -> librte_kni.so.21
lrwxrwxrwx 1 root root   18 4月  27 16:53 librte_kni.so.21 -> librte_kni.so.21.0
-rwxr-xr-x 1 root root  32K 4月  27 16:53 librte_kni.so.21.0

# build dperf :  
export PKG_CONFIG_PATH=dpdk/dpdk-stable-20.11.5/mydpdk/lib/x86_64-linux-gnu/pkgconfig/
>> The way you give : "dpdk/dpdk-stable-20.11.2/mydpdk/lib64/pkgconfig/"
cd dperf
make

# use dperf

./dperf: error while loading shared libraries: librte_kni.so.21: cannot open shared object file: No such file or directory

I will change dpdk 20.11.5 to 20.11.2, tks.

**Comment by pengjianzhang** [comment]
export LD_LIBRARY_PATH=/root/dpdk/dpdk-stable-20.11.2/mydpdk/lib64/
./build/dperf -h

https://zhuanlan.zhihu.com/p/451338251

**Comment by penghaiheng** [comment]
> don't need to change dpdk version.
> 
> export LD_LIBRARY_PATH=/root/dpdk/dpdk-stable-20.11.2/mydpdk/lib64/ ./build/dperf -h
> 
> https://zhuanlan.zhihu.com/p/451338251

This is useful, thank you. 

I read this link to building, only PKG_CONFIG_PATH...  
link : https://github.com/baidu/dperf/blob/main/docs/build.md

**Comment by pengjianzhang** [comment]
this is for dpdk-19 not for dpdk-20.
dpdk-19 is easy for beginners.

**Comment by pengjianzhang** [comment]
this is for dpdk-19 not for dpdk-20.
dpdk-19 is easy for beginners.

**Comment by penghaiheng** [comment]
> this is for dpdk-19 not for dpdk-20. dpdk-19 is easy for beginners.

This "Build dperf With DPDK-20" in links. :-)  

Thanks again.

**Comment by pengjianzhang** [comment]
thanks.
