### ISSUE TITLE
how to customize the client's sending packet throughput? 

### ISSUE THREAD

**Issue by ygm521** [baidu/dperf#110]
I want to test the udp throughput, how to customize the client's sending packet throughput? 
For example：
./iperf -u -c 192.168.148.210 -t 60 -i 1 -b 1000M -p 10000

change the client.conf？
cc                          2000

**Comment by pengjianzhang** [comment]
set current connections and set packet size.
for example:
i want to send 1mpps and every packet size is 1500bytes.


cps 100
cc  1000
keepalive 1ms 
packet_size 1400

**Comment by ygm521** [comment]
good！ thanks！

**Comment by pengjianzhang** [comment]
coule u please add a star to dperf, thanks.

**Comment by ygm521** [comment]
is right？thanks！

# example

33.242--udp-->33.241,22.121--udp-->192.168.22.211

# cat test/udp/client.conf 
```

mode                        client
protocol                    udp

cpu                         0 1
payload_size                1400
duration                    60s

cps                         100        
cc                          100
keepalive                   1ms

#port                       pci             addr         gateway
port                        0000:06:00.1    192.168.33.242   192.168.33.241

#                           addr_start      num
client                      192.168.33.242     1

#                           addr_start      num
server                      192.168.22.211      1

#                           port_start      num
listen                      80              1
```

# cat test/udp/server.conf 
```
mode            server
protocol        udp

keepalive       1s
payload_size    64

cpu             0 1

duration        10m

#port           pci             addr         gateway
port            0000:09:00.0    192.168.22.211   192.168.22.121

#               addr_start      num
client          192.168.22.121      1

#               addr_start      num
server          192.168.22.211      1

#               port_start      num
listen          80              1
```

**Comment by pengjianzhang** [comment]
if you use 2 cpus,  please use 2 server ips
example:
server          192.168.22.211      2

**Comment by ygm521** [comment]
if i use 2 cpus, how to understand the config num？what's the meaning?

```
#               addr_start      num
client          192.168.22.121      1
```

**Comment by pengjianzhang** [comment]
'num' is the total ip address numbers starting from 'addr_start' 
client 192.168.1.2  4  -> 192.168.1.2, 192.168.1.3 192.168.1.4, 192.168.1.5 
 

client first-ip  num
                     

https://github.com/baidu/dperf/blob/main/docs/configuration-CN.md
https://github.com/baidu/dperf/blob/main/docs/configuration.md
