### ISSUE TITLE
support for multiple queues on google cloud

### ISSUE THREAD

**Issue by pengjianzhang** [baidu/dperf#129]
virtio_dev_configure(): Unsupported Rx multi queue mode 1
Port0 dev_configure = -22

rss auto mq_rs_none

pull request https://github.com/baidu/dperf/pull/131

**Comment by jesson1** [comment]
我的网卡不支持rss，这个issue启发了我，应该配置rss  auto mq_rx_none

**Comment by pengjianzhang** [comment]
如果喜欢dperf，请加个star哦，谢谢

**Comment by zhaopcm** [comment]
![image](https://github.com/user-attachments/assets/117f238b-279c-40a1-a51e-ad39c5c62a40)
看起来有点问题不支持mq_rs_none

**Comment by pengjianzhang** [comment]
做了优化，不需要配置mq_rs_none了
