### ISSUE TITLE
请问编译的时候这个警告有影响吗

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#134]
mkdir -p build
gcc -O3 -g -I./src -DHTTP_PARSE -include rte_config.h -march=native -mno-avx512f -I/usr/local/include src/main.c src/socket.c src/config.c src/client.c src/mbuf_cache.c src/udp.c src/port.c src/mbuf.c src/arp.c src/icmp.c src/tcp.c src/tick.c src/http.c src/net_stats.c src/flow.c src/work_space.c src/cpuload.c src/config_keyword.c src/socket_timer.c src/ip.c src/eth.c src/server.c src/dpdk.c src/ctl.c src/icmp6.c src/neigh.c src/vxlan.c src/csum.c src/kni.c src/bond.c src/lldp.c src/rss.c src/ip_list.c src/http_parse.c src/trace.c -o build/dperf -L/usr/local/lib/x86_64-linux-gnu -Wl,--as-needed -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs -lpthread -lrte_net_bond -lrte_bus_pci -lrte_bus_vdev
src/kni.c: In function ‘kni_create’:
src/kni.c:137:43: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
     snprintf(name, RTE_KNI_NAMESIZE, "%s%d", cfg->kni_ifname, idx);
                                           ^
In file included from /usr/include/stdio.h:862:0,
                 from /usr/local/include/rte_mempool.h:36,
                 from /usr/local/include/rte_mbuf.h:38,
                 from src/kni.h:22,
                 from src/kni.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 27 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/kni.c: In function ‘kni_link_up’:
src/kni.c:137:43: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
     snprintf(name, RTE_KNI_NAMESIZE, "%s%d", cfg->kni_ifname, idx);
                                           ^
In file included from /usr/include/stdio.h:862:0,
                 from /usr/local/include/rte_mempool.h:36,
                 from /usr/local/include/rte_mbuf.h:38,
                 from src/kni.h:22,
                 from src/kni.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 27 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by pengjianzhang** [comment]
请问 这是dpdk哪个版本

**Comment by pengjianzhang** [comment]
看起来有问题，所有warnning都应该消除。不过如果不开启kni，就不会触发到这个bug

**Comment by digger-yu** [comment]
> 看起来有问题，所有warnning都应该消除。不过如果不开启kni，就不会触发到这个bug。 请提供一下：
> 
>     1. dpdk版本
> dpdk-stable-20.11.5#
>     2. GCC版本
> root@dperf:~/dpdk-stable-20.11.5# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

>     3. 操作系统
> 
> root@dperf:~/dpdk-stable-20.11.5# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
root@dperf:~/dpdk-stable-20.11.5#


root@dperf:~/dperf# ./build/dperf -v
1.2.0
root@dperf:~/dperf#

> 谢谢

**Comment by pengjianzhang** [comment]
知道这个问题了，待会我修复一下，麻烦你帮忙测一下，谢谢

**Comment by digger-yu** [comment]
> 知道这个问题了，待会我修复一下，麻烦你帮忙测一下，谢谢

哦了^_^

**Comment by pengjianzhang** [comment]
请测试一下这个分支，谢谢

https://github.com/pengjianzhang/dperf/tree/compile-warning

**Comment by digger-yu** [comment]
> 请测试一下这个分支，另外，能给dperf加个star吗~~ 谢谢
> 
> https://github.com/pengjianzhang/dperf/tree/compile-warning

`root@dperf:~# git clone https://github.com/pengjianzhang/dperf.git
正克隆到 'dperf'...
remote: Enumerating objects: 1234, done.
remote: Counting objects: 100% (354/354), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 1234 (delta 191), reused 239 (delta 184), pack-reused 880
接收对象中: 100% (1234/1234), 373.78 KiB | 1.70 MiB/s, 完成.
处理 delta 中: 100% (851/851), 完成.
root@dperf:~# cd dperf/
root@dperf:~/dperf# ls
CHANGELOG.md  CONTRIBUTING.md  docs  LICENSE  Makefile  README-CN.md  README.md  src  test
root@dperf:~/dperf# make
mkdir -p build
gcc -O3 -g -I./src -DHTTP_PARSE -include rte_config.h -march=native -mno-avx512f -I/usr/local/include src/main.c src/socket.c src/config.c src/client.c src/mbuf_cache.c src/udp.c src/port.c src/mbuf.c src/arp.c src/icmp.c src/tcp.c src/tick.c src/http.c src/net_stats.c src/flow.c src/work_space.c src/cpuload.c src/config_keyword.c src/socket_timer.c src/ip.c src/eth.c src/server.c src/dpdk.c src/ctl.c src/icmp6.c src/neigh.c src/vxlan.c src/csum.c src/kni.c src/bond.c src/lldp.c src/rss.c src/ip_list.c src/http_parse.c src/trace.c -o build/dperf -L/usr/local/lib/x86_64-linux-gnu -Wl,--as-needed -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs -lpthread -lrte_net_bond -lrte_bus_pci -lrte_bus_vdev
src/kni.c: In function ‘kni_create’:
src/kni.c:137:43: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
     snprintf(name, RTE_KNI_NAMESIZE, "%s%d", cfg->kni_ifname, idx);
                                           ^
In file included from /usr/include/stdio.h:862:0,
                 from /usr/local/include/rte_mempool.h:36,
                 from /usr/local/include/rte_mbuf.h:38,
                 from src/kni.h:22,
                 from src/kni.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 27 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/kni.c: In function ‘kni_link_up’:
src/kni.c:137:43: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
     snprintf(name, RTE_KNI_NAMESIZE, "%s%d", cfg->kni_ifname, idx);
                                           ^
In file included from /usr/include/stdio.h:862:0,
                 from /usr/local/include/rte_mempool.h:36,
                 from /usr/local/include/rte_mbuf.h:38,
                 from src/kni.h:22,
                 from src/kni.c:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 27 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@dperf:~/dperf# ./build/dperf -v
./build/dperf: error while loading shared libraries: librte_kni.so.21: cannot open shared object file: No such file or directory
root@dperf:~/dperf#
`

我下载的对么，还是有告警

**Comment by pengjianzhang** [comment]
git clone https://github.com/pengjianzhang/dperf.git
git checkout compile-warning

**Comment by digger-yu** [comment]
> git clone https://github.com/pengjianzhang/dperf.git

root@dperf:~# rm -rf dperf
root@dperf:~# git clone https://github.com/pengjianzhang/dperf.git
正克隆到 'dperf'...
remote: Enumerating objects: 1234, done.
remote: Counting objects: 100% (354/354), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 1234 (delta 191), reused 239 (delta 184), pack-reused 880
接收对象中: 100% (1234/1234), 373.78 KiB | 1.60 MiB/s, 完成.
处理 delta 中: 100% (851/851), 完成.
root@dperf:~# git checkout compile-warning
fatal: 不是一个 git 仓库（或者任何父目录）：.git
root@dperf:~# git checkout 'compile-warning'
fatal: 不是一个 git 仓库（或者任何父目录）：.git
root@dperf:~# cd dperf/
root@dperf:~/dperf# git checkout compile-warning
分支 'compile-warning' 设置为跟踪来自 'origin' 的远程分支 'compile-warning'。
切换到一个新分支 'compile-warning'
root@dperf:~/dperf# make
mkdir -p build
gcc -O3 -g -I./src -DHTTP_PARSE -include rte_config.h -march=native -mno-avx512f -I/usr/local/include src/main.c src/socket.c src/config.c src/client.c src/mbuf_cache.c src/udp.c src/port.c src/mbuf.c src/arp.c src/icmp.c src/tcp.c src/tick.c src/http.c src/net_stats.c src/flow.c src/work_space.c src/cpuload.c src/config_keyword.c src/socket_timer.c src/ip.c src/eth.c src/server.c src/dpdk.c src/ctl.c src/icmp6.c src/neigh.c src/vxlan.c src/csum.c src/kni.c src/bond.c src/lldp.c src/rss.c src/ip_list.c src/http_parse.c src/trace.c -o build/dperf -L/usr/local/lib/x86_64-linux-gnu -Wl,--as-needed -lrte_node -lrte_graph -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_regexdev -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_rcu -lrte_ring -lrte_eal -lrte_telemetry -lrte_kvargs -lpthread -lrte_net_bond -lrte_bus_pci -lrte_bus_vdev
root@dperf:~/dperf#

验证没问题，没有告警了
