### ISSUE TITLE
建议更新个脚本，方便更改配置文件中server和client的地址

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#135]
建议更新个脚本，方便更改配置文件中server和client的地址
目前看配置文件中，server和client的地址都是固定的

**Comment by pengjianzhang** [comment]
能举个例子吗，没太理解你的意思，谢谢

**Comment by pengjianzhang** [comment]
谢谢你的建议。
实际测试中，由于环境各异，需要对配置做调整，另外在在测试过程中，也需要调整参数，以达到最佳指标；这些配置文件只能作为参考。
