### ISSUE TITLE
bind网卡后，dperf启动后有错误，请教一下

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#137]
`root@dperf:~# ifconfig eth0 down 
root@dperf:~# modprobe uio
root@dperf:~# modprobe uio_pci_generic
root@dperf:~# modprobe vfio-pci
root@dperf:~# /root/dpdk-stable-20.11.5/usertools/dpdk-devbind.py -b vfio-pci 0000:02:00.0 
root@dperf:~# /root/dpdk-stable-20.11.5/usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:02:00.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=vfio-pci unused=e1000,uio_pci_generic

No 'Baseband' devices detected
==============================

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

No 'Misc (rawdev)' devices detected
===================================

No 'Regex' devices detected
===========================
root@dperf:~# /root/dperf/build/dperf -c /root/dperf/test/http/server-cps.conf
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL:   0000:02:00.0 VFIO group is not viable! Not all devices in IOMMU group bound to VFIO or unbound
EAL: Requested device 0000:02:00.0 cannot be used
EAL: Bus (pci) probe failed.
EAL: No legacy callbacks, legacy socket not created
port init fail
dpdk init fail
root@dperf:~# 
root@dperf:~# /root/dpdk-stable-20.11.5/usertools/dpdk-devbind.py -u 0000:02:00.0
root@dperf:~# /root/dpdk-stable-20.11.5/usertools/dpdk-devbind.py -b e1000 0000:02:00.0
root@dperf:~# /root/dperf/build/dperf -c /root/dperf/test/http/server-cps.conf
EAL: Detected 2 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: No legacy callbacks, legacy socket not created
port init fail
dpdk init fail
root@dperf:~# 
root@dperf:~# /root/dperf/build/dperf -v
1.2.0
root@dperf:~# 

root@dperf:~# cat /root/dperf/test/http/server-cps.conf
mode        server
cpu         0
duration    10m
port        0000:02:00.0    6.6.241.27   6.6.241.1
client      6.6.241.1       254
client      6.6.242.1       254
server      6.6.241.27      1
listen      80              1
root@dperf:~# `

请教一下，现在启动的时候提示port init fail  感觉是网卡没弄对导致的，麻烦指导一下
server-cps.conf的配置文件中只改了端口的名字
这块不是很明白
绑定网卡初期，怎么确定bind的参数是uio uio_pci_generic vfio-pci e1000中的哪一种，前面俩我都绑不上，只有vfio-pci 和e1000 这两种可以，不加这个参数还不行

绑定没有提示错误，但启动dperf的时候报错，是不是还是网卡绑定的问题
另外，我编辑的时候没有删除线，提交之后日志的部分地方显示删除线，这个您知道在哪设置么``

**Comment by pengjianzhang** [comment]
要确定一下这个网卡dpdk 是否支持 82545EM Gigabit Ethernet Controller (Copper) 100f

**Comment by digger-yu** [comment]
> 要确定一下这个网卡dpdk 是否支持 82545EM Gigabit Ethernet Controller (Copper) 100f 我感觉igb_uio支持的网卡种类要多于 uio_pci_generic vfio-pci
> 
> 你试一下dpdk-19.11版本，用igb_uio驱动 参考： https://zhuanlan.zhihu.com/p/451340043

查询了一下网卡devid号，发现20.11dpdk版本是支持这个网卡的
![2](https://user-images.githubusercontent.com/55081697/172984538-764d53fe-29e4-4b85-8e25-ed7f29665229.png)

也换过19.11版本和igb_uio驱动

启动的时候还是会报错
![1](https://user-images.githubusercontent.com/55081697/172984593-675877fc-65a3-4d02-97c1-990601630e7a.png)

请问是不是还是网卡的问题

**Comment by pengjianzhang** [comment]
大页配了吗

**Comment by digger-yu** [comment]
> 大页配了吗

![3](https://user-images.githubusercontent.com/55081697/172988224-ee4bcdfa-9895-4ba8-8cad-fcd3e683b53c.png)

配置了，但值不大，是不是大页哪设置不合理

**Comment by pengjianzhang** [comment]
参考这个文章去配置，每个大页Size是1G，配2个大页，试试
https://zhuanlan.zhihu.com/p/451340043

**Comment by pengjianzhang** [comment]
这个网卡是vmware虚出来的吗？ vmxnet3网卡是支持的

**Comment by digger-yu** [comment]
> 个大页Size是1G，配2个大页，试试

是vmware 虚拟出来的

**Comment by pengjianzhang** [comment]
看看能不能虚 vmxnet3网卡

**Comment by pengjianzhang** [comment]
这个网卡DPDK 应该是支持的呀

**Comment by digger-yu** [comment]
> 这个网卡DPDK 应该是支持的呀

是的啊，而且现在用的也是igb_uio驱动，绑定未提示任何错误
大页看着也没问题，但还是报错
![image](https://user-images.githubusercontent.com/55081697/173041224-c30264ef-0249-46c8-abbc-3e3311d05ea5.png)

**Comment by pengjianzhang** [comment]
换个操作系统试试 centos 7.9？

**Comment by pengjianzhang** [comment]
你配置错了

**Comment by digger-yu** [comment]
> 
![image](https://user-images.githubusercontent.com/55081697/173044831-a6493d1e-a23a-46c7-a6f2-5b7c2361aa3c.png)

具体哪个配置，是grub.cfg么

**Comment by pengjianzhang** [comment]
dperf的配置

**Comment by digger-yu** [comment]
> 

![image](https://user-images.githubusercontent.com/55081697/173045265-10e4e045-f177-457e-8e18-2e5544b4a1da.png)
里面只修改了网卡编号

**Comment by pengjianzhang** [comment]
client只留一行， 254改为1

**Comment by digger-yu** [comment]
> 

![image](https://user-images.githubusercontent.com/55081697/173047447-86fbb1c8-02c7-4544-9ebc-bc2cd9a675e9.png)
看起来应该可以了

另外请教一下，现在dpdk绑定之前需要down掉网卡，dpdk kni是不是可以设置多个虚拟地址，这个kni具体怎么用

**Comment by pengjianzhang** [comment]
dperf会给一个物理网卡 虚一个kni，请参考https://zhuanlan.zhihu.com/p/517921468
