### ISSUE TITLE
请问有测云主机带宽的配置模版吗？谢谢

### ISSUE THREAD

**Issue by Ericoai** [baidu/dperf#138]

**Comment by pengjianzhang** [comment]
两个云上虚拟机之间对打吗？

**Comment by Ericoai** [comment]
你好，感谢回复！

是两个云上虚拟机之间对打，我参考配置脚本将payload_size调大为1400，并发cps调小为200后，测试结果如下：
1. 发送和接收端1个cpu，测试结果cpu使用率70%，带宽7.8G
2. 发送和接收端4个cpu，打开rss auto，测试结果每个cpu使用率40%，总带宽12G

我有以下两个问题，可以帮忙解答一下吗？
1. 当使用多个cpu的时候，cpu使用率下降较为明显，这个是正常的吗？还是我配置有问题呢？
2. 我的云主机是8核云主机，测试时候使用的cpu个数一定要和网卡数保持一致吗？我配置cpu为1-7，port数为4，会提示cpu个数和port个数不一致而报错？

谢谢

**Comment by pengjianzhang** [comment]
如果测云主机的带宽，感觉并不需要很多网卡，测单个网卡带宽就好了

**Comment by Ericoai** [comment]
感谢解答
