### ISSUE TITLE
请问有测试云主机间新建连接数和并发连接数的性能测试的配置模板吗？谢谢

### ISSUE THREAD

**Issue by Ericoai** [baidu/dperf#139]
你好，我参考https://zhuanlan.zhihu.com/p/451341132 这篇指导配置了测试云主机新建和并发的脚本；但是测试时候server显示收到包数为0，请问是配置有误吗？

配置信息：

![image](https://user-images.githubusercontent.com/25098236/173783004-1c773e62-3178-473d-8af5-58d8f4038e9a.png)

测试结果：

![image](https://user-images.githubusercontent.com/25098236/173782757-12541e6c-1178-435d-a958-b810283c9f51.png)

**Comment by pengjianzhang** [comment]
1.  server.conf 上的 'client'一定要包含 client.conf的'client'
2. 你的环境上可以起这么多IP么， 一般云上只能配一个IP吧 "client 30.100.1.3 1 "
3. 云上CPS也不会有很高，你可以先测cps 10k, 再慢慢提升
4. 在云上，可以把客户端IP减少， 把listen 的端口数增加
5. 把客户端的网关指向server，server的网关指向client

**Comment by Ericoai** [comment]
感谢回复！

我减少client ip，增加listen 端口数之后，测试结果如下：

请问新建连接是查看skopen这个值吗？

**Comment by pengjianzhang** [comment]
是的，你的测试出现了skErr，你把tx burst调小试试

**Comment by Ericoai** [comment]
谢谢指导，我把tx burst分别调节成64，32，但是都出现了skerr

**Comment by pengjianzhang** [comment]
降低压力，tx设为4或8

**Comment by chengxiang1997** [comment]
大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。

**Comment by pengjianzhang** [comment]
> 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。

参考 readme或者dperf.org上的文档，差别不大
你的主机是哪家的，什么网卡驱动

**Comment by pengjianzhang** [comment]
> > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > 
> > 
> > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> 
> 移动云的，安装dpdk报错
移动云没有测试过，如果安装不了DPDK，你得问一下移动云的技术支持
google云、阿里云、AWS、百度云、火山云 都是支持dperf的

如果喜欢dperf 请加个star，谢谢

**Comment by pengjianzhang** [comment]
> > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > 
> > 
> > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> 
> 移动云的，安装dpdk报错

Linux环境上，编译安装应该是没有问题的，能不能运行是另一个问题，云上常见的virtio驱动也是支持DPDK的

**Comment by chengxiang1997** [comment]
> > > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > > 
> > > 
> > > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> > 
> > 
> > 移动云的，安装dpdk报错
> 
> Linux环境上，编译安装应该是没有问题的，能不能运行是另一个问题，云上常见的virtio驱动也是支持DPDK的

您好，dpdk和dperf安装好了，但是启动dperf服务时报错了，出现了以下错误

[root@vm-002 dperf-1.8.0]# lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device
00:04.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI
00:05.0 Communication controller: Red Hat, Inc. Virtio console
00:06.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon
00:07.0 System peripheral: Intel Corporation 6300ESB Watchdog Timer
[root@vm-002 dperf-1.8.0]# cat server.conf
mode        server
cpu         0
duration    10m
port        0000:00:03.0    192.168.0.232   192.168.0.131
client      192.168.0.131   1
server      192.168.0.232   1
listen      80 1
[root@vm-002 dperf-1.8.0]# ./build/dperf -c server.conf
EAL: Requested device 0000:00:03.0 cannot be used
not enough ports available: avail 0 require 1
port init fail
dpdk init fail

**Comment by pengjianzhang** [comment]
> > > > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > > > 
> > > > 
> > > > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> > > 
> > > 
> > > 移动云的，安装dpdk报错
> > 
> > 
> > Linux环境上，编译安装应该是没有问题的，能不能运行是另一个问题，云上常见的virtio驱动也是支持DPDK的
> 
> 您好，dpdk和dperf安装好了，但是启动dperf服务时报错了，出现了以下错误
> 
> [root@vm-002 dperf-1.8.0]# lspci 00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02) 00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II] 00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] 00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01) 00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03) 00:02.0 VGA compatible controller: Cirrus Logic GD 5446 00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device 00:04.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI 00:05.0 Communication controller: Red Hat, Inc. Virtio console 00:06.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon 00:07.0 System peripheral: Intel Corporation 6300ESB Watchdog Timer [root@vm-002 dperf-1.8.0]# cat server.conf mode server cpu 0 duration 10m port 0000:00:03.0 192.168.0.232 192.168.0.131 client 192.168.0.131 1 server 192.168.0.232 1 listen 80 1 [root@vm-002 dperf-1.8.0]# ./build/dperf -c server.conf EAL: Requested device 0000:00:03.0 cannot be used not enough ports available: avail 0 require 1 port init fail dpdk init fail

网卡要绑定用户态驱动， 应该是绑定vfio-pci

**Comment by chengxiang1997** [comment]
> > > > > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > > > > 
> > > > > 
> > > > > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> > > > 
> > > > 
> > > > 移动云的，安装dpdk报错
> > > 
> > > 
> > > Linux环境上，编译安装应该是没有问题的，能不能运行是另一个问题，云上常见的virtio驱动也是支持DPDK的
> > 
> > 
> > 您好，dpdk和dperf安装好了，但是启动dperf服务时报错了，出现了以下错误
> > [root@vm-002 dperf-1.8.0]# lspci 00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02) 00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II] 00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] 00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01) 00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03) 00:02.0 VGA compatible controller: Cirrus Logic GD 5446 00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device 00:04.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI 00:05.0 Communication controller: Red Hat, Inc. Virtio console 00:06.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon 00:07.0 System peripheral: Intel Corporation 6300ESB Watchdog Timer [root@vm-002 dperf-1.8.0]# cat server.conf mode server cpu 0 duration 10m port 0000:00:03.0 192.168.0.232 192.168.0.131 client 192.168.0.131 1 server 192.168.0.232 1 listen 80 1 [root@vm-002 dperf-1.8.0]# ./build/dperf -c server.conf EAL: Requested device 0000:00:03.0 cannot be used not enough ports available: avail 0 require 1 port init fail dpdk init fail
> 
> 网卡要绑定用户态驱动， 应该是绑定vfio-pci

[root@vm-002 usertools]# modprobe vfio-pci
[root@vm-002 usertools]# ./dpdk-devbind.py -b vfio-pci 0000:00:03.0
Warning: routing table indicates that interface 0000:00:03.0 is active. Not modifying
[root@vm-002 usertools]# ./dpdk-devbind.py -s

Network devices using kernel driver
===================================
0000:00:03.0 'Virtio network device 1000' if=eth0 drv=virtio-pci unused=virtio_pci,vfio-pci *Active*

No 'Baseband' devices detected
==============================

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

No 'Misc (rawdev)' devices detected
===================================
似乎绑定不了，求大佬指导一下

**Comment by chengxiang1997** [comment]
> > > > > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > > > > 
> > > > > 
> > > > > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> > > > 
> > > > 
> > > > 移动云的，安装dpdk报错
> > > 
> > > 
> > > Linux环境上，编译安装应该是没有问题的，能不能运行是另一个问题，云上常见的virtio驱动也是支持DPDK的
> > 
> > 
> > 您好，dpdk和dperf安装好了，但是启动dperf服务时报错了，出现了以下错误
> > [root@vm-002 dperf-1.8.0]# lspci 00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02) 00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II] 00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] 00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01) 00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03) 00:02.0 VGA compatible controller: Cirrus Logic GD 5446 00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device 00:04.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI 00:05.0 Communication controller: Red Hat, Inc. Virtio console 00:06.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon 00:07.0 System peripheral: Intel Corporation 6300ESB Watchdog Timer [root@vm-002 dperf-1.8.0]# cat server.conf mode server cpu 0 duration 10m port 0000:00:03.0 192.168.0.232 192.168.0.131 client 192.168.0.131 1 server 192.168.0.232 1 listen 80 1 [root@vm-002 dperf-1.8.0]# ./build/dperf -c server.conf EAL: Requested device 0000:00:03.0 cannot be used not enough ports available: avail 0 require 1 port init fail dpdk init fail
> 
> 网卡要绑定用户态驱动， 应该是绑定vfio-pci

[root@vm-002 usertools]# modprobe vfio-pci
[root@vm-002 usertools]# ./dpdk-devbind.py -b vfio-pci 0000:00:03.0
Warning: routing table indicates that interface 0000:00:03.0 is active. Not modifying
似乎绑定不了，麻烦大佬指导一下

**Comment by pengjianzhang** [comment]
> > > > > > > 大佬请问下，云主机怎么配置dperf呀，我这云主机装dpdk都装不了。
> > > > > > 
> > > > > > 
> > > > > > 参考 readme或者dperf.org上的文档，差别不大 你的主机是哪家的，什么网卡驱动
> > > > > 
> > > > > 
> > > > > 移动云的，安装dpdk报错
> > > > 
> > > > 
> > > > Linux环境上，编译安装应该是没有问题的，能不能运行是另一个问题，云上常见的virtio驱动也是支持DPDK的
> > > 
> > > 
> > > 您好，dpdk和dperf安装好了，但是启动dperf服务时报错了，出现了以下错误
> > > [root@vm-002 dperf-1.8.0]# lspci 00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02) 00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II] 00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II] 00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01) 00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03) 00:02.0 VGA compatible controller: Cirrus Logic GD 5446 00:03.0 Ethernet controller: Red Hat, Inc. Virtio network device 00:04.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI 00:05.0 Communication controller: Red Hat, Inc. Virtio console 00:06.0 Unclassified device [00ff]: Red Hat, Inc. Virtio memory balloon 00:07.0 System peripheral: Intel Corporation 6300ESB Watchdog Timer [root@vm-002 dperf-1.8.0]# cat server.conf mode server cpu 0 duration 10m port 0000:00:03.0 192.168.0.232 192.168.0.131 client 192.168.0.131 1 server 192.168.0.232 1 listen 80 1 [root@vm-002 dperf-1.8.0]# ./build/dperf -c server.conf EAL: Requested device 0000:00:03.0 cannot be used not enough ports available: avail 0 require 1 port init fail dpdk init fail
> > 
> > 
> > 网卡要绑定用户态驱动， 应该是绑定vfio-pci
> 
> [root@vm-002 usertools]# modprobe vfio-pci [root@vm-002 usertools]# ./dpdk-devbind.py -b vfio-pci 0000:00:03.0 Warning: routing table indicates that interface 0000:00:03.0 is active. Not modifying 似乎绑定不了，麻烦大佬指导一下

参考 https://www.alibabacloud.com/help/zh/ecs/user-guide/replace-uio-drivers-with-vfio-drivers

**Comment by chengxiang1997** [comment]
请问下，可以使用dperf测试弹性负载均衡吗

**Comment by pengjianzhang** [comment]
> 请问下，可以使用dperf测试弹性负载均衡吗

很多厂商用dperf测四层负载均衡

**Comment by chengxiang1997** [comment]
> > 请问下，可以使用dperf测试弹性负载均衡吗
> 
> 很多厂商用dperf测四层负载均衡

![Image](https://github.com/user-attachments/assets/6869c413-9013-4623-9c4e-fc519657bb64)
以上是我测云主机并发，客户端的截图，应该是表明并发可以测起来了吧，但是我修改客户端和服务端的配置文件的IP后去测试弹性负载均衡，就会有问题

**Comment by chengxiang1997** [comment]
> > > > > 请问下，可以使用dperf测试弹性负载均衡吗
> > > > 
> > > > 
> > > > 很多厂商用dperf测四层负载均衡
> > > 
> > > 
> > > ![Image](https://github.com/user-attachments/assets/6869c413-9013-4623-9c4e-fc519657bb64) 以上是我测云主机并发，客户端的截图，应该是表明并发可以测起来了吧，但是我修改客户端和服务端的配置文件的IP后去测试弹性负载均衡，就会有问题
> > 
> > 
> > 而且网卡被dpdk接管了之后，除了dperf输出的日志没有其它地方可以查看云主机的实时并发
> 
> 能不能写篇文章，总结一下，如何在xx云上安装配置dperf，挂到dperf主页上

有时间的话，我可以写一下，但是当前我更想解决我的两个问题：
1、被dpdk接管的网卡，没有监控可以查看其并发连接数
2、如何使用dperf测试弹性负载均衡

**Comment by pengjianzhang** [comment]
> > > > > > 请问下，可以使用dperf测试弹性负载均衡吗
> > > > > 
> > > > > 
> > > > > 很多厂商用dperf测四层负载均衡
> > > > 
> > > > 
> > > > ![Image](https://github.com/user-attachments/assets/6869c413-9013-4623-9c4e-fc519657bb64) 以上是我测云主机并发，客户端的截图，应该是表明并发可以测起来了吧，但是我修改客户端和服务端的配置文件的IP后去测试弹性负载均衡，就会有问题
> > > 
> > > 
> > > 而且网卡被dpdk接管了之后，除了dperf输出的日志没有其它地方可以查看云主机的实时并发
> > 
> > 
> > 能不能写篇文章，总结一下，如何在xx云上安装配置dperf，挂到dperf主页上
> 
> 有时间的话，我可以写一下，但是当前我更想解决我的两个问题： 1、被dpdk接管的网卡，没有监控可以查看其并发连接数 2、如何使用dperf测试弹性负载均衡

1. 只能从dperf上看
2. 你可以参考一下 dperf.org上的文章

**Comment by abcyunyu** [comment]
> > 请问下，可以使用dperf测试弹性负载均衡吗
> 
> 很多厂商用dperf测四层负载均衡

请问下，dperf可以测试七层负载均衡器吗？以下的解释没理解，能详细解释下吗？
我看百度开发中心有写限制：
dperf的HTTP消息长度不超过一个网络报文，适合测试基于报文转发的网络设备，不适合用于七层负载均衡器的测试；
