### ISSUE TITLE
dperf server启动后，客户端设备无法ping通dperf的地址

### ISSUE THREAD

**Issue by jiawen94** [baidu/dperf#140]
设备debian11.3

拓扑：两设备通过交换机192.168.10.1相连接
server（192.168.10.191~194）<--交换机->client（192.168.10.141）

server已经配置hugepage，并且通过uio_generic绑定网卡（原静态ip是192.168.10.192）

问题：client设备无法ping通192.168.10.192
![image](https://user-images.githubusercontent.com/29114225/175901602-8085f31c-cd89-4873-8c4c-eee6a0671140.png)

**Comment by jiawen94** [comment]
dperf版本是1.2
dpdk版本是20.11.5

**Comment by pengjianzhang** [comment]
试一下,  下面两个命令通不通：
curl  192.168.10.192

 arping -I eth0  192.168.10.192  
eth0 换成客户端上的网卡名称

**Comment by jiawen94** [comment]
> 试一下, 下面两个命令通不通： curl 192.168.10.192
> 
> arping -I eth0 192.168.10.192 eth0 换成客户端上的网卡名称

arp可以通，但是ping和curl都不通
![image](https://user-images.githubusercontent.com/29114225/175906398-375fcdf9-260e-4d2f-9378-07cca93ff687.png)

**Comment by pengjianzhang** [comment]
确定一下 arp报文没有到达dperf，如果到达dperf会看到pktRX , arpRX上有数据

**Comment by pengjianzhang** [comment]
另外 在curl，ping的时候，观察一下pktRx, icmpRx, icmpTx

**Comment by jiawen94** [comment]
> 另外 在curl，ping的时候，观察一下pktRx, icmpRx, icmpTx

我在客户端ping arping curl 绑定了网口ens192，都成功了，并且服务端的pktRx, icmpRx, icmpTx都有数据

但是客户端换其他网口进行ping arp和curl操作，就无法连接
![image](https://user-images.githubusercontent.com/29114225/175910577-1461bc10-58db-4f59-b307-b324a47d3a22.png)

![image](https://user-images.githubusercontent.com/29114225/175909963-01a4713c-d87a-45b9-be5b-71172bfa65a0.png)

（服务端dpdk绑定的网口刚好也叫ens192）

**Comment by pengjianzhang** [comment]
符合预期，dperf只允许特定的客户端能建立连接，这些客户端的IP要配置在server的配置文件里。

另外，如果要其他的客户端能Ping通，你要把server.conf里的网关设置为交换机的网关。
dperf只会把报文发送给网关。

**Comment by jiawen94** [comment]
> 符合预期，dperf只允许特定的客户端能建立连接，这些客户端的IP要配置在server的配置文件里。
> 
> 另外，如果要其他的客户端能Ping通，你要把server.conf里的网关设置为交换机的网关。 dperf只会把报文发送给网关。
> 
> 请参考 配置手册： https://github.com/baidu/dperf/blob/main/docs/configuration-CN.md

我有个疑问：
在服务端的server.conf中，client的num设置是60，我理解应该是192.168.10.141~192.168.10.200的ip段的客户端都能访问，为什么只有客户端的ens192（192.168.10.142）才能访问？
![image](https://user-images.githubusercontent.com/29114225/175938979-f3edb517-5c47-475a-96ea-94fd02541b00.png)

是一定要把gateway配置成三层交换机的网关地址才能让 我配置的ip段都能访问server端吗？

**Comment by pengjianzhang** [comment]
1. 客户端、服务器都把网关指向141。 建议把客户端的网关指向服务器，服务器的网关指向客户端
2. 测试带宽，可以把协议改为udp

**Comment by jiawen94** [comment]
已解决我的问题，谢谢
