### ISSUE TITLE
关于dperf http 并发测试数值统计

### ISSUE THREAD

**Issue by InterNALXz** [baidu/dperf#141]
在进行http并发测试时，net_stats_print_pkt函数中，数值是怎么获取的呢，比如stats->pkt_tx，是没有ack包统计的结果吗

**Comment by pengjianzhang** [comment]
每个worker线程独立统计（累加值），ctl线程每秒汇总、输出每秒的速率。
每个计数函数（宏）都在net_stats.h中定义，如net_stats_rx() net_stats_tx()。
没有单独统计ack。
如果希望dperf，请给项目加个star吧，谢谢~

**Comment by InterNALXz** [comment]
里面的数值是从dpdk获取的？

**Comment by pengjianzhang** [comment]
每收到/发送一个mbuf，就去计数，需要分析报文的内容。dpdk不直接提供这些统计，网卡的出错统计数据是从DPDK直接拿的。

**Comment by InterNALXz** [comment]
好的，明白了，谢谢！
