### ISSUE TITLE
在特定的网络拓扑下，dperf发送端和接收端无法连接

### ISSUE THREAD

**Issue by jiawen94** [baidu/dperf#144]
我有一条IPsec隧道（可以连接两个不同子网），一端是172.30.235.0/24子网，另一端是172.30.236.0/24子网。
dperf服务端：172.30.235.10
dperf客户端：172.30.236.10

dperf服务端和客户端都在/etc/network/interface中添加了静态路由规则
![image](https://user-images.githubusercontent.com/29114225/176383384-752b36d1-a798-44d2-af85-e7bcb783e464.png)

子网之间能互相ping通，且iperf可以测吞吐
![image](https://user-images.githubusercontent.com/29114225/176383849-fbab75d0-b1f7-4fbb-ad3f-6bffd452286d.png)
![image](https://user-images.githubusercontent.com/29114225/176383967-9d292b2d-86aa-4a55-98dc-9942afcef237.png)

问题是，dperf client发的包，dperf server端收不到。配置如下
![image](https://user-images.githubusercontent.com/29114225/176384693-6e809092-cdd2-4416-84ba-409aaee590c8.png)

我之后尝试只开启dperf server，client端去ping，server端是有数据输出的，所以我推测dperf  client端发包有问题，导致服务端没收到。
麻烦看一下，谢谢~

**Comment by jiawen94** [comment]
![image](https://user-images.githubusercontent.com/29114225/176389332-5323a4e9-c4d4-4726-890c-b0afa076cbd4.png)

**Comment by pengjianzhang** [comment]
配置发一下。
dperf是kernel bypass的，不能识别/etc/network/interface的配置。
dperf只会发送报文给网关，你看下网关配置是否正确。
另外 你用的是什么网卡

**Comment by jiawen94** [comment]
我用的虚拟机，网卡信息如下
![image](https://user-images.githubusercontent.com/29114225/176391783-5aee4a0c-5b43-40d0-a451-cf82ed9ad251.png)

dperf的客户端网关配的是服务端的地址；dperf服务端的配置的网关是客户端的地址
服务端配置
```
#daemon
mode            server
tx_burst        128
cpu     0
#rss    auto
protocol        udp

duration        3m
#payload_size    1400
packet_size     1500
keepalive       1s

#numa2
port            0000:0b:00.0    172.30.235.10    172.30.236.10  00:0c:29:b8:b6:63

#               addr_start      num
client          172.30.236.10       1

#               addr_start      num
server          172.30.235.10      1

#               port_start      num
listen          80              5
```
客户端配置
```
mode                        client
#tx_burst                    128
#launch_num                  10
cpu                         0
#rss    auto

protocol        udp
#payload_size                1400
packet_size     1500
duration                    120s
cps                         400
cc                          3000
keepalive                   1ms

#port                       pci             addr         gateway    [mac]
port                        0000:0b:00.0    172.30.236.10   172.30.235.10  00:0c:29:e2:e3:85

#                           addr_start      num
client                      172.30.236.10       1

#                           addr_start      num
server                      172.30.235.10       1
#                           port_start      num
listen                      80              5
```

会不会就是因为dperf无法识别我自定义的路由规则导致的吗？（正常情况下，不配路由规则，两端无法ping通）

**Comment by pengjianzhang** [comment]
1. packet_size 是不是要设置小一点， 这条链路是不是不能发这么大的报文，考虑到Ipsec
2. 我觉得你的网关设置有问题
网关和接口IP 应该要在同一个网段，你需要一个网关帮你转发报文。
3. 你能画一下网络拓扑吗,  dperf client 和 dperf server中间有些什么

port            0000:0b:00.0    172.30.235.10    172.30.236.10  00:0c:29:b8:b6:63
port                        0000:0b:00.0    172.30.236.10   172.30.235.10  00:0c:29:e2:e3:85

**Comment by jiawen94** [comment]
packet_size改小到128，dperf还是没通
拓扑您看一下，172.30.235.10和172.30.236.10设备，都添加了路由规则，访问对方子网
![image](https://user-images.githubusercontent.com/29114225/176399749-02c89b72-e292-4455-a342-34d0ac33696b.png)

![image](https://user-images.githubusercontent.com/29114225/176399062-b693cccd-aacd-45ba-aa34-49ce8506aaed.png)

**Comment by pengjianzhang** [comment]
修改一下配置，试试
port          xxx  172.30.235.10    172.30.235.1
 
port           xxx   172.30.236.10    172.30.236.1

**Comment by pengjianzhang** [comment]
大页太少了，报内存不足，调整一下配置
 listen 80 1
逐步提高cc 提高压力

**Comment by jiawen94** [comment]
您好，我现在已将dperf的两端listen参数都设置80 1

1.大页总大小调大到8G之后，多CPU启动，确实不报错了。在16G内存的系统中，这么配置大页是否合适（总大页占内存一半，页大小2M，cat /proc/cpuinfo | grep pdpe1gb 查看，似乎不支持1G大页）
![image](https://user-images.githubusercontent.com/29114225/176589488-d20b63b9-3c6c-44b8-963b-4125b410fbb3.png)
![image](https://user-images.githubusercontent.com/29114225/176598253-4da0f1b3-21d2-4724-8396-fbc99e466222.png)

2.我调整了cc的取值，但是对吞吐率的结果没有显著提升。

3.此外，我发现dperf多cpu的吞吐率结果反而不如单个cpu
![image](https://user-images.githubusercontent.com/29114225/176585019-16f769ea-26ac-42f1-8d59-a15408bd5597.png)

4.如何理解上图输出的CPU信息，比如57 0 0 0 0 0 0 0，我通过htop看cpu的使用率，8个核心都是100%使用率
![image](https://user-images.githubusercontent.com/29114225/176589383-c66fea6c-6bec-4cbd-9982-498a325fd7db.png)

**Comment by pengjianzhang** [comment]
如果使用多个CPU需要：
1. 方法1：客户端、服务器需要多配几个IP
2. 方法2：打开rss auto

大页2G应该够了
从统计数据看，出现了重传，应该带宽可能接近上限了
注释tx_burst， 对你的网络而言 128太大了

**Comment by jiawen94** [comment]
我的情况应该是满足上述的【方法2】，即服务端和客户端分别只有一个绑定dpdk的IP地址，但配置里打开了rss auto。开启多cpu也是为了更好发挥dperf的效率。
开启多cpu导致测试结果下降，是否正常现象

**Comment by pengjianzhang** [comment]
不正常，需要调整参数。
如果出现了丢包，就会导致测试结果下降。
建议用UDP协议测试。把keepalive 间隔调大，并发也调大一点，tx_burst取消。

**Comment by jiawen94** [comment]
网络带宽预计255Mbps
目前只在两端都是8 cpu的情况下才出现吞吐率下降的情况（比如，1端4cpu，另一端8cpu，就没出现吞吐率骤降的情况）
tx_burst取消，keep alive调 10ms~100ms，cc调6000~15000，没有改善

**Comment by pengjianzhang** [comment]
225Mbps用一个cpu就好了
