### ISSUE TITLE
借助dperf测试tcp带宽（like perf）

### ISSUE THREAD

**Issue by thunderZH963** [baidu/dperf#145]
你好，如果我想测试tcp的带宽，请问可以借助dperf吗（类似iperf,但是想用dpdk协议栈）？您有什么建议？
期待回复！

**Comment by pengjianzhang** [comment]
可以的
如果喜欢dperf，请给项目加个star吧，谢谢

**Comment by thunderZH963** [comment]
请问具体应该怎么做呢？

**Comment by pengjianzhang** [comment]
https://github.com/baidu/dperf/issues/138

**Comment by thunderZH963** [comment]
now fix
