### ISSUE TITLE
dperf报错

### ISSUE THREAD

**Issue by thunderZH963** [baidu/dperf#146]
dpdk19.11

采用的网卡信息为0000:af:00.1 'MT27800 Family [ConnectX-5] 1017' if=ens1f1np1 drv=mlx5_core unused=vfio-pci *Active*
server.conf文件为
mode        server
cpu         0
duration    10m
port        0000:af:00.0    192.168.1.4   192.168.1.6
client      192.168.1.6      1
server      192.168.1.4     1
listen 80 1
huge配置如下
<img width="723" alt="image" src="https://user-images.githubusercontent.com/48862662/176617398-a36f4b40-88ea-4d8b-a6c7-4c3b2d5a221e.png">
出现报错
EAL: Detected 64 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: 42 hugepages of size 1073741824 reserved, but no mounted hugetlbfs found for that size
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:af:00.0 on NUMA socket 1
EAL:   probe driver: 15b3:1017 net_mlx5
net_mlx5: DV flow is not supported

port start error: Cannot allocate memory
start port fail
dpdk init fail

可以请教下是什么问题吗

**Comment by pengjianzhang** [comment]
是不是没有设置大页，请参考一下readme

**Comment by thunderZH963** [comment]
您看cat /proc/meminfo出来的截图是有hugepage的

**Comment by thunderZH963** [comment]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/48862662/176620216-59718941-dbb1-48d4-b989-677c22179b4b.png">

**Comment by thunderZH963** [comment]
我已经按照您的文章做了配置，helloworld执行如下
<img width="951" alt="image" src="https://user-images.githubusercontent.com/48862662/176623063-5dd63ca3-5ba1-46cc-af15-898734e51a34.png">

请问您有什么建议去验证配置正确性

**Comment by pengjianzhang** [comment]
mlx网卡驱动安装了吗

**Comment by thunderZH963** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/48862662/176624562-50c7e6da-b13e-4a05-9f19-f4ac3bd7e49a.png">
<img width="860" alt="image" src="https://user-images.githubusercontent.com/48862662/176624590-8fe11222-e472-4945-8280-681f1af2fed2.png">
已安装

**Comment by pengjianzhang** [comment]
配置贴一下

**Comment by thunderZH963** [comment]
这是我的配置
<img width="771" alt="image" src="https://user-images.githubusercontent.com/48862662/176626061-6d8c273c-e700-4e42-b157-ad5acced80a9.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/48862662/176626143-65a094fa-9d3c-4bd1-b99a-1ef4b5766c56.png">
<img width="643" alt="image" src="https://user-images.githubusercontent.com/48862662/176626240-a20d48f0-52b5-42e7-886a-7ed65f162f62.png">
刚才重启了一下发现
<img width="905" alt="image" src="https://user-images.githubusercontent.com/48862662/176626461-7a36887f-6e50-40ca-9c94-0f93311fe729.png">

这是什么问题？

**Comment by thunderZH963** [comment]
一些补充：
ConnectX5(rev:0)        NA       af:00.1   mlx5_3          net-ens1f1np1             1

ens1f1np1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.4  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::e42:a1ff:fe53:9633  prefixlen 64  scopeid 0x20<link>
        ether 0c:42:a1:53:96:33  txqueuelen 1000  (Ethernet)
        RX packets 1918  bytes 158484 (158.4 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1486  bytes 91552 (91.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
以上是网卡信息

**Comment by thunderZH963** [comment]
sorry, maybe pic address error! now,
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/48862662/176627662-730ce097-a265-4066-abf2-597a4610da55.png">
This is ok?

**Comment by pengjianzhang** [comment]
看起来工作正常

**Comment by thunderZH963** [comment]
据我观察，sudo lsof -i:80并无发现进程，如果此时我把client/server ip都设置为本机ip:192.168.1.4
那本机访问curl http://192.168.1.4提示curl: (7) Failed to connect to 192.168.1.4 port 80: Connection refused。
这是不是不太正常。

**Comment by pengjianzhang** [comment]
网关设置不对，不能与接口地址一样，要设置为一个正确的网关（也可以设置为客户端的IP），dperf只会把报文丢向网关

**Comment by thunderZH963** [comment]
如果我是想在单机进行测试，应该怎么设置呢？
我能想到的就是把网关、客户端、服务端设置为一致

**Comment by pengjianzhang** [comment]
你需要两个网卡（或者两个VF），每个dperf使用一个网卡，还需使用socket_mem配置，详情查看手册

**Comment by thunderZH963** [comment]
在接下来的系统中，我有两台server，每个server上都有一块cx5的网卡，ip地址分别为192.168.1.4和192.168.1.5，那此时的gateway要如何配置？

**Comment by pengjianzhang** [comment]
客户端把网关指向服务器，服务器把网关指向客户端

**Comment by thunderZH963** [comment]
ok. Thanks.
我会尝试一下，感谢您的解答！

**Comment by pengjianzhang** [comment]
也请向周围的朋友推荐一下dperf，谢谢

**Comment by thunderZH963** [comment]
now fix
