### ISSUE TITLE
BlueField2支持

### ISSUE THREAD

**Issue by thunderZH963** [baidu/dperf#147]
以下是我机器上的网卡信息
<img width="821" alt="image" src="https://user-images.githubusercontent.com/48862662/176803156-5d804d11-2747-4c31-9d92-391faaf854cd.png">

当我使用dperf启动server端时，如果我指定的是ConnectX5卡，可以正常启动
但如果指定BlueField2卡，无法启动，报错如下
<img width="895" alt="image" src="https://user-images.githubusercontent.com/48862662/176803207-9548fc83-5f52-4c08-810e-510af21be267.png">
请问，是因为dperf不支持吗？

**Comment by thunderZH963** [comment]
在适配上您有什么建议吗？我应该从哪里入手？
我用的是DPDK19.11

**Comment by pengjianzhang** [comment]
你试一下最新的dpdk，看起来bluefield2用的是MLX5
参考一下
https://doc.dpdk.org/guides/platform/bluefield.html

**Comment by thunderZH963** [comment]
好的，最新的dpdk和dperf是兼容的？

**Comment by pengjianzhang** [comment]
是的

**Comment by thunderZH963** [comment]
我之前采用dpdk19.11的原因是更高的dpdk版本会出现如下错误
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/48862662/176805651-65197697-2f8f-41da-9368-31e097eacc33.png">

**Comment by pengjianzhang** [comment]
你可以试着不要编这个驱动

**Comment by thunderZH963** [comment]
ok,目前来看最新版本是可以的。
但是如果两个机器的ip是互通的，我指定另一台机器的一个ip为gateway，
但是出现了Error: bad gateway. dperf cannot find gateway's MAC address. Please check the link.
这是什么原因

**Comment by pengjianzhang** [comment]
dperf只会发送报文给网关
如果解析不到网关MAC，就会报错

**Comment by thunderZH963** [comment]
now fix
