### ISSUE TITLE
results so high? 

### ISSUE THREAD

**Issue by thunderZH963** [baidu/dperf#149]
这是我的配置信息
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/48862662/176980896-a4721223-09ae-4bce-be16-3d3d240187fe.png">

这是结果
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/48862662/176980876-9521b4ac-f3b6-489d-b68f-9672825fd06e.png">

因为这是100g的cx6网卡，我想知道这个结果远超100G是为啥？

**Comment by thunderZH963** [comment]
我发现中间过程输出的bitsRX比较正常，可能因为Test Finish这部分是总和吗？
期待您的回答。
同时我想测的是100Gb的网卡，我发现目前只能测到25G，有什么参数还可以调整吗？
期待您的回答，谢谢

**Comment by pengjianzhang** [comment]
result是总计
不是每秒的速度

**Comment by thunderZH963** [comment]
我看到test里是多个pci address和ip，但我的物理网卡是只有一个pci address，您意思是给一个网卡配多个ip？但pci address（port）这部分呢

**Comment by pengjianzhang** [comment]
建议读一下配置文档 谢谢

**Comment by thunderZH963** [comment]
仔细看了一下configure.md还是比较困惑
我目标是想reproduce如下的表格
<img width="856" alt="image" src="https://user-images.githubusercontent.com/48862662/176992403-a7efd1b2-52e0-4505-b778-4fe66b527177.png">
首先配置了如下
<img width="715" alt="image" src="https://user-images.githubusercontent.com/48862662/176992416-cf7dd4d3-f011-48e5-85df-4c5496495d6a.png">
我理解可以得到的就是1RX/1TX的情况
但是针对一张网卡，我还是不太理解如何能够配置多个port 去测试类似iperf中多个stream的情况
这是我的网卡配置
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/48862662/176992480-fe3457e5-2ff2-4483-a68d-375a4e34661a.png">
期待得到您的解答。

**Comment by pengjianzhang** [comment]
1个cpu对应一个队列，提升带宽可以单网卡可以开多个队列，多网卡多队列都可以。

**Comment by thunderZH963** [comment]
可以请教一个单个网卡如何开多个队列？ 配置多个IP的话，我理解server ip数量不是应该和port数量一样？

**Comment by thunderZH963** [comment]
我目前多配cpu的话是通过rss enable

**Comment by thunderZH963** [comment]
solved

**Comment by thunderZH963** [comment]
solved

**Comment by pengjianzhang** [comment]
你能不能写一篇文章，说明如何测试带宽，我想这对社区是有很大的帮助，或许链接可以挂到项目主页上

**Comment by thunderZH963** [comment]
no problem.我们正在尝试在arm/x86 server上采用dperf/iperf进行带宽测试和性能比较，我会把整个过程写成文章分享！也感谢您的交流。

**Comment by pengjianzhang** [comment]
dperf的优势在于及时发现丢包，能够准确发现问题

**Comment by pengjianzhang** [comment]
也欢迎你把配置文件提交进来
https://zhuanlan.zhihu.com/p/485869677
