### ISSUE TITLE
Tps test and scale by cpu

### ISSUE THREAD

**Issue by thunderZH963** [baidu/dperf#151]
我的设置如下
client和server都是一张100Gb的CX5网卡，两张网卡通过一个交换机连接。
<img width="503" alt="image" src="https://user-images.githubusercontent.com/48862662/177023109-0785647e-ac2f-479f-a6f1-1193bb32be28.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/48862662/177023122-9d5a425b-4879-4f57-8217-ebe76673ccc4.png">
经过我的测试，cpu 设置为0时，bitsTx/Rx可以达到30Gb
经过我的测试，cpu 设置为0 1时，bitsTx/Rx可以达到60Gb
此后，继续提升则无法再提高
而我采用iperf测试，在4 streams就可以达到93Gb。
请问这部分我应该如何继续提升，有没有什么可以参考的配置，（目前网卡只有一个port），目标是想测到至少类似iperf的tcp bandwidth。
我理解多ip可能可以提高？但会提示：port num (1) != server_ip_range (2)
期待解答
谢谢！

**Comment by pengjianzhang** [comment]
不要使用rss 配置项，server ip数目与cpu数目一样

**Comment by thunderZH963** [comment]
但这样的话，port num (1) != server_ip_range (2)怎么解决？

**Comment by pengjianzhang** [comment]
一个网卡，使用8个队列的例子，供参考：
https://github.com/baidu/dperf/blob/main/test/performance/tx-pps/flood-8.conf

**Comment by thunderZH963** [comment]
我看这个例子里server配置如下
server          6.6.213.4       8
这是我需要在一个网卡上配置6.6.213.4-6.6.213.4.11这8个iP？
flood和protocol tcp也是要求的？

**Comment by pengjianzhang** [comment]
请仔细阅读配置文档，理解每个配置的含义

**Comment by thunderZH963** [comment]
我仔细对照了配置文档，进行了多IP的实验，结论如下
client端网卡配置了6个IP：192.168.31.100-192.168.31.105
server端网卡配置了6个IP：192.168.31.10-192.168.31.15
一、首先client端和server配置文件如下
`mode                        client
tx_burst                    128
launch_num                  3
cpu                         0
payload_size                1400
duration                    120s
cps                         400
cc                          3000
keepalive                   1ms
port        0000:af:00.1    192.168.31.100   192.168.31.10
client      192.168.31.100      1
server      192.168.31.10     1
listen 80 1

mode                        server
tx_burst                    128
cpu                         0
duration                    150s
payload_size                1400
keepalive                   1s
port                        0000:af:00.1    192.168.31.10   192.168.31.100
client      192.168.31.100      1
server      192.168.31.10     1
listen 80 1
`
此时report的cpu usage大概为31，带宽为31Gb
二、接下来，增大server端到2
`mode                        client
tx_burst                    128
launch_num                  3
cpu                         0 1
payload_size                1400
duration                    120s
cps                         400
cc                          3000
keepalive                   1ms
port        0000:af:00.1    192.168.31.100   192.168.31.10
client      192.168.31.100      1
server      192.168.31.10     2
listen 80 1

mode                        server
tx_burst                    128
cpu                         0 1
duration                    150s
payload_size                1400
keepalive                   1s
port                        0000:af:00.1    192.168.31.10   192.168.31.100
client      192.168.31.100      1
server      192.168.31.10     2
listen 80 1
`
我理解此时server ips为192.168.31.10 和192.168.31.11
发现此时report的结果中两个core cpu usage总和为31，带宽仍为31Gb
三、接下来，增大client数量

`mode                        client
tx_burst                    128
launch_num                  3
cpu                         0 1
payload_size                1400
duration                    120s
cps                         400
cc                          3000
keepalive                   1ms
port        0000:af:00.1    192.168.31.100   192.168.31.10
client      192.168.31.100      2
server      192.168.31.10     2
listen 80 1

mode                        server
tx_burst                    128
cpu                         0 1
duration                    150s
payload_size                1400
keepalive                   1s
port                        0000:af:00.1    192.168.31.10   192.168.31.100
client      192.168.31.100      2
server      192.168.31.10     2
listen 80 1
`
再次测试，发现report的结果中两个core cpu usage总和为31，带宽仍为31Gb

请教您一下是我的配置有问题吗？我发现继续增大cpu数量，一直是多个core总和为31，带宽仍为31Gb。

**Comment by pengjianzhang** [comment]
增加cpu个数到8  交换机是不是瓶颈

**Comment by thunderZH963** [comment]
我用iperf可以测到90Gb，我理解交换机应该不是瓶颈？

**Comment by pengjianzhang** [comment]
要逐步增大cc

**Comment by thunderZH963** [comment]
而且我如果用一个server和rss auto是可以到60gb左右的，但也没法提升了。

**Comment by thunderZH963** [comment]
> 要逐步增大cc

好的，我尝试增加cc看下

**Comment by thunderZH963** [comment]
增大cc可以提高performance，但出现其他问题，本问题已解决

**Comment by thunderZH963** [comment]
增大cc可以提高performance，但出现其他问题，本问题已解决
