### ISSUE TITLE
performance between a weak client and a strong server, maybe cpu is bottleneck

### ISSUE THREAD

**Issue by thunderZH963** [baidu/dperf#152]
client端采用的服务器配置：8 cpu cores + 16G mem ARM cpu
server端采用服务器配置：64 cpu cores + 128G mem Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
client端采用的服务器配置较低
配置文件如下
`
mode                        client
tx_burst                    128
launch_num                  3
cpu                         0 1 2 3 4 5 6 7
payload_size                1400
duration                    120s
cps                         400
cc                          20000
keepalive                   1ms
port        0000:03:00.1    192.168.31.200   192.168.31.10
client      192.168.31.200      8
server      192.168.31.10     8
listen 80 1

mode                        server
tx_burst                    128
cpu                         0 1 2 3 4 5 6 7
duration                    150s
payload_size                1400
keepalive                   1s
port                        0000:af:00.1    192.168.31.10   192.168.31.100
client      192.168.31.200      8
server      192.168.31.10     8
listen 80 1
`
运行过程我逐步增大cpu core数量从1到8，发现带宽从25增大到40后不再提高，以下是8core结果
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/48862662/177036548-c8f86ff6-2fdb-494f-8f8c-da182df4a1fd.png">
发现client端cpu usage都达到100，而server端还较低，是不是可以说明cpu可能是造成带宽不高的瓶颈？
或者有神什么提高的建议吗？

**Comment by pengjianzhang** [comment]
CPU不给力，没有办法。
你都要测这么高的性能，就不能备个好的服务器？

**Comment by thunderZH963** [comment]
是这样的，我们是做系统研究的，这件事情的target是在weak server上做一些合适的network application,去作为strong server的辅助，因此需要全面了解不同服务器性能。

**Comment by thunderZH963** [comment]
两个64 cpu cores + 128G mem Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz服务器之间是可以达到接近100G的，但换一个弱的看来目前是有bottleneck的。
感谢您的耐心解答！
