### ISSUE TITLE
Error: small packet_size

### ISSUE THREAD

**Issue by jiawen94** [baidu/dperf#158]
我打算测试不同tcp包长度的吞吐率（最小16 bytes），如果packet_size 调整到32或者以下，dperf会报Error: small packet_size，有什么方法可以解决吗？
配置
```
mode                        client
#tx_burst                    128
launch_num                  10
cpu                         2-3
rss     auto

protocol        tcp
#payload_size                1428
packet_size     16
duration                    500s
cps                         400
cc                          4000
keepalive                   1ms

#port                       pci             addr         gateway    [mac]
port                        0000:08:00.1    172.30.174.10   172.30.174.1

#                           addr_start      num
client                      172.30.174.10       1

#                           addr_start      num
server                      172.30.149.10       1
#                           port_start      num
listen                      8866              1
```

**Comment by pengjianzhang** [comment]
packet size包含了以太网、IP、TCP头部

**Comment by jiawen94** [comment]
你好，我很想拿dperf取代iperf测试吞吐率，我这两天测试下来，又遇到一些疑问，请教一下：
1.packet_size参数和iperf的--len参数有什么换算关系吗？包含的固定长度是多少？我对这方面知识掌握的不够多。
2.之前都是通过直连网线测试的，最近把DUT通过交换机连接，发现dperf需要运行几十秒才开始发包和收包，不清楚前面为什么等那么就时间，如下图所示，30秒之后才开始发包
![image](https://user-images.githubusercontent.com/29114225/177979982-10e85e40-41c4-4245-a2b0-76d00b63c720.png)

3.我想用dperf取代iperf测试，从网关的流量图看，iperf3默认是单向流量（只有in或out的流量，除非加上--bidir参数测试双向），而dperf是双向流量（in和out都有流量），dperf是否支持类似iperf那种单向流量的测试模式？文档中好像没有提到类似的参数

**Comment by pengjianzhang** [comment]
1.packet_size参数和iperf的--len参数有什么换算关系吗？包含的固定长度是多少？我对这方面知识掌握的不够多。 
packet_size包含L3,L3,L4报文长度

2.之前都是通过直连网线测试的，最近把DUT通过交换机连接，发现dperf需要运行几十秒才开始发包和收包，不清楚前面为什么等那么就时间，如下图所示，30秒之后才开始发包
30秒有点不太正常，有wait, slow_start可以调整

3.我想用dperf取代iperf测试，从网关的流量图看，iperf3默认是单向流量（只有in或out的流量，除非加上--bidir参数测试双向），而dperf是双向流量（in和out都有流量），dperf是否支持类似iperf那种单向流量的测试模式？
如果是测带宽，可以用udp协议，单向流用flood参数


非常欢迎你使用dperf。dperf可以满足你的需求，你需要理解一下dperf的配置。使用物理网卡请注释rss配置，给服务器配置多个IP。这篇文章值得参考。
https://github.com/baidu/dperf/blob/main/test/performance/bandwidth/README.md
也请在企业内部、朋友之间宣传一下dperf，谢谢。

**Comment by jiawen94** [comment]
你好，之前你强调过测试带宽最好用UDP而不是TCP，我想知道是什么原因？
30s后才发包以及如何测试单向的问题，我周一再根据你说的方法验证一下。
