### ISSUE TITLE
dperf 如何添加vlan 头？

### ISSUE THREAD

**Issue by hgkiller** [baidu/dperf#159]
dperf 中可以添加像下面这种有vlan 头的配置吗

“pkt = Ether(dst="20:04:0f:68:5d:15")/Dot1Q(vlan=610)/IP(dst="172.16.96.101")”

**Comment by hgkiller** [comment]
对，就是物理网卡

**Comment by pengjianzhang** [comment]
可以试试
https://tonydeng.github.io/sdn-handbook/dpdk/offload.html

在DPDK中，在调用发送函数前，必须提前设置mbuf数据结构，设置PKT_TX_VLAN_PKT位，同时将具体的Tag信息写入vlan_tci字段。

**Comment by hgkiller** [comment]
嗯，感觉还是在dperf 中添加一个这个支持比较好

**Comment by pengjianzhang** [comment]
你能支持一下这个feature吗

**Comment by hgkiller** [comment]
我觉得你做起来会更快，O(∩_∩)O哈哈~

**Comment by pengjianzhang** [comment]
我没有物理网卡，我可以写一下，你帮我测可以吗

**Comment by hgkiller** [comment]
这个可以有

**Comment by pengjianzhang** [comment]
邮件联系
pengjianzhang@gmail.com

**Comment by pengjianzhang** [comment]
交换机上处理一下就好了吧，
dperf实现此功能的必要在哪里呢？

**Comment by hgkiller** [comment]
那不就是要改变交换机的配置吗，有些场景可以改变会影响的东西比较多

**Comment by pengjianzhang** [comment]
please test this branch, thanks
https://github.com/pengjianzhang/dperf/tree/vlan

**Comment by pengjianzhang** [comment]
在测吗？

**Comment by hgkiller** [comment]
验证了一下，感觉是没发出来。。。

**Comment by pengjianzhang** [comment]
ARP 正常吗，ICMP 正常吗

**Comment by hgkiller** [comment]
mode            client
cpu             0
slow_start      30
tx_burst        128
launch_num      10
payload_size    1
duration        1m
vlan            610

protocol        tcp
flood

cc              16k
cps             1k
keepalive       1ms

#port           pci             addr        gateway              [mac]
port            0000:43:00.1    192.168.60.2   192.168.60.3      20:04:0f:68:5d:15
#               addr_start      num
client          6.6.234.4       10
#               addr_start      num
server          172.16.96.101       1
#               port_start      num
listen          80              1

**Comment by pengjianzhang** [comment]
先用server模式运行，看看arp，icmp能不能正常工作

**Comment by pengjianzhang** [comment]
分支弄错了，不好意思，用这个分支：
https://github.com/pengjianzhang/dperf/tree/main

**Comment by hgkiller** [comment]
Ok   我重新试一下

**Comment by pengjianzhang** [comment]
在配置文件中加入 一行
vlan  VLANID
例子：
vlan 123

**Comment by hgkiller** [comment]
没发出来，这怎么看dperf 发出去的包？

**Comment by pengjianzhang** [comment]
把dperf的网关指向客户端，在客户端上抓包
网卡支持vlan卸载吗？

**Comment by hgkiller** [comment]
不行，实在发不出来，我还是用trex 吧

**Comment by hgkiller** [comment]
mode            client
cpu             0
tx_burst        128
launch_num      10
payload_size    1400
duration        1m
vlan            610

protocol        tcp
flood

cc              1k
cps             1k
keepalive       1ms

#port           pci             addr        gateway              [mac]
port            0000:41:00.0    192.168.60.2   192.168.60.1      00:50:56:a4:0c:54
#               addr_start      num
client          6.6.234.4       10
#               addr_start      num
server          192.168.60.1       1
#               port_start      num
listen          80              1

**Comment by pengjianzhang** [comment]
你用的什么网卡
看看网卡是否支持： ethtool -k eth0| grep vlan

**Comment by hgkiller** [comment]
0000:41:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=igb_uio unused=ixgbe,vfio-pci

**Comment by pengjianzhang** [comment]
用mode server模式运行
在客户端上ping 接口IP

**Comment by hgkiller** [comment]
这个抓包看了一下，vlan 还是没加上

**Comment by pengjianzhang** [comment]
你们有熟悉DPDK的同事吗，调试一下吧，大概就是看看我开启网卡的vxlan卸载特性设置对不对

**Comment by hgkiller** [comment]
`static inline void work_space_tx_send(struct work_space *ws, struct rte_mbuf *mbuf)
{
    struct tx_queue *queue = &ws->tx_queue;

```
  if( g_config.vlan_id > 0 ) {
        mbuf->ol_flags |= PKT_TX_VLAN;
        mbuf->vlan_tci = g_config.vlan_id;
        // printf("-> try to insert vlan_id@%d\n", mbuf->vlan_tci);
    }
```

    if (ws->vlan_id) {
        mbuf->ol_flags |= PKT_TX_VLAN;
        mbuf->vlan_tci = ws->vlan_id;
        // printf("try to insert vlan_id@%d\n", mbuf->vlan_tci);
    }

    net_stats_tx(mbuf);
    queue->tx[queue->tail] = mbuf;
    queue->tail++;
    if (((queue->tail - queue->head) >= queue->tx_burst) || (queue->tail == TX_QUEUE_SIZE)) {
        work_space_tx_flush(ws);
    }
}`

**Comment by pengjianzhang** [comment]
可以发出vlan报文？

**Comment by hgkiller** [comment]
可以了

**Comment by pengjianzhang** [comment]
请测一测，UDP，TCP，ICMP是否都正常

**Comment by hgkiller** [comment]
line 13: unknown config keyword("vlan") ......

**Comment by pengjianzhang** [comment]
我看下

**Comment by pengjianzhang** [comment]
vlan2分支?

**Comment by hgkiller** [comment]
可以了

**Comment by pengjianzhang** [comment]
再确认一下 UDP，TCP，ICMP 都是支持VLAN的是吗？

**Comment by hgkiller** [comment]
tcp udp 都是支持的

**Comment by pengjianzhang** [comment]
ping dperf的地址能通吗？

**Comment by hgkiller** [comment]
可以

**Comment by hgkiller** [comment]
另外，dperf 支持syn 包重传吗？

**Comment by pengjianzhang** [comment]
支持SYN包重传

**Comment by pengjianzhang** [comment]
非常感谢你的支持，dperf又多了一个特性，下个版本发布时向你致谢~

**Comment by hgkiller** [comment]
哈哈，我觉得dperf 的组包方式在灵活一些，就完全可以媲美trex了。。。

**Comment by pengjianzhang** [comment]
请详细说一下吧，有哪些灵活性的点。
dperf主要用来做四层性能测试，要做几十亿并发，几千万每秒新建，需要极简协议栈，与trex的定位不太一样

**Comment by hgkiller** [comment]
比如说，如果要测试toa， 需要对tcp 包做一些构造 或者其他对tcp 层包做一些定制化的时候。。。

**Comment by pengjianzhang** [comment]
是的；常见功能可以加进来，欢迎社区小伙伴一起来做
