### ISSUE TITLE
dperf error : Segmentation fault 

### ISSUE THREAD

**Issue by Danshanshu** [baidu/dperf#16]
启动后报错Segmentation fault 
![image](https://user-images.githubusercontent.com/98389566/150954572-85455673-4698-4fdb-b1a9-7890a2d2b4d5.png)

**Comment by pengjianzhang** [comment]
Did you bind the network port?

**Comment by pengjianzhang** [comment]
please contact me with email, thanks.

**Comment by pengjianzhang** [comment]
Can you send me an email and we can talk on the phone?

**Comment by Danshanshu** [comment]
可以的，18286682451



***@***.***#######
 
From: peng jianzhang
Date: 2022-01-25 18:34
To: baidu/dperf
CC: Danshanshu; Author
Subject: Re: [baidu/dperf] dperf error : Segmentation fault (Issue #16)
Can you send me an email and we can talk on the phone?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Danshanshu** [comment]
这是我的配置文件




***@***.***#######
 
From: ***@***.***
Date: 2022-01-25 18:37
To: baidu/dperf
Subject: Re: Re: [baidu/dperf] dperf error : Segmentation fault (Issue #16)
可以的，18286682451



***@***.***#######
 
From: peng jianzhang
Date: 2022-01-25 18:34
To: baidu/dperf
CC: Danshanshu; Author
Subject: Re: [baidu/dperf] dperf error : Segmentation fault (Issue #16)
Can you send me an email and we can talk on the phone?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Danshanshu** [comment]
> 启动后报错Segmentation fault ![image](https://user-images.githubusercontent.com/98389566/150954572-85455673-4698-4fdb-b1a9-7890a2d2b4d5.png)

mode        client
cpu         3
socket_mem  4096
duration    60s
cps         10k
port        0000:0b:00.0    172.16.10.100   172.16.10.1
client      172.16.10.100   2
server      41.38.0.7       1
listen      80              1

**Comment by Danshanshu** [comment]
> 

root@VM164309614001261:~/dperf# ./build/dperf -c test/http/client-test.conf
EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
Segmentation fault (core dumped)

**Comment by Danshanshu** [comment]
> > 
> 
> root@VM164309614001261:~/dperf# ./build/dperf -c test/http/client-test.conf EAL: Detected 16 lcore(s) EAL: Detected 1 NUMA nodes EAL: Multi-process socket /var/run/dpdk/rte/mp_socket EAL: Selected IOVA mode 'PA' EAL: Probing VFIO support... EAL: PCI device 0000:0b:00.0 on NUMA socket -1 EAL: probe driver: 15ad:7b0 net_vmxnet3 Segmentation fault (core dumped)

root@VM164309614001261:~/dpdk-stable-19.11.11# ./usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:0b:00.0 'VMXNET3 Ethernet Controller 07b0' drv=uio_pci_generic unused=vmxnet3

Network devices using kernel driver
===================================
0000:03:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens160 drv=vmxnet3 unused=uio_pci_generic *Active*

No 'Baseband' devices detected
==============================

No 'Crypto' devices detected
============================

No 'Eventdev' devices detected
==============================

No 'Mempool' devices detected
=============================

No 'Compress' devices detected
==============================

No 'Misc (rawdev)' devices detected
===================================

**Comment by pengjianzhang** [comment]
please try igb_uio.ko

**Comment by pengjianzhang** [comment]
cheers. we fixed it.
