### ISSUE TITLE
有没有更详细的日志。回显不知道怎么排查

### ISSUE THREAD

**Issue by YangLe-BJ** [baidu/dperf#160]
![image](https://user-images.githubusercontent.com/109845537/181010452-fde8b542-e0ef-44e0-9603-883bcadacbce.png)

**Comment by pengjianzhang** [comment]
什么网卡

**Comment by YangLe-BJ** [comment]
kvm虚拟机，virtio驱动。 
网卡绑定了eth1

**Comment by pengjianzhang** [comment]
贴一下配置

**Comment by YangLe-BJ** [comment]
感谢您的回复。刚才截图没上传完成就发送了 不好意思 
dpdk网卡绑定信息
![image](https://user-images.githubusercontent.com/109845537/181146566-be6d847c-c584-4158-ab42-987b4247182e.png)
大页配置
![image](https://user-images.githubusercontent.com/109845537/181146695-8521ed8a-3f41-4472-84e0-c43231ccc2a5.png)
网卡信息
![image](https://user-images.githubusercontent.com/109845537/181146853-13177d54-8922-4f73-8d0c-9b4ffc0fcf64.png)

**Comment by pengjianzhang** [comment]
发一下dperf配置

**Comment by YangLe-BJ** [comment]
是udp里的server.conf吗   这个还没改 
![image](https://user-images.githubusercontent.com/109845537/181148377-791062e8-03e8-4a4f-84f2-d38e27ab7447.png)

**Comment by pengjianzhang** [comment]
要根据你的实际环境修改一下，尤其是PCI号，网卡数量。可以参考一下主页readme上的文章，也可以看看我知乎上的文章。

能给项目加个star吗，谢谢！也请在周围小伙伴中帮忙宣传一下项目，谢谢~

**Comment by YangLe-BJ** [comment]
好的 一定！非常感谢您
