### ISSUE TITLE
可以用来测试网络设备带宽吗？

### ISSUE THREAD

**Issue by 119064273** [baidu/dperf#161]
可以达到线速发包吗，例如10G， 100G？

**Comment by pengjianzhang** [comment]
可以

**Comment by 119064273** [comment]
@pengjianzhang 例如发送1000000 个报文，然后在线速10G模式下，这种场景也是可以的是吧，发固定数目的报文？

**Comment by pengjianzhang** [comment]
可以控制发包的速度，报文大小，发包时间， 发送总报文数不能控制，不过有报文计数。你可以先试用一下。如果喜欢，请给项目加个star，谢谢。

**Comment by 119064273** [comment]
👌，“dperf一经开源，立即在圈内引发了关注，因为它卓越的性能（每秒1千万CPS，几十亿并发，100Gbps带宽），在部分场景下可代替售价数百万元的商用性能测试仪，为用户节省昂贵的测试仪购买成本”  ， 我们就是买不起商业测试仪器，想对我们diy的交换机做类似rfc2544测试（吞吐量测试；时延测试；丢包率；背靠背）啥的，能实现吗？或者有什么建议吗

**Comment by pengjianzhang** [comment]
基本上可以，时延你要实测一下，看看能不能达到要求，背靠背不懂
欢迎一起来推动dperf完善交换机场景的测试
