### ISSUE TITLE
编译安装问题

### ISSUE THREAD

**Issue by wangshuai199398** [baidu/dperf#162]
您好，咨询个问题：
在dpdk21.11上编译
meson build --prefix=/root/dpdk/dpdk-stable-21.11.1/mydpdk -Denable_kmods=true
生成的libdpdk.pc感觉不是我的代码生成的，我在rte_eal_init中添加的日志打印不出来
不知道这样编译正确吗？

**Comment by pengjianzhang** [comment]
dperf能正常启动吗

**Comment by pengjianzhang** [comment]
如果觉得dpdk21.11有问题，试试19.11

**Comment by pengjianzhang** [comment]
如果喜欢dperf，请给项目加个star哦，谢谢

**Comment by wangshuai199398** [comment]
> 如果喜欢dperf，请给项目加个star哦，谢谢

已加star，这个问题安装到系统目录就好了，安装到/root/dpdk/dpdk-stable-21.11.1/mydpdk用的时候不是我的dpdk库，能运行，但是现在报错没有网关，我这个服务器没有网关，不知道有没有环境搭建的配置文档？
谢谢。。
代码没细看，感觉写的很好，可以学习学习。

**Comment by pengjianzhang** [comment]
谢谢支持

1. 可以两个设备互打流量，互指网关就可以
2. 可以作为客户端发送单向报文
