### ISSUE TITLE
请教下配置文档没看懂的中server/client 和port的配置

### ISSUE THREAD

**Issue by YangLe-BJ** [baidu/dperf#163]
1.Port的数量是否取决于dpdk绑定了几张网卡？  比如只绑定了一张网卡  那么port只能是绑定的网卡的pci号，port的数量只能为1.
2.我当前的机器为8U16G 有两张网卡。其中dpdk绑定了一张网卡。如果按照port数量和server数量必须一致的要求。则server数量应该为1.  
如果按照server IP地址数目与CPU数目相等。 则数量应该为8. 这块没有搞明白 到底怎么配置？
![image](https://user-images.githubusercontent.com/109845537/183245552-840463c2-d1eb-4c01-afeb-fce0dcc226f7.png)

**Comment by pengjianzhang** [comment]
1. 是
2. ip数量与网卡（port）数量没关系。一张网卡上可以配置多个ip。

**Comment by YangLe-BJ** [comment]
_**ip数量与网卡（port）数量没关系。一张网卡上可以配置多个ip。**_
     1.我当前并没有在一个网卡上配置多个ip这个是否可以配置为>1呢？
     2.我只有1个port的情况下。 配置多个cpu是否是无意义的？并不能提高性能？

**Comment by pengjianzhang** [comment]
1. 可以，你需要把测试的网络环境设计好
2. 一般情概况下多个cpu是会提升性能的，因为一个cpu对应一个rx/tx队列。除非整个网络环境的性能不高。
