### ISSUE TITLE
一些注意事项是出于哪些方面考虑设计的呢？

### ISSUE THREAD

**Issue by ygm521** [baidu/dperf#164]
以下要求是出于哪些方面考虑的？代码对应处理逻辑在哪？谢谢。便于其他人加入项目维护中。
1.  在client模式下，'client'数量需要与'port'的数量一致，并且一一对应。 表示这个网口使用什么客户端地址池作为建连接的源地址。
2.  在server模式下, 'client'数量没有要求，可以比'port'多，也可以比'port'少。 表示server只接收哪些客户端的连接，dperf server不接受来自未知地址的连接请求。
3.  'port'的数量必须要与'server'的数量一致。 默认要求server IP地址数目与CPU数目相等，即每个worker线程分配一个。

**Comment by pengjianzhang** [comment]
client/server分别表示一个地址段，一个地址段只能配在一个网卡(port)上。
从性能考虑：一个客户端线程与一个服务器线程互打流量，每个线程占用1个CPU，性能是最高的。
从性能测试的需求：客户端需要大量IP，服务器只需要少量IP即可，每个服务器线程分片一个IP就可以满足需求，当然从性能角度考虑，每个线程分片一个IP，而不是一个port分配一个IP。
在有DUT（如四层负载均衡）的情况下，DUT会做地址转换，DUT可能有多个地址池，地址池中的任何一个IP都会作为原地址到达服务器线程，所以我们允许在server上配置多个client。

代码逻辑主要看config.c


欢迎加入dperf开发，如果能邮件说明一下背景就最好了。




 服务器只需要少量IP，客户端需要大量IP，我们让一个看
主要是出于性能考虑，

**Comment by ygm521** [comment]
1. 数据结构之间管理关系比较晕。比如 socket_table， socket_pool，  socket_port_table。 
2. 网卡支持对称rss，普通rss，网卡支持FDIR邮件特性等 各自注意点是什么？

**Comment by pengjianzhang** [comment]
你有物理机环境吗，可以从一个实际需求开始，这样熟悉dperf更快。
请看一下 vlan支持的issue

**Comment by ygm521** [comment]
我这没有硬件环境。^@^
