### ISSUE TITLE
fdir-flow director 网卡特性代码哪里用到呢？

### ISSUE THREAD

**Issue by ygm521** [baidu/dperf#166]
1，fdir-flow director 网卡特性代码哪里用到呢？
2，rte_flow 流分到指定队列不需要网卡特性吧？

**Comment by pengjianzhang** [comment]
1. flow.c 
2. 需要

**Comment by ygm521** [comment]
我看fdir-flow director 是需要使能网卡的 flow director功能，代码中没找到呢，请指点？
![image](https://user-images.githubusercontent.com/7271089/184293824-67c4f29c-ea04-4b52-9227-415e1cb96713.png)

**Comment by pengjianzhang** [comment]
本问题与dperf无关，最高到DPDK社区去讨论，也可以查阅DPDK文档与example，谢谢
