### ISSUE TITLE
dperf支持封装geneve报文吗？

### ISSUE THREAD

**Issue by wangjun0728** [baidu/dperf#167]
在我们云网络环境中，可能会需要使用geneve封装报文使用上会更好

**Comment by pengjianzhang** [comment]
不支持，欢迎提交pull request支持，请参考VXLAN的支持

**Comment by wangjun0728** [comment]
在这种场景下ECS(ovs)------gateway(ovs-dpdk)，测试网关性能时，不想过多的创建虚机，直接发送封装报文到网关去测试，再解封装送出去，这样测试单个网元会更灵活，如果能支持会很棒，目前ovs使用的geneve和vxlan比较普遍。

**Comment by pengjianzhang** [comment]
你们可以支持一下，应该比较容易，我给你们review
