### ISSUE TITLE
dperf的cps参数解释？

### ISSUE THREAD

**Issue by wangjun0728** [baidu/dperf#168]
配置文件中cps是新建会话速率吗？按照cps的测试逻辑应该是一边建立连接一边拆除连接，然后我还能保持到一定的新建连接速率为cps；
并发的过程每秒多少个连接这是qps；
我们这这个“CPS”是指哪一种？还是都可以做到？

**Comment by pengjianzhang** [comment]
CPS： 新建连接数
QPS：是每秒请求数，可以用keepalive调节
