### ISSUE TITLE
虚机互打测试带宽

### ISSUE THREAD

**Issue by windc131** [baidu/dperf#169]
1.云上两台虚机互打流量，仅绑定一块网卡的情况下能否用多cpu，多队列打流；
2.另外我按照下面配置打流，cpu使用率一直都只有25%，是哪边配置有误吗，如何把cpu打上去？
mode                        client
tx_burst                    128
rss             auto
launch_num                  10
cpu                         1
payload_size                1400
duration                    20m
cps                         400
cc                          600000
keepalive                   1ms
port        0000:00:03.0    192.168.10.3   192.168.10.254
client      192.168.10.3     100
server      10.255.110.209   1
listen 80 10

**Comment by pengjianzhang** [comment]
打带宽参考一下文章 [Using dperf to test network bandwidth](https://github.com/baidu/dperf/blob/main/test/performance/bandwidth/README.md)

可以配多个CPU，请参考doc目录下的配置文档
测带宽建议用UDP协议
并发调小点

这两篇文章是GOOGLE,AWS云上测试PPS的，有参考意义
https://zhuanlan.zhihu.com/p/523618346
https://zhuanlan.zhihu.com/p/515594359

如果喜欢dperf，请给项目加个star，也给周围的小伙伴宣传下，谢谢
