### ISSUE TITLE
dperf 三层网络

### ISSUE THREAD

**Issue by edwnorton** [baidu/dperf#171]
您好， 我想使用dperf测试dpvs的性能，我们的环境走了三层网络，fullnat模式， 请求路径为
 客户端源IP（A）--->dpvsvip(B)--->fullnat localip（C)---> 后端IP(D) 
如果使用dperf是否可以支持，有没有文档可以参考？ 感谢！

**Comment by pengjianzhang** [comment]
可以。
请参考doc下面的配置文档，例子，知乎上的文档也可以参考，在fullnat模式下，客户端，服务器的配置需要配置正确的client,server字段。
如果喜欢dperf，请给项目加个star~~，谢谢~~
