### ISSUE TITLE
dperf为什么没有 dpdk app的（EAL common options）标准输入？

### ISSUE THREAD

**Issue by gotostack** [baidu/dperf#178]
例如：
`  -a, --allow         Add a device to the allow list.
                      Only use the specified devices. The argument format
                      for PCI devices is <[domain:]bus:devid.func>.
                      This option can be present several times.
                      [NOTE: allow cannot be used with block option]`

服务器上有多个mellanox的设备，该输入可以指定用某一个网卡来测试。

再如：
`  -l CORELIST         List of cores to run on
                      The argument format is <c1>[-c2][,c3[-c4],...]
                      where c1, c2, etc are core indexes between 0 and 128`

指定服务器的某些core用来测试。

还是我打开方式不对？

谢谢

**Comment by pengjianzhang** [comment]
dperf使用配置文件来启动。
请参考dperf的配置手册，readme。
如果喜欢dperf，请给项目加个star，谢谢~

**Comment by gotostack** [comment]
建议搞个conf sample

**Comment by pengjianzhang** [comment]
好的 很好的建议 谢谢
