### ISSUE TITLE
dperf服务启动不成功port init fail、dpdk init fail

### ISSUE THREAD

**Issue by zero-yx** [baidu/dperf#179]
服务端机器执行如下

`./build/dperf -c server.conf`

```
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:00:0a.0 on NUMA socket -1
EAL:   probe driver: 8086:100e net_e1000_em
port init fail
dpdk init fail
```
不知道为什么初始化失败？

**Comment by pengjianzhang** [comment]
1.确认一下dpdk是否支持该网卡
2. 贴一下配置文件
3. 贴一下环境信息，网卡pic号, cpu个数

**Comment by zero-yx** [comment]
1、配置文件
2、
cpu个数

网卡信息(后面几个都一样，并且检测：ethtool -l 网卡名称&nbsp; &nbsp; 不支持这个命令操作)应该是这里有问题


pci信息，之前都用的箭头指向的网卡，怀疑其有问题后，后3个换成以下

经检查不支持多队列




3、总结：目前需要virtual box设定多队列网卡，但是不知道怎么在vb中设置。dpdk必须多队列网卡支持







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jianzhang ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 晚上8:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baidu/dperf] dperf服务启动不成功port init fail、dpdk init fail (Issue #179)





 
1.确认一下dpdk是否支持该网卡
 2. 贴一下配置文件
 3. 贴一下环境信息，网卡pic号, cpu个数

**Comment by pengjianzhang** [comment]
dperf并不要求多队列网卡。不确定virtualbox 环境是否能运行dpdk

**Comment by zero-yx** [comment]
感谢您的指导
1、目测好像是启动成功了
2、依据您的建议我去检查是否支持dpdk了，于是按照安装dpdk后的验证方式，如下：
以下均是使用usertools/dpdk-setup.sh 执行的


①、使用x86的64c++编译工具进行编译
②、设置hugepage
③、insert igb模块
④、依据pci绑定网卡 （需要保证该网卡状态不是active）
⑤、进行examples/helloworld,进行编译并跑样例程序


最后我正准备给您说支持dpdk时，顺便再跑了一下服务 build/dperf -c&nbsp; server.conf&nbsp; 结果成果运行了


3、推断、总结：似乎从配置文件中，无法自动帮我绑定网卡，在我误打误撞手动绑定网卡之后运行才能成功跑通，这可能是dperf存在某些适配问题（猜测）。那么这问题该怎么处理呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jianzhang ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 晚上9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baidu/dperf] dperf服务启动不成功port init fail、dpdk init fail (Issue #179)





 
dperf并不要求多队列网卡。不确定virtualbox 环境是否能运行dpdk

**Comment by pengjianzhang** [comment]
dperf不会帮你绑定网卡，你需要先绑定网卡，文档里有写

**Comment by zero-yx** [comment]
啊、抱歉！作者，我没有看到这一条，我再回去认真看一下文档。
感谢您的指点，本人目前大四，希望未来能有能力和机会加入到dperf中的开源建设，这真的太酷了
再次感谢您的指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jianzhang ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 上午10:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [baidu/dperf] dperf服务启动不成功port init fail、dpdk init fail (Issue #179)





 
dperf不会帮你绑定网卡，你需要先绑定网卡，文档里有写

**Comment by pengjianzhang** [comment]
欢迎加入，请留意邮件，有新的需求 我会写邮件通知你的

**Comment by JisonRWang** [comment]
您好，针对
> port init fail
> dpdk init fail

问题，我也贡献一下哈～
我也遇到了这个问题。通过在dperf代码dpdk.c中打printf()，发现是`port_init_all()`里面的`rte_eth_dev_count_avail()`返回值为0导致。同样，运行DPDK的dpdk-testpmd实例发现遇到同样的问题，都是获取不到网卡。最后通过numactl --hardware命令，发现我本机（物理机，并且全部在物理机上运行）NUMA上有4个node，一共128G内存，但是node0/node1各自有64G内存，node2/node3没有自己的内存，推测问题可能出在这里。所以去机房，把设备上的两条内存拔下来插到node2/node3上面，再运行dperf和dpdk-testpmd，就没有这个问题了。

**Comment by pengjianzhang** [comment]
是不是cpu 的 node 与 网卡的node不一样导致的？

**Comment by JisonRWang** [comment]
> 是不是cpu/大页的 node 与 网卡的node不一样导致的？ 我尝试修复一下，也请你帮忙测一下
在拔下两条node0/node1的32G内存条并插给node2/node3之前，我给node0和node1都用dpdk-hugepages.py分配了大页内存，并且只给这两个node分配大页内存，node2/node3是没有大页内存的（这俩节点都没有自己的内存，用numactl --hardware看的）。在第0个cpu核上运行dperf，该核在node0上。结果就是rte_eth_dev_count_avail()返回值为0，使用的dpdk版本为21.11.3。

另外，不好意思，我不明白您说的“网卡的node”是指？

**Comment by pengjianzhang** [comment]
应该是大页所在的node，与网卡所在的Node不一样

**Comment by pengjianzhang** [comment]
增加了出错提示信息，好像其他的也做不了

**Comment by JisonRWang** [comment]
> $ cat /sys/class/net/enp97s0f1np1/device/numa_node 
> 3

验证了！！！果然如您所说，这张网卡在node3上面，而之前开大页内存是在node0/node1上面，当时node2/node3都没有自己的内存，别说开大页内存了，但是这张网卡偏偏在node3上面！！！重新拔插内存条之后，给node2/node3添加了内存，现在每个node都有32G内存，
>$ numactl --hardware
available: 4 nodes (0-3)
node 0 cpus: 0 1 2 3 16 17 18 19
node 0 size: 32067 MB
node 0 free: 23417 MB
node 1 cpus: 4 5 6 7 20 21 22 23
node 1 size: 32253 MB
node 1 free: 23174 MB
node 2 cpus: 8 9 10 11 24 25 26 27
node 2 size: 32233 MB
node 2 free: 23854 MB
node 3 cpus: 12 13 14 15 28 29 30 31
node 3 size: 32253 MB
node 3 free: 23673 MB
node distances:
node   0   1   2   3 
  0:  10  16  16  16 
  1:  16  10  16  16 
  2:  16  16  10  16 
  3:  16  16  16  10 

>$ sudo dpdk-hugepages.py -s
Node Pages Size Total
2    8     1Gb    8Gb
0    8     1Gb    8Gb
3    8     1Gb    8Gb
1    8     1Gb    8Gb
Hugepages mounted on /dev/hugepages

并且给每个node都分配了大页内存，所以现在跑起来没问题啦～～～

**Comment by JisonRWang** [comment]
> 代码里增加了出错提示信息，好像其他的也做不了

这就已经很好了，要不是因为这次的错误提示，可能还找不到这次的问题原因呢。也给以后一个教训，就是好好看看NUMA每个node到底有多少内存，网卡在哪个node上，以免再出现这样的问题。
