### ISSUE TITLE
我单网口开启kni后启动dperf客户端，ctrl c退出的时候，机器总是会卡死，是已知问题吗

### ISSUE THREAD

**Issue by sheva7777** [baidu/dperf#182]

**Comment by pengjianzhang** [comment]
正常现象。
关闭dperf后，网卡没有恢复，机器失联了。
建议：
1.用两个网卡
2.网卡开启vf，dperf使用vf
3.dperf关闭后，恢复网卡

**Comment by sheva7777** [comment]
![image](https://user-images.githubusercontent.com/39009843/187572583-639ac240-45a9-4c11-b9e0-7a5a936ac2dc.png)
dperf客户端执行一段时间后会coredump

**Comment by pengjianzhang** [comment]
1. 请修改Makefile  -O3 改为 -O0，gdb定位一下在哪里coredump的
2. 请贴一下你的client, server 配置文件

**Comment by sheva7777** [comment]
![image](https://user-images.githubusercontent.com/39009843/187575207-d7bd6922-6614-4ea9-bc01-9d1228abe74f.png)

**Comment by pengjianzhang** [comment]
请输入： bt
看看调用栈

**Comment by sheva7777** [comment]
![image](https://user-images.githubusercontent.com/39009843/187575618-fd6ac96c-e6d5-46e7-a944-06eeb827bc9d.png)

**Comment by pengjianzhang** [comment]
能开个腾讯视频会议，联调一下吗，视频会议连接地址发到我邮箱，谢谢

**Comment by sheva7777** [comment]
mode        client
cpu         0
duration    600s
cps         5k
port      
client      
server      
listen      80              200
kni


mode        server
cpu         0
duration    100m
port       
client     
server     
listen      80              16
kni

**Comment by pengjianzhang** [comment]
1. 两个 listen 都改成 listen 80 1 试试
2. 把kni关掉试试

**Comment by sheva7777** [comment]
1试了，还是会coredump。2没试，就一个网口

**Comment by pengjianzhang** [comment]
client server 都 增加 protocol tcp试试

**Comment by pengjianzhang** [comment]
关掉kni，观察一下 是否会coredump

**Comment by sheva7777** [comment]
配置protocol udp，没有coredump，但是好像有显示问题
![image](https://user-images.githubusercontent.com/39009843/187580426-aa71eded-fd58-4a74-9e12-cd2a0900741b.png)

**Comment by pengjianzhang** [comment]
ok 你用的是最新的版本吗

**Comment by sheva7777** [comment]
客户端是1.3.0，服务端是1.1.0

**Comment by pengjianzhang** [comment]
都用1.1.0版本试试

**Comment by sheva7777** [comment]
都用1.1.0 没复现

**Comment by pengjianzhang** [comment]
看起来与kni有关系，临时修复了一下，请测一下这个分支，谢谢。
https://github.com/pengjianzhang/dperf/tree/crash

**Comment by pengjianzhang** [comment]
主干里已经修复了crash问题
protocol udp显示不正常的问题，麻烦说明一下如何复现，非常谢谢

**Comment by sheva7777** [comment]
> 主干里已经修复了crash问题，请测一下 protocol udp显示不正常的问题，麻烦说明一下如何复现，非常谢谢

crash的问题没有复现

**Comment by pengjianzhang** [comment]
udp统计不正常 能复现么

**Comment by sheva7777** [comment]
> udp统计不正常 能复现么

可以复现
client：
mode        client
protocol udp
cpu         0
duration    600s
cps         10k
port        
client                                   1
server                                  1
listen      80              1
kni


server:
mode        server
protocol udp
cpu         0
duration    100m
port        
client                        254
listen      80              16
kni

**Comment by pengjianzhang** [comment]
我这里没有复现这个问题，所以请你尽量把完整配置发一下，IP可以x.x.1.2，谢谢

**Comment by sheva7777** [comment]
hello，我使用过程中一直有个疑问，由于环境原因，我不能配置多个client ip，为了增加cps的数量，只能增加l4lb监听的vport数量。请问我1个client ip，200个监听，和200个client ip，1个监听或者50个client ip，4个监听 的测试结果可以看作一样的吗？

**Comment by pengjianzhang** [comment]
可以

**Comment by pengjianzhang** [comment]
这个issue先关了，UDP的统计问题 另开一个issue跟踪吧 麻烦了

**Comment by pengjianzhang** [comment]
UDP连接数统计错误的BUG，麻烦再测试一下，谢谢。

1. 是不是因为中间过了负载均衡?
2. 如果client直接请求server会不会出现统计错误？
3. 在运行过程中，出现统计错误是在什么时候，刚开始就错误？
4. 是否出现过UDP重传（udpRt不为0）？
