### ISSUE TITLE
dperf测试，客户端出现很多skErr

### ISSUE THREAD

**Issue by yfming** [baidu/dperf#186]
<img width="1251" alt="图片" src="https://user-images.githubusercontent.com/25922534/188537943-6409d3b0-5053-4be8-bba7-ef1a77ade6fb.png">

**Comment by pengjianzhang** [comment]
图片看不到

**Comment by pengjianzhang** [comment]
出现了很多SYN报文重传，检查一下配置，网络环境吧

**Comment by yfming** [comment]
dperf syn重传的时间间隔是多少呢？
客户端配置：
mode            client
slow_start      60
tx_burst        128
launch_num      10
cpu             1-16

payload_size    300
duration        10m

cps              1000k
#cc               5000k
#keepalive        100s

#port           pci             addr      gateway        [mac]
port            0000:19:00.0    192.168.100.71  192.168.100.35 B8:CE:F6:8D:CF:0A

#               addr_start      num
client          192.168.100.200  50

#               addr_start      num
server          192.168.100.80   16
#               port_start      num
listen          80               1

**Comment by pengjianzhang** [comment]
大概，1-3秒

测CPS的话，把payload_size设置为1吧

**Comment by yfming** [comment]
mellanox cx4-25g lx

**Comment by yfming** [comment]
我发现cps和cc不能同时测试啊。skcon达到cc配置的值之后就不发包了。

**Comment by pengjianzhang** [comment]
不能同时。
你想要同时，请调整keepalive，控制长连接持续时间

**Comment by yfming** [comment]
> 调整

dperf，在测试cps或者cc的时候，怎么控制pps或者qps呢？

**Comment by yfming** [comment]
> 不能同时。
> 
> 你想要同时，请调整keepalive，控制长连接持续时间
> 
> 

dperf，在测试cps或者cc的时候，怎么控制pps或者qps呢？

**Comment by pengjianzhang** [comment]
keepalive

**Comment by yfming** [comment]
keepalived设置很小，但是最多只能发和连接数相等的报文。不能继续加大pps了

**Comment by pengjianzhang** [comment]
keepalive能设置10us

**Comment by pengjianzhang** [comment]
参考这个文章
https://github.com/baidu/dperf/blob/main/test/performance/bandwidth/README.md


测带宽并不需要很大的并发，通常几百-几千就可以了，keepalive 设置为1ms，带宽并不需要很多CPU，主要看网卡能力，交换机能力。
tx_burst设置为4 - 16就可以了，不用设置很高

**Comment by pengjianzhang** [comment]
我一般会测一个cpu 一个队列的能力，然后再逐步增加cpu

**Comment by yfming** [comment]
我不是纯测带宽。想的是要在并发很大的情况下测试一下带宽能到多少

> 参考这个文章
> 
> https://github.com/baidu/dperf/blob/main/test/performance/bandwidth/README.md
> 
> 
> 
> 
> 
> 测带宽并不需要很大的并发，通常几百-几千就可以了，keepalive 设置为1ms，带宽并不需要很多CPU，主要看网卡能力，交换机能力。
> 
> tx_burst设置为4 - 16就可以了，不用设置很高
> 
>

**Comment by pengjianzhang** [comment]
为什么不用两套dperf呢

**Comment by yfming** [comment]
> 为什么不用两套dperf呢

没有那么多机器了。主要是一台dperf也没达到发包带宽，所以请教一下是不是有啥配置问题导致的，还是dperf的再高并发的情况下性能就是这样呢。

**Comment by pengjianzhang** [comment]
dperf的性能，请看项目主页readme
