### ISSUE TITLE
啟動 dperf server 時出現錯誤

### ISSUE THREAD

**Issue by Aiden128** [baidu/dperf#187]
環境是透過 Proxmox 建立的虛擬機：
- 虛擬機器 ubuntu：20.04.5
- dpdk：21.11
- dperf：1.3
- nic driver：VMware vmxnet3

已經確認 DPDK 可以執行 helloworld 並且進行綁定
- helloworld
![image](https://user-images.githubusercontent.com/143052/188834046-34e813f9-b24a-49a0-b3f0-5c00c95903db.png)

- 網卡綁定
![image](https://user-images.githubusercontent.com/143052/188834290-f64f2cee-9797-46cf-83bb-e10493137ed3.png)

執行 dperf 時出現如下錯誤：
![image](https://user-images.githubusercontent.com/143052/188834486-349e4cc9-76f0-4ca0-b7bc-c2b2b0745f98.png)

設定檔：
![image](https://user-images.githubusercontent.com/143052/188834779-e8b815bf-fb76-428e-9426-a27ab06b5291.png)

已經有參考其他人案例，但還是沒有發現相同原因，想請問是否有哪邊有沒有注意到的設定呢？

**Comment by pengjianzhang** [comment]
配置大页了吗

**Comment by pengjianzhang** [comment]
不妨试试dpdk-19.11，绑定igb_uio驱动
