### ISSUE TITLE
dperf 有没有加入https 协议支持的计划？

### ISSUE THREAD

**Issue by hgkiller** [baidu/dperf#188]
现在https, 或者说基于ssl/tls 的协议有很多了，而且应用的也比较多，dperf 能加入对这种协议的支持吗？

**Comment by pengjianzhang** [comment]
没有计划
dperf使用DPDK+用户态TCP协议栈，性能可以做到非常高；但是如果支持HTTPS，性能并不会比内核协议栈好很多，所以dperf并不适合这个场景。
