### ISSUE TITLE
为啥 server.c 里面没什么代码？

### ISSUE THREAD

**Issue by 1225951453** [baidu/dperf#19]
麻烦问一下，咱们这个项目，为啥 server.c 里面没什么代码？看您在design-CN.md里面的描述，github上的项目代码，是要当作客户端来使用是吗?用来测试服务器到底能承受多大的压力

**Comment by pengjianzhang** [comment]
麻烦问一下，咱们这个项目，为啥 server.c 里面没什么代码？
答：客户端、服务器的处理逻辑主要在udp.c，tcp.c，与协议栈深度融合了，这是为了性能考虑，缩短处理路径，提升性能。常规http server因为有操作系统、协议栈的隔离，做不到这一点，不过一些用户态协议栈如6wind的，把很多逻辑做成回调函数，与协议栈融合得比较高。

看您在design-CN.md里面的描述，github上的项目代码，是要当作客户端来使用是吗?用来测试服务器到底能承受多大的压力
答：dperf有两种运行模式，client/server，通过配置"mode"控制。主要用来测试一些网关设备（如四层负载均衡、防火墙等的）压力，这些网关设备一边连接客户端，一边连接服务器。普通服务器如nginx的性能达不到很高的量级，不需要dperf来测试，dperf功能有限，也不适合测试这些设备。
