### ISSUE TITLE
x710万兆直连测速异常

### ISSUE THREAD

**Issue by gong5311** [baidu/dperf#191]
作者好，我使用两台设备，各一张因特尔x710的万兆网卡直连，测试使用模板为test/performance/bandwith下的配置文件，测试结果bitsrx和bitstx显示结果异常，请问是哪里操作有问题吗？

**Comment by pengjianzhang** [comment]
请贴一下配置，截图统计

**Comment by gong5311** [comment]
不好意思，我这里手机端好像无法上传图片，可以麻烦提供一个邮箱吗

**Comment by gong5311** [comment]
![IMG_20220928_085132](https://user-images.githubusercontent.com/50473346/192664697-d2872719-e532-439d-bdea-1c85333acd3f.jpg)
![IMG_20220928_085217](https://user-images.githubusercontent.com/50473346/192664704-55afb4a4-b5b2-4ada-9e2b-7c63c6951950.jpg)
![Uploading IMG_20220928_091012.jpg…]()

**Comment by gong5311** [comment]
您好，配置和统计结果如图



---原始邮件---
发件人: "Jianzhang ***@***.***&gt;
发送时间: 2022年9月28日(周三) 上午9:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baidu/dperf] x710万兆直连测速异常 (Issue #191)




 
请贴一下配置，截图统计

**Comment by pengjianzhang** [comment]
pengjianzhang@gmail.com

**Comment by pengjianzhang** [comment]
统计中有很多drop，请把参数调小，然后再逐步调大试试
tx_burst 4
cc 1000
如果喜欢dperf，请加个star哦，谢谢

**Comment by gong5311** [comment]
好的，感谢回复！
