### ISSUE TITLE
Error: 'rss' is required if cpu num is not equal to server ip num

### ISSUE THREAD

**Issue by Sachi14** [baidu/dperf#192]
mode                        client
tx_burst                    128
launch_num                  10
cpu                         1-16

payload_size                1
duration                    10m

cps                         50k
cc                          10m
keepalive                 180s

#port                       pci             addr      gateway    [mac]
port                        0000:06:00.1    10.0.243.85 10.0.243.254  20:ce:2a:75:6c:41

#                           addr_start      num
client                      10.0.243.85		90

#                           addr_start      num
server                      10.0.243.83       1
#                           port_start      num
listen                      80              32

**Comment by pengjianzhang** [comment]
Maybe your network interface is a virtual network interface and does not support the FDIR feature, so you need to set 'rss'.
Please refer to the configuration documentation.
https://github.com/baidu/dperf/blob/main/docs/configuration.md.
I would appreciate it if you could add a star to dperf. Thanks.
