### ISSUE TITLE
dpdk22.03 Mellanox编译

### ISSUE THREAD

**Issue by js228** [baidu/dperf#193]
请问dpdk22.03还有自动打开Mellanox编译开关的功能嘛？有的话这个命令是在哪？

**Comment by pengjianzhang** [comment]
不能自动打开，dpdk会检测系统，自动打开。
有关闭的开关。
https://doc.dpdk.org/guides/prog_guide/build-sdk-meson.html
meson -Ddisable_drivers=event/*,net/tap

**Comment by js228** [comment]
您说的驱动是指Mellanox网卡驱动？
如果要对Mellanox网卡编译vpp的话就只需要安装Mellanox网卡驱动，
然后在编译VPP时在make命令加上vpp_uses_dpdk_mlx5_pmd=yes DPDK_MLX5_PMD_DLOPEN_DEPS=y就可以嘛？

**Comment by pengjianzhang** [comment]
> 您说的驱动是指Mellanox网卡驱动？ 
答：是

> 如果要对Mellanox网卡编译vpp的话就只需要安装Mellanox网卡驱动， 然后在编译VPP时在make命令加上vpp_uses_dpdk_mlx5_pmd=yes DPDK_MLX5_PMD_DLOPEN_DEPS=y就可以嘛？
答：VPP的编译不了解。我讲的是DPDK编译支持MLX

**Comment by js228** [comment]
dpdk会自动识别的话可以认为对intel网卡和Mellanox网卡编译的区别就是Mellanox需要安装OFED驱动，其它的没有区别？
可以认为是OFED驱动代替了igb_uio？

**Comment by pengjianzhang** [comment]
是的
默认会支持intel网卡的，Mellanox网卡是检测到驱动才安装的

**Comment by js228** [comment]
对于intel网卡，需要加载igb_uio驱动绑定网卡，dpdk才能识别该网卡，
但是mellanox网卡安装OFED驱动，dpdk也可以直接识别出mellanox网卡？
还是说同时有OFED和igb_uio驱动，dpdk识别的还是igb_uio驱动，而igb_uio会与OFED协作？

**Comment by pengjianzhang** [comment]
> 对于intel网卡，需要加载igb_uio驱动绑定网卡，dpdk才能识别该网卡， 但是mellanox网卡安装OFED驱动，dpdk也可以直接识别出mellanox网卡？ 

答：使用intel网卡需要帮网卡这个步骤，可以是igb_uio 或 uio_pci_generic 等；MLX网卡不需要这个步骤

> 还是说同时有OFED和igb_uio驱动，dpdk识别的还是igb_uio驱动，而igb_uio会与OFED协作？

答：不是。问题有点混乱。你去实践一下就知道了。

**Comment by js228** [comment]
就是mellanox网卡是不需要igb_uio这个驱动的对吧

**Comment by pengjianzhang** [comment]
是的

**Comment by js228** [comment]
请问已经安装了mlx驱动了，dpdk22.03无法识别是什么原因呢

**Comment by pengjianzhang** [comment]
我没有遇到过这种情况。你也可以试试这个驱动
https://github.com/linux-rdma/rdma-core
