### ISSUE TITLE
client mode下，keepalive参数不生效

### ISSUE THREAD

**Issue by nanlou** [baidu/dperf#194]
目的：hold住N条tcp连接，每条连接上间隔指定时间发送一个request，持续发送M个request

配置：根据[文档](https://github.com/baidu/dperf/blob/main/docs/configuration-CN.md)中的描述，keepalive interval(timeout) [num]可以满足需求，所以按如下配置
```bash
mode                        client
tx_burst                    128
launch_num                  10
cpu                         0

payload_size                1000
duration                    30s

cps                         1
cc                          10
keepalive                   100ms  20

#port                       pci             addr      gateway
port                        0000:03:02.0    192.168.0.222 192.168.0.1

#                           addr_start      num
client                      192.168.0.222               5

#                           addr_start      num
server                      192.168.0.159       1
#                           port_start      num
listen                      9999              1
```

预期应该是并发10条连接，每条连接上每100ms发送一次reqeust，但是实际行为与预期并不一致，每条连接上均只有一次request

**Comment by nanlou** [comment]
抓包看server是没关的，server现在不是dperf，是一个自己写的程序，抓包看server是回了keepalive的，抓包如图
![image](https://user-images.githubusercontent.com/5701870/195043967-b40cd254-5e82-429f-a54a-3a3b98eee26f.png)

**Comment by pengjianzhang** [comment]
需要开启http模式

**Comment by nanlou** [comment]
增加protocol字段后似乎仍然不生效
![image](https://user-images.githubusercontent.com/5701870/195046047-9c3e3ee2-cac3-4588-a9e3-663e1b720593.png)

**Comment by nanlou** [comment]
问题解决，看起来是需要标准的http response ，和状态码无关，刚从http_client_process_data里面看到http_parse_run结果为HTTP_PARSE_ERR时候会重新走socket_init_http了，感谢～
