### ISSUE TITLE
vxlan模式 client 启动时 报错 Error: Cannot enable vlan and vxlan at the same time

### ISSUE THREAD

**Issue by owenstake** [baidu/dperf#195]
采用vxlan client配置文件 test/vxlan/ipv4/vxlan-client1.conf

**Comment by pengjianzhang** [comment]
非常感谢 我晚点看下

**Comment by pengjianzhang** [comment]
请用这个版本测试一下，谢谢
https://github.com/pengjianzhang/dperf

**Comment by owenstake** [comment]
> 已经在下面的分支修复，请测试一下，谢谢 https://github.com/pengjianzhang/dperf

没问题

**Comment by pengjianzhang** [comment]
如果测试通过了 请告知一下
