### ISSUE TITLE
dperf对virtio网卡的支持并不是很好

### ISSUE THREAD

**Issue by cunfate** [baidu/dperf#197]
virtio网卡本身并不支持任何的硬件rss，因此在多队列virtio网卡压测的过程中会遇到以下问题：
1. rss只能配置成auto，而auto只能支持1个serverip
2. 在1的基础上，如果用两个多队列的virtio网卡对打，因为server端只能配置一个ip地址，则client只能用一个核压测。

是否可以改进成不支持rss的网卡，允许每个core接收一个队列，每个队列独立跑一个数据面线程？这样比较符合使用外部有vswitch并且在vswitch已经做好了rss的场景。

**Comment by pengjianzhang** [comment]
hi cunfate, 非常感谢你使用dperf，并提出如此宝贵的意见

1. client可以设置多个IP
2. vswitch这个场景 请详细说明一下

谢谢

**Comment by pengjianzhang** [comment]
hi cunfate，如果dperf支持这个特性，能不能帮忙测试一下，谢谢

**Comment by cunfate** [comment]
可以的，vswitch的场景

**Comment by pengjianzhang** [comment]
Hi cunfate，我先关掉issue，也欢迎继续讨论
