### ISSUE TITLE
一台机器两个网卡发包

### ISSUE THREAD

**Issue by yfming** [baidu/dperf#199]
两种使用方式都没起来：
1、如果我启动两个perf，按照手册，用这个参数socket-mem，加了后也不行，想请教一下正确的使用方式。
2、如果两个口做bond，配置如下：
`port            bond0:2(0000:19:00.0,0000:19:00.1)    192.168.100.62    192.168.100.35`
提示错误：
`Error: Cannot enable vlan and bond at the same time`

**Comment by pengjianzhang** [comment]
要两个网卡，每个dperf占一个网卡

**Comment by yfming** [comment]
我是分别尝试了用bond，或者两个网卡各启动一个dperf，都没起来。不是用了bond后启动两个dperf

**Comment by pengjianzhang** [comment]
贴一下你的机器配置，是否是双numa，dperf配置文件

**Comment by yfming** [comment]
我是同一个numa上的两个口，不能分别起一个dperf吗？
那如果我用bond可以吗？试了bond后，报上面那个错。

**Comment by pengjianzhang** [comment]
1. 我晚点验证一下
2. 这是一个bug，已经修复

**Comment by yfming** [comment]
谢谢回复，我是同一个网卡两个口，分别启用可以了。是我配置问题
> 贴一下你的机器配置，是否是双numa，dperf配置文件
> 
> 
> 
> 这个配置例子里面，两个dperf分别使用一张网卡，分别在两个Numa上，请参考一下
> 
> https://github.com/baidu/dperf/tree/main/test/multi-instance
> 
>
