### ISSUE TITLE
请教几个问题（关于多线程与网卡分流）

### ISSUE THREAD

**Issue by yfming** [baidu/dperf#2]
<img width="1041" alt="图片" src="https://user-images.githubusercontent.com/25922534/147810862-aa1a8103-8c1f-4caf-bbf0-46dd60583fd7.png">

**Comment by yfming** [comment]
每个线程绑定一个cpu核吗？ 
client每个线程只请求一个目的ip，意思是多核cpu的时候要配置很多个server ip吗？
server使用报文目的ip分流，是server收包分发队列分流吧，如果只配置一个server ip，就只能在一个核上处理报文了吗？这样会不满足测试性能吧
client上使用报文原ip分流，疑问是，client收到server回来的报文后的分发到不同队列吧？这样一个serverip的时候也只能在一个核上处理报文了嘛？

**Comment by pengjianzhang** [comment]
Q: 每个线程绑定一个cpu核吗？
A: yes

Q: client每个线程只请求一个目的ip，意思是多核cpu的时候要配置很多个server ip吗？
A: yes

Q: server使用报文目的ip分流，是server收包分发队列分流吧，如果只配置一个server ip，就只能在一个核上处理报文了吗？
A: yes

Q: 这样会不满足测试性能吧
A:  If testing L4LB, we can configure many VIPs on L4LB。The role of dperf server is RS.

Q: client上使用报文原ip分流，疑问是，client收到server回来的报文后的分发到不同队列吧？这样一个serverip的时候也只能在一个核上处理报文了嘛？
A: yes

**Comment by yfming** [comment]
多谢解答。我看测试用例都是配了一个server ip，所以又这些疑问

**Comment by yfming** [comment]
dperf作为rs，也需要配置很多ip来监听吧。因为每个server 线程只监听一个ip，是不是IP个数要和线程数相等？

**Comment by pengjianzhang** [comment]
More examples here:  test/performance/

**Comment by pengjianzhang** [comment]
Q: dperf作为rs，也需要配置很多ip来监听吧。因为每个server 线程只监听一个ip，是不是IP个数要和线程数相等？
A: yes

**Comment by pengjianzhang** [comment]
> 多谢解答。我看测试用例都是配了一个server ip，所以有这些疑问 dperf作为rs，也需要配置很多ip来监听吧。因为每个server 线程只监听一个ip，是不是IP个数要和线程数相等？

you'are very welcome!

**Comment by yfming** [comment]
多谢

**Comment by pengjianzhang** [comment]
> 多谢
don't mention it
