### ISSUE TITLE
main.c里面有个“daemon”变量，在我电脑上编译，提示 unuse

### ISSUE THREAD

**Issue by 1225951453** [baidu/dperf#20]
if (g_config.daemon) {
       daemon(1, 1); //？？？
    }
不太懂您这个 daemon(1, 1)的作用，麻烦解释一下，谢谢

**Comment by pengjianzhang** [comment]
请把编译提示贴一下
daemon就是后台运行。如果需要跑常稳，比如运行好几天，就需要打开daemon

**Comment by 1225951453** [comment]
warning: ignoring return value of ‘daemon’, declared with attribute warn_unused_result [-Wunused-result]
   62 |        daemon(1, 1);
      |        ^~~~~~~~~~~~

**Comment by pengjianzhang** [comment]
编译器版本

**Comment by pengjianzhang** [comment]
if (daemon(1, 1) != 0) {
            printf("daemon error\n");
            return 1;
        }
请这样试一下，是否还报错

**Comment by pengjianzhang** [comment]
> warning: ignoring return value of ‘daemon’, declared with attribute warn_unused_result [-Wunused-result] 62 | daemon(1, 1); | ^~~~~~~~~~~~
> 
> 我在我笔记本的虚拟机上编译的，ubuntu20.04

请试一下这个分支，是否报错，谢谢。  https://github.com/pengjianzhang/dperf

**Comment by 1225951453** [comment]
> > warning: ignoring return value of ‘daemon’, declared with attribute warn_unused_result [-Wunused-result] 62 | daemon(1, 1); | ^~~~~~~~~~~~
> > 我在我笔记本的虚拟机上编译的，ubuntu20.04
> 
> 请试一下这个分支，是否报错，谢谢。 https://github.com/pengjianzhang/dperf

好的

**Comment by 1225951453** [comment]
还有不理解daemon(1,1)这是什么用法，一个bool变量还能这么用?

**Comment by pengjianzhang** [comment]
> 

这是一个函数啊

**Comment by pengjianzhang** [comment]
给我发个邮件pengjianzhang@baidu.com，我邮件回给你吧

**Comment by 1225951453** [comment]
> 给我发个邮件[pengjianzhang@baidu.com](mailto:pengjianzhang@baidu.com)，我邮件回给你吧

好的
