### ISSUE TITLE
为什么server端回包 是 rst包，而不是fin报文？

### ISSUE THREAD

**Issue by owenstake** [baidu/dperf#200]
采用配置 test/http/client-cps.conf  test/http/server-cps.conf

**Comment by pengjianzhang** [comment]
是不是客户端IP、目的端口不在服务器的配置中

**Comment by owenstake** [comment]
> 是不是客户端IP、目的端口不在服务器的配置中，应该是配置上的问题，请仔细排查一下

you are right
