### ISSUE TITLE
统计指标 SynRt 太大，这意味着什么？

### ISSUE THREAD

**Issue by owenstake** [baidu/dperf#203]

**Comment by pengjianzhang** [comment]
压力太大，网卡或者中间设备上丢包了，把压力调小，把tx_burst调小，通常不需要设置tx_burst

**Comment by owenstake** [comment]
> 压力太大，网卡或者中间设备上丢包了，把压力调小，把tx_burst调小，如果不是测大带宽，就用默认值

嗯呢。我是测 测试qps

**Comment by pengjianzhang** [comment]
要设置keepalive，客户端上的超时，要比服务器上超时小
