### ISSUE TITLE
能否同时支持vlan和vxlan提问

### ISSUE THREAD

**Issue by ZSdut** [baidu/dperf#204]
不能同时支持vlan和vxlan吗，请问如果要支持，得解决哪些问题哦？谢谢

**Comment by pengjianzhang** [comment]
应该是可以的，主要是利用网卡的功能打vlan id；请参考一下VLAN的实现；如果你实现了此功能，欢迎提交进来

**Comment by ZSdut** [comment]
>我看您提交的那个代码中检查check_vlan函数中有
 if (cfg->vxlan_num) {
-        printf("Error: Cannot enable vlan and vxlan at the same time\n");
-        return -1;
-    }
-是这个包不能同时有vlan和vxlan吗

**Comment by pengjianzhang** [comment]
dperf现在不支持 VLAN + VXLAN 同时出现，应为没有这个需求。

**Comment by ZSdut** [comment]
有无设计文档看看，谢谢

**Comment by pengjianzhang** [comment]
请参考
 https://github.com/baidu/dperf/blob/main/docs/design.md
https://github.com/baidu/dperf/blob/main/docs/configuration.md

**Comment by ZSdut** [comment]
还有一个问题，我在每次发包的时候用软件加的vlan头（即用rte_insert_vlan）这导致mbuf里面的内容改变，所以我不得不在alloc一个mbuf的时候重新将l2l3l4重新copy上去，否则l2层的mac地址会失效。这违背了原来您的代码零拷贝的优势，请问有啥更好的办法解决这个问题吗？（还是用软件加vlan头这种办法）
