### ISSUE TITLE
mbuf_data_push_data支持传入datalen参数

### ISSUE THREAD

**Issue by nanlou** [baidu/dperf#205]
背景是udp/tcp的data需要传入一些raw data， hex convert to string后，中间包含了若干连续 '0'，mbuf_data_push_data中直接strlen(data)获取长度会被截断，导致发送的data不全

**Comment by pengjianzhang** [comment]
没太理解你的问题

**Comment by nanlou** [comment]
当前udp 默认发送的payload是用'a'填充的，如果需要发送的载荷包含连续的'0'，mbuf_data_push_data因为提取的payload长度是通过strlen来获取的，会导致这个长度是小于实际payload的，会被截断，比如hex_data = '0cea0120000100000000000105626169647503636f6d0000010001000029100000000000000c000a0008ec798115eb103e1b'

**Comment by pengjianzhang** [comment]
dperf没有问题，的修改dperf后出现了问题 是吗？

**Comment by nanlou** [comment]
> dperf没有问题，你修改dperf后出现了问题 是吗？

yes，我不确定是否这是共性需求（指定payload的padding内容），如果不是的话我就自己改了 hh

**Comment by pengjianzhang** [comment]
欢迎提一个pull request，我觉得这是一个需求，我觉得可以有几种输入形式
1. hex
2. 字符串
3. 文件

**Comment by nanlou** [comment]
> 欢迎提一个pull request，我觉得这是一个合理需求，我觉得可以有几种输入形式
> 
> 1. hex
> 2. 字符串
> 3. 文件
> 
> 有的测试支持从Pcap导入，也有的测试支持Lua脚本产生数据，这个可以暂时不支持。

实现了1-2的基本功能，以及tcp flood支持从配置文件配置tcp flags，代码写的比较烂...

**Comment by pengjianzhang** [comment]
请提pull request，我review一下，谢谢
