### ISSUE TITLE
如何让数据包的payload变随机值？

### ISSUE THREAD

**Issue by uname-v** [baidu/dperf#207]
# 背景
最近用dperf测试openvpn隧道的吞吐时，发现吞吐性能比预期高很多。经过抓包分析发现，dperf的包payload都是一串`aaaaaa`字符，太有规律了，openvpn的压缩算法让吞吐率高了不少。但是这种测试场景太过理想，实际场景下，payload应该偏向于随机。
<img width="1046" alt="截屏2022-11-26 03 00 34" src="https://user-images.githubusercontent.com/119074916/204042541-34761f7e-6c08-4d31-8337-bf6464b46f13.png">

# 问题
是否有办法让dperf包的payload变得随机？

**Comment by pengjianzhang** [comment]
hi uname-v，非常感谢使用dperf，尤其是这种新的场景。

目前为了性能考虑dperf的payload是一样的。
如果每个包数据都一样，但是报文内容随机，是否满足你的需求。
是否有其他工具能满足你的测试需求。

**Comment by uname-v** [comment]
可以的，希望你能将此功能加入到dperf中，让dperf越来越完善。

**Comment by uname-v** [comment]
目前用过一些测试工具，iperf3、pktgen-dpdk等，感觉dperf是**易用性**和**发包性能**综合来看是比较好的。

**Comment by pengjianzhang** [comment]
再确认一下，是不是这样
1. 所有报文的payload都是一样的（与当前相同）
2. 报文的payload的每个字节都是随机的（当前每个字节都是字符a）

**Comment by uname-v** [comment]
是的，我期望的就是这样子。谢谢🫶

**Comment by pengjianzhang** [comment]
ok 可以很快支持 到时候请多测试一下

**Comment by pengjianzhang** [comment]
请测试这个分支 https://github.com/pengjianzhang/dperf/  谢谢

**Comment by uname-v** [comment]
谢谢，我周一到内网环境测试下，有结果跟你反馈

**Comment by uname-v** [comment]
payload_random参数开启和关闭都测试并抓包看过，没问题。开启后，openvpn的吞吐也确实符合我的预期
![image](https://user-images.githubusercontent.com/119074916/204233793-a399b70c-8cfb-4e04-bc48-cf586091f99b.png)

**Comment by uname-v** [comment]
谢谢
