### ISSUE TITLE
Would you pleass add support to DPDK 22.11

### ISSUE THREAD

**Issue by ykzj** [baidu/dperf#209]
Good tool to test network performance. Since DPDK released [22.11](https://doc.dpdk.org/guides/rel_notes/release_22_11.html), I tried to compile dperf with DPDK 22.11 follow the instruction of this [link](https://github.com/baidu/dperf/blob/main/docs/build.md#build-dperf-with-dpdk-20), but failed.

Would you please add support to DPDK 22.11 and update the doc?

Thanks.

**Comment by pengjianzhang** [comment]
thanks for your advice. dperf should support dpdk 22.11.

**Comment by pengjianzhang** [comment]
please test this branch https://github.com/pengjianzhang/dperf, thanks.

build dpdk
cd /root/dpdk/dpdk-stable-22.11.1
meson build --prefix=/root/dpdk/dpdk-stable-22.11.1/mydpdk -Denable_kmods=true -Ddisable_libs=""
ninja -C build install

**Comment by pengjianzhang** [comment]
dpdk-22.11 is supported now

**Comment by ykzj** [comment]
great, thanks for your quickly response. love it.

**Comment by pengjianzhang** [comment]
please star dperf~~ thanks~
