### ISSUE TITLE
dperf和pktgen和f-stack的区别

### ISSUE THREAD

**Issue by CHRIS123540** [baidu/dperf#214]
pktgen是一个发包机器，f-stack用户态协议栈。dperf更倾向于后者吗？

**Comment by pengjianzhang** [comment]
可以这么理解。
dperf是网络性能测试仪，维护了一个轻量级的协议栈，满足三、四层性能测试场景；f-stack用的是freebsed的协议栈，可以跑很多应用程序。
t-rex与dperf类似，主要是针对性能测试，t-rex的协议栈比较复杂，支持复杂的7层测试功能，性能也比dperf低一些。

如果喜欢dperf，请加个star，谢谢~

**Comment by CHRIS123540** [comment]
了解了，那请问dperf的协议栈有实现流量控制吗。我在tcp.c的文件中没有看见这一块。

**Comment by CHRIS123540** [comment]
您的回答对我十分有用，感谢您的回答！

**Comment by pengjianzhang** [comment]
不客气，如果看到代码中的Bug，或者任何可以改进的地方，请告诉我，谢谢~
