### ISSUE TITLE
设置源IP和源端口随机遍历顺序

### ISSUE THREAD

**Issue by hgkiller** [baidu/dperf#223]
研究了一下dperf，设置源IP随机遍历的时候，首先使用设置的源端口，使用完源端口后，才会使用下一个IP，这个地方是否可以设置一个配置项，可以配置首先遍历源IP，还是源端口？

**Comment by pengjianzhang** [comment]
能说一下背景吗？为什么要这么做？

**Comment by hgkiller** [comment]
主要是在做对DTU设备做性能测试的时候，需要源IP足够离散，这样才能更均匀分布在不同的核上，如果离散度不够的话，虽然看着流量很大，但可能只附着在了几个核上，这样测出来的结果就意义不大了

**Comment by pengjianzhang** [comment]
一般网卡RSS使用5元组吧，端口变化，按道理也会有均匀的哈希

**Comment by pengjianzhang** [comment]
请测试一下这个分支，谢谢
https://github.com/pengjianzhang/dperf/tree/ipport

配置方法：
client_hop

**Comment by pengjianzhang** [comment]
麻烦抽空测一下，谢谢

**Comment by hgkiller** [comment]
好 ， 这个方法怎么使用

**Comment by pengjianzhang** [comment]
用这个分支，https://github.com/pengjianzhang/dperf/tree/ipport

在客户端配置中增加一条：
client_hop

**Comment by hgkiller** [comment]
这个是IP 随机，端口固定吗？

**Comment by pengjianzhang** [comment]
IP是顺序变化，端口也是顺序变化

**Comment by pengjianzhang** [comment]
你是要打单向流量还是双向流量？

**Comment by hgkiller** [comment]
```
mode            client
cpu             0
duration        4h
#tx_burst        10
#launch_num      2
cps             10
#cc              200
#keepalive       5s
vlan            812
#rss             l3l4

protocol    http

http_host   83.1.1.1

#port           pci             addr      gateway        [mac]
port            0000:0b:00.0    6.6.245.2 169.254.12.1  00:50:56:b7:57:2e

#               addr_start      num
client          6.6.245.2       10

#               addr_start      num
server          83.1.1.1       1

#               port_start      num
listen          80              1

lport_range     2000 2004

client_hop
```

我测出来的结果，ip 是随机的，源端口是固定的，

**Comment by pengjianzhang** [comment]
哦，那我就是记错了，曾经一个版本是端口也会变的

是否符合预期？
端口一起变化是否更好？

**Comment by hgkiller** [comment]
源ip 和 源端口 都在变是最好的啊

**Comment by hgkiller** [comment]
ok

**Comment by pengjianzhang** [comment]
你的range 设置太小了，lport_range     2000 2004

**Comment by hgkiller** [comment]
拉取最新代码验证，符合预期
![image](https://user-images.githubusercontent.com/9523250/216497647-9493ac08-4603-4dc5-a421-cf9c49f51a57.png)

**Comment by pengjianzhang** [comment]
已经合入主干了，请用主干再验证一下，谢谢~
