### ISSUE TITLE
测试单向pps，client配置了比较大的cc值，但是在服务端上看连接数很低

### ISSUE THREAD

**Issue by sheva7777** [baidu/dperf#226]
客户端cc配置了500k，服务端上看连接数只有5w左右

**Comment by sheva7777** [comment]
mode        client
cpu         0-3
duration    600s
cc          500k
rss         l3l4
flood
protocol    udp
packet_size 64
keepalive   10us
port        00.0    11   65
client      11     1
server      22      1
listen      80              10
kni

**Comment by pengjianzhang** [comment]
请把配置贴完整

**Comment by sheva7777** [comment]
服务器没配置deprf，测试单向的pps
mode        client
cpu         0-1
duration    600s
cc          500k
rss         l3l4
flood
protocol    udp
packet_size 64
keepalive   10us
port        0000:cc:00.0    10.10.10.11   10.10.10.1
client      10.10.10.11     1
server      10.10.10.22      1
listen      80              10
kni

**Comment by sheva7777** [comment]
我持续看了下，连接数也在增长，但是涨的非常缓慢

**Comment by pengjianzhang** [comment]
mode client
cpu 0-1
duration 600s
cps 50k
cc 500k
rss l3l4
flood
protocol udp
packet_size 64
keepalive 10us
port 0000:cc:00.0 10.10.10.11 10.10.10.1
client 10.10.10.11 100
server 10.10.10.200 1
listen 80 10
kni

**Comment by sheva7777** [comment]
请问下cps、cc和并发数的关系是啥

**Comment by pengjianzhang** [comment]
cps是每秒新建连接数，connections per second
cc是并发数，current connections，
达到一定的并发数，尤其是比较高的并发，需要一个较长的爬坡过程，通过cps设置每秒增加的连接数

**Comment by sheva7777** [comment]
我们发现并发数会影响pps性能，而且一般线上的并发数远大于几千，几十万并发数会更接近线上

**Comment by pengjianzhang** [comment]
ok，如果几十万并发的话，keepalive就要调大一点，另外你的cpu数量可以增加一些。
请向周围的小伙伴宣传、关注一下dperf吧，谢谢~~

**Comment by sheva7777** [comment]
请问下出现大量dropTx，是客户端性能问题吗

**Comment by pengjianzhang** [comment]
是的
1. 增加CPU个数
2. 检查网卡能力

**Comment by sheva7777** [comment]
方便加下微信吗

**Comment by pengjianzhang** [comment]
ok  pengjianzhang@gmail.com

**Comment by sheva7777** [comment]
我发现客户端的skCon=500,000，但是服务端的会话数（五元组）只有31250

**Comment by pengjianzhang** [comment]
配置贴一下

**Comment by sheva7777** [comment]
mode        client
cpu         0-15
duration    600s
cps         50k
cc          500k
rss         l3l4
flood
protocol    udp
packet_size 64
keepalive   1s
port        0000:cc:00.0    10.10.10.11 10.10.10.1
client      10.10.10.11     1
server      10.10.10.22      1
listen      8050              50
lport_range 1000 65535
kni

server没有配置，测试单向pps

**Comment by pengjianzhang** [comment]
你的配置可能支撑不了这么大的并发，client的IP多配一些，建议配100个看看，
client 10.10.10.11 100

**Comment by pengjianzhang** [comment]
那你就把server的端口数目增大试试
listen 8050 1000

**Comment by pengjianzhang** [comment]
你用1个cpu试试

**Comment by pengjianzhang** [comment]
你必须要打比较大的并发吗

**Comment by sheva7777** [comment]
我需要打比较大的并发，我希望并发可以较准确的控制

**Comment by pengjianzhang** [comment]
如果client，server双向都是dperf是没问题，单向的可能有点小bug

**Comment by sheva7777** [comment]
我晚点试下

**Comment by pengjianzhang** [comment]
seconds 46                 cpuUsage 16  16
pktRx   1                  pktTx    500,007            bitsRx   336                bitsTx  424,005,424        dropTx  0
tcpRx   0                  tcpTx    0                  udpRx    0                  udpTx   500,005
arpRx   1                  arpTx    1                  icmpRx   0                  icmpTx  0
tosRx   0                  otherRx  0                  badRx    0
udpRt   0                  udpDrop  0                  tcpDrop  0
skOpen  0                  skClose  0                  skCon    500,000            skErr   0
ierrors 0                  oerrors  0                  imissed  0

**Comment by pengjianzhang** [comment]
请测这个分支，谢谢
https://github.com/pengjianzhang/dperf/tree/flood

**Comment by hgkiller** [comment]
我也遇到这个问题了，抓包看了一下了一下，好像CC 是在一条连接上发送多个http 请求，如何设置一个tcp 连接上只发送一个http请求呢，同时也可以达到较大的tcp 并发连接

**Comment by pengjianzhang** [comment]
> hgkiller

可以尝试一下调节keepalive参数，client超时长，server超时短一点

**Comment by sheva7777** [comment]
> 请测这个分支，谢谢 https://github.com/pengjianzhang/dperf/tree/flood

使用这个分支可以达到50w并发
