### ISSUE TITLE
Mellanox CX6-DX 多端口启动dperf出现内存池创建失败

### ISSUE THREAD

**Issue by markchen7788** [baidu/dperf#227]
作者大大，请问您一下这是怎么回事呀？？？想用CX6的两个PF端口运行dperf,但是出现内存池创建失败，我给了25G的2048KB大页，怎么回事呀？顺便说一下，dperf真的很好用！！！
![图片](https://user-images.githubusercontent.com/50443757/213460188-9343dfa5-f870-48b6-ad2b-46d808d613fa.png)

**Comment by pengjianzhang** [comment]
地址数目太大，把地址数，端口数降一下，试试如下配置项

client ip1  10
client ip2  10

listen 80  4

喜欢dperf，请加个star哦，也请周围的小伙伴关注一下dperf，谢谢

**Comment by markchen7788** [comment]
大大，新年快乐，已经关注dperf了！！！我在单numa节点和双numa节点的服务器上都尝试过了，保持每一个cpu所在numa节点有20G的2048KB大页，但是第二个端口还是出现上述错误，请问还有什么其它可能的原因吗？？？

**Comment by pengjianzhang** [comment]
谢谢 祝新年快乐
你用dperf client直接打dperf server吗？

**Comment by markchen7788** [comment]
对的，主要是测试VNF的并发连接性能，然后目前想在dperf服务端开启多个mellanox VF port

**Comment by pengjianzhang** [comment]
不需要多个VF，试试1G大页吧
