### ISSUE TITLE
是否可以测试DNS服务器性能

### ISSUE THREAD

**Issue by zhiyuan2007** [baidu/dperf#229]
看到有个udp的支持，不知道能否支持dns服务器性能测试

**Comment by pengjianzhang** [comment]
非常感谢你对dperf的关注
dns有很多工具测试，一般性能也达不到四层负载均衡的性能量级，这个需求要认真评估下

**Comment by zhiyuan2007** [comment]
> 

谢谢， 普通版本的dns确实有dnsperf， queryperf等工具可以测试， 基于dpdk开发的dns，想知道有没有一个对应的测试工具

**Comment by zhiyuan2007** [comment]
好的，肯定有成熟的，我先找找看。

**Comment by pengjianzhang** [comment]
可以看下f-stack， trex，vpp，seastar

**Comment by zhiyuan2007** [comment]
谢谢
