### ISSUE TITLE
进行自动化测试

### ISSUE THREAD

**Issue by CHRIS123540** [baidu/dperf#234]
作者你好，请问dperf是否有实现在运行中改变配置的方法。比如写一个自动化脚本。

**Comment by pengjianzhang** [comment]
请详细描述一下，我还get到你的想法

**Comment by CHRIS123540** [comment]
比如我想利用dperf每隔10s改变一下cc数量，但不是通过down掉dperf，重新写config文件。而是在dperf运行中时，有没有一种途径能直接改变。

**Comment by pengjianzhang** [comment]
为什么要有这个功能呢，测到最高值就好了

**Comment by CHRIS123540** [comment]
如果单纯做压测dperf足够优秀了，统计数据也很详细。如果能有上述的这个功能，可以在测试其他网络功能（比如内核流控）的时候更加灵活。我看仓库里面没有提到相关内容，咨询一下。

**Comment by pengjianzhang** [comment]
深入探讨一下？ 给我发个会议连接 pengjianzhang@gmail.com
