### ISSUE TITLE
build_dpdk_2x.sh脚本可能有点问题

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#235]
脚本中这一句后面是不是多了个“/”
HOME_DIR=/root/dpdk/
log如下

  User defined options
    prefix      : /root/dpdk**//**dpdk-stable-22.11.1/mydpdk
    disable_libs: ""
    enable_kmods: true

Found ninja-1.11.0 at /usr/bin/ninja

另外即便修改了这个，执行脚本也没有安装成功

**Comment by pengjianzhang** [comment]
可能与环境有关
请修复一下吧，谢谢

**Comment by digger-yu** [comment]
脚本的最后有一些报错
Installing symlink pointing to librte_baseband_turbo_sw.so.23.0 to /root/dpdk/dpdk-stable-22.11.1/mydpdk/lib/x86_64-linux-gnu/dpdk/pmds-23.0/librte_baseband_turbo_sw.so.23
Installing symlink pointing to librte_baseband_turbo_sw.so.23 to /root/dpdk/dpdk-stable-22.11.1/mydpdk/lib/x86_64-linux-gnu/dpdk/pmds-23.0/librte_baseband_turbo_sw.so
Running custom install script '/bin/sh /root/dpdk/dpdk-stable-22.11.1/config/../buildtools/symlink-drivers-solibs.sh lib/x86_64-linux-gnu dpdk/pmds-23.0'
正克隆到 'dpdk-kmods'...
remote: Enumerating objects: 537, done.
remote: Counting objects: 100% (537/537), done.
remote: Compressing objects: 100% (345/345), done.
remote: Total 537 (delta 168), reused 372 (delta 85)
接收对象中: 100% (537/537), 120.94 KiB | 33.00 KiB/s, 完成.
处理 delta 中: 100% (168/168), 完成.
make -C /lib/modules/4.15.0-20-generic/build/ M=/root/dpdk/dpdk-kmods/linux/igb_uio
make[1]: 进入目录“/usr/src/linux-headers-4.15.0-20-generic”
  CC [M]  /root/dpdk/dpdk-kmods/linux/igb_uio/igb_uio.o
symbolmap: 00000001: invalid section
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/dpdk/dpdk-kmods/linux/igb_uio/igb_uio.mod.o
  LD [M]  /root/dpdk/dpdk-kmods/linux/igb_uio/igb_uio.ko
make[1]: 离开目录“/usr/src/linux-headers-4.15.0-20-generic”
正克隆到 'dperf'...
remote: Enumerating objects: 1252, done.
remote: Counting objects: 100% (401/401), done.
remote: Compressing objects: 100% (175/175), done.
remote: Total 1252 (delta 262), reused 237 (delta 226), pack-reused 851
接收对象中: 100% (1252/1252), 372.96 KiB | 52.00 KiB/s, 完成.
处理 delta 中: 100% (860/860), 完成.
Makefile:31: *** "no installation of DPDK found"。 停止。
root@dperf:~#

看起来是安装dperf的时候没有找到dpdk
但默认变量设置的是这个，这里的路径可能有点问题
export PKG_CONFIG_PATH=$HOME_DIR/$DPDK_DIR/mydpdk/lib64/pkgconfig

实际上在dpdk对应路径里面并没有lib64
root@dperf:~/dpdk/dpdk-stable-22.11.1/mydpdk# ls
bin  include  lib  share
root@dperf:~/dpdk/dpdk-stable-22.11.1/mydpdk#
root@dperf:~/dpdk/dpdk-stable-22.11.1/mydpdk# find ./ -name pkgconfig
./lib/x86_64-linux-gnu/pkgconfig
root@dperf:~/dpdk/dpdk-stable-22.11.1/mydpdk#
root@dperf:~/dpdk/dpdk-stable-22.11.1/mydpdk/lib/x86_64-linux-gnu# pwd
/root/dpdk/dpdk-stable-22.11.1/mydpdk/lib/x86_64-linux-gnu
root@dperf:~/dpdk/dpdk-stable-22.11.1/mydpdk/lib/x86_64-linux-gnu#

**Comment by pengjianzhang** [comment]
不好意思，这个脚本没在Ubuntu上验证过
看起来是DPDK编译不完整

**Comment by digger-yu** [comment]
请问re2c这个包主要作用是什么，是必须安装的么

**Comment by pengjianzhang** [comment]
ninja的依赖

**Comment by digger-yu** [comment]
https://github.com/baidu/dperf/compare/main...digger-yu:dperf:main

适配了一下ubuntu，由于下载较慢，脚本中注释了
#wget http://fast.dpdk.org/rel/$DPDK_XZ
##############################
root@dperf:~#  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
root@dperf:~# python3 -V
Python 3.9.15
root@dperf:~# ./dperf/build/dperf -v
1.4.0
root@dperf:~# ./dperf/build/dperf -h
-h --help
-v --version
-t --test       Test configure file and exit
-c --conf file  Run with conf file
-m --manual     Show manual
root@dperf:~#

**Comment by pengjianzhang** [comment]
请提交一个pull request吧

**Comment by digger-yu** [comment]
> 2\. 如果当前目录有dpdk就不下载

第一个不会写，第二个硬憋了一个，未验证

https://github.com/baidu/dperf/compare/main...digger-yu:dperf:main

**Comment by pengjianzhang** [comment]
还是修改原来的文件吧，只维护一个文件简单点，不要创建新的文件

**Comment by digger-yu** [comment]
> 还是修改原来的文件吧，只维护一个文件简单点，不要创建新的文件

那还得加上当前操作系统的判断，整复杂了就

**Comment by pengjianzhang** [comment]
re2c可以升级一下

**Comment by digger-yu** [comment]
> re2c可以升级一下

我试了一下，不安装re2c的前提下，dpdk和dperf也能正常装

**Comment by digger-yu** [comment]
> > re2c可以升级一下
> 
> 我试了一下，不安装re2c的前提下，dpdk和dperf也能正常装

https://github.com/baidu/dperf/compare/main...digger-yu:dperf:main
修改了判断条件里的错误，末尾增加apt -y 参数，该版本已经实际验证过

就是实际运行dperf前，还需要手工添加一下
export LD_LIBRARY_PATH=/root/dpdk-stable-22.11.1/mydpdk/lib/x86_64-linux-gnu/

**Comment by digger-yu** [comment]
> 请提一个pull request，比较方便讨论代码，谢谢 https://zhuanlan.zhihu.com/p/485869677

我就是看这个文章操作的，Git不太熟
请教这个链接是pull request么
新增了环境变量的添加，目前在ubuntu上已经比较完善
https://github.com/baidu/dperf/compare/main...digger-yu:dperf:main

**Comment by pengjianzhang** [comment]
在github页面上 你的dperf项目点pull request

**Comment by digger-yu** [comment]
> 在github页面上 你的dperf项目点pull request

上面链接就是
https://github.com/baidu/dperf/compare/main...digger-yu:dperf:main
这个不对么

**Comment by pengjianzhang** [comment]
你没有点提交

**Comment by digger-yu** [comment]
> 你没有点提交

这次应该可以了，哈哈，头一次整这个
