### ISSUE TITLE
请问下怎么配ip

### ISSUE THREAD

**Issue by 19951138239** [baidu/dperf#238]
请问下server.conf里的ip有什么用。网卡绑定了dpdk驱动还能配上ip吗

**Comment by pengjianzhang** [comment]
网卡交由dperf接管，IP也交由dperf接管，IP是配置在dperf的配置文件里

**Comment by 19951138239** [comment]
![image](https://user-images.githubusercontent.com/71491568/217738889-e5b20c82-5086-4738-8979-c16495d0e510.png)
请问下具体怎么配置，比如上面这个http的sercer-cps.conf，我修改好了，直接./build/dperf -c test/http/server-cps.conf就配置上ip了吗，  我看到有个配置里有个kni的说明，好像也是给端口配置ip的。
请问下具体怎么配置，文档不全，很难把程序开起来测试，我搞好了的话后面编写个文档。

**Comment by 19951138239** [comment]
已经知道怎么解决了，感谢作者的回复
