### ISSUE TITLE
dperf 长时间运行后，不能正常发包

### ISSUE THREAD

**Issue by hgkiller** [baidu/dperf#240]
发现dperf 存在一个问题，配置文件中设置了运行4h,  dperf 在开始运行时还算正常，尝试了几次，每次运行大概40分钟左右后，dperf 基本就不能发包建连接了，这时候ctrl+c 停止dperf ，也不能正常停止了，只能强制kill

**Comment by pengjianzhang** [comment]
请贴一下配置
另外请gdb看一下到底是卡在哪里了
