### ISSUE TITLE
请教个俩网卡在一个机器上的配置问题

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#242]
#相关版本说明
Ubuntu 18.04
dpdk  22.11.1
dperf 1.4.0 
cpu只有一个NUMA 
网卡信息：intel 82599 万兆双网口

0000:05:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=igb_uio unused=ixgbe
0000:05:00.1 '82599ES 10-Gigabit SFI/SFP+ Network Connection 10fb' drv=igb_uio unused=ixgbe
（试过ixgbe驱动，dperf起不来，又换回了igb_uio）

#拓扑
dperf client -----DUT lan    DUT wan------dperf server 
DUT为普通路由器，wan侧已配置静态ip
DUT为千兆口，dperf均为10G 口
#################
mode                         client
tx_burst                     16
socket_mem                   0
launch_num                   10
#rss                         auto
cpu                          0
protocol                     tcp
#payload_size                 1
duration                     20s
cps                          10
#cc                           3000
keepalive                     1ms
#port pci addr gateway [mac]
port         0000:05:00.1     192.168.10.10 10.1.1.1  D4:35:38:77:6E:BE
client       192.168.10.10      10
server       10.1.1.1        1
listen       80              1
#################
mode            server
#tx_burst       16
socket_mem      0
launch_num      10
#rss            auto
cpu             0
protocol        tcp
duration        60s
keepalive       10ms
#payload_size    64
#port pci addr gateway [mac]
port            0000:05:00.0 10.1.1.1 192.168.10.10 3C:CD:57:35:52:00
client          192.168.10.10 20
server          10.1.1.1 1
listen          80 1
#################
反复调整了client和server的配置，这个配置目前是可以运行的，但在server上没有计数
感觉是和server侧的dperf不通

配置文件中的ip地址及mac都是正确的
也试过将配置中的网关地址换成真实网关地址，结果是一样的，在server上都没有计数

目前client侧输出如下
-------------
Test Finished
-------------
pktRx   442                pktTx    1,913              bitsRx   309,040            bitsTx  947,056            dropTx  0
tcpRx   0                  tcpTx    1,900              udpRx    0                  udpTx   0
arpRx   5                  arpTx    13                 icmpRx   392                icmpTx  0
tosRx   0                  otherRx  22                 badRx    23
synRx   0                  synTx    1,900              finRx    0                  finTx   0                  rstRx   0          rstTx 0
synRt   1,420              finRt    0                  ackRt    0                  pushRt  0
tcpDrop 0                  udpDrop  0
skOpen  480                skClose  440                skCon    40                 skErr   440
httpGet 0                  http2XX  0                  httpErr  0
ierrors 0                  oerrors  0                  imissed  0

server 侧输出如下
-------------
Test Finished
-------------
pktRx   0                  pktTx    2                  bitsRx   0                  bitsTx  672                dropTx  0
tcpRx   0                  tcpTx    0                  udpRx    0                  udpTx   0
arpRx   0                  arpTx    2                  icmpRx   0                  icmpTx  0
tosRx   0                  otherRx  0                  badRx    0
synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx0
synRt   0                  finRt    0                  ackRt    0                  pushRt  0
tcpDrop 0                  udpDrop  0
skOpen  0                  skClose  0                  skCon    0                  skErr   0
httpGet 0                  http2XX  0                  httpErr  0
ierrors 0                  oerrors  0                  imissed  0

请教这个问题应该怎么排查呢

**Comment by pengjianzhang** [comment]
client， server绑不同的CPU，用不同的大页

相关配置项：
cpu 
socket_mem 0

**Comment by digger-yu** [comment]
> client， server绑不同的CPU，用不同的大页
> 
> 相关配置项： cpu socket_mem

client用cpu0 server用cpu1 这个修改简单，但改了还是没效果
请教大页怎么用不同的，我看网上有这种配置，但我这个设备就一个node0
echo 2048 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
echo 2048 > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages
##############
root@server:~# cat /sys/devices/system/node/
has_cpu            has_normal_memory  online             power/
has_memory         node0/             possible           uevent
root@server:~# cat /sys/devices/system/node/

另外，socket_num 该怎么配置，这个参数的配置没太理解，有一个issue里面是2500,0,0,0 请问三个逗号的0代表啥呢

##############
mode                         client
tx_burst                     16
socket_mem                   0
launch_num                   10
#rss                         auto
cpu                          0
protocol                     tcp
#payload_size                 1
duration                     20s
cps                          10
#cc                           3000
keepalive                     1ms
#port pci addr gateway [mac]
port         0000:05:00.1     192.168.10.10 10.1.1.1  D4:35:38:77:6E:BE
client       192.168.10.10      10
server       10.1.1.1        1
listen       80              1
#################
mode            server
tx_burst        16
socket_mem      0,0
launch_num      10
#rss            auto
cpu             1
protocol        tcp
duration        60s
keepalive       10ms
#payload_size    64
#port pci addr gateway [mac]
port            0000:05:00.0 10.1.1.1 192.168.10.10 3C:CD:57:35:52:00
client          192.168.10.10 20
server          10.1.1.1 1
listen          80 1
######################

**Comment by pengjianzhang** [comment]
假设系统有10G大页，每个进程配5G
参考 DPDK手册

**Comment by digger-yu** [comment]
> 假设系统有10G大页，每个进程配5G 参考 DPDK手册, socket_mem 启动参数


最开始就是client 的socket_num 128,0 
server socket_num 0,128
但启动会报错，是大页不够么
root@server:~# ./dperf/build/dperf -c ./dperf/digger/server-throughput.conf
EAL: Detected CPU lcores: 8
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/9369/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Not enough memory available on socket 1! Requested: 128MB, available: 0MB
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
rte_eal_init fail
dpdk_eal_init fail
dpdk init fail
大页里是有free部分的
root@server:~# cat /proc/meminfo | grep Huge
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
HugePages_Total:    7517
HugePages_Free:     7514
HugePages_Rsvd:       61
HugePages_Surp:        0
Hugepagesize:       2048 kB
root@server:~#

**Comment by pengjianzhang** [comment]
假设你有100M大页，每个进程分50M
配置方法：
socket_mem 50

**Comment by digger-yu** [comment]
> 单NUMA，假设你有100M大页，每个进程分50M 配置方法： socket_mem 50
> 
> 没测试过，一个NUMA跑两个进程，一般分到两个NUMA上

--socket-mem 1024,2048
This will allocate 1 gigabyte of memory on socket 0, and 2048 megabytes of memory on socket 1.
好像懂一点了，1024就是socket0，逗号后面的就是socket1 

我现在都是50，也能跑起来，但server还是没统计，client 和server怎么用不同的大页呢

NUMA具体有几个是不是跟CPU类型有关？除非换设备不然没法干预
root@server:~# numastat
                           node0
numa_hit                 5114898
numa_miss                      0
numa_foreign                   0
interleave_hit             37960
local_node               5114898
other_node                     0
root@server:~# numactl --hardware
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 15904 MB
node 0 free: 227 MB
node distances:
node   0
  0:  10
root@server:~#

**Comment by pengjianzhang** [comment]
> https://doc.dpdk.org/guides-22.11/linux_gsg/nic_perf_intel_platform.html? 这个文档中提到这么句话 Usually 0x:00.x is on socket 0 and 8x:00.x is on socket 1. Note: To get the best performance, ensure that the core and NICs are in the same socket
> 
> 请问dperf是不是也可以不限制双网卡必须用不同的NUMA，
答：没有限制

> 只是暂时不支持？
答：没测试过，可能是支持的

**Comment by digger-yu** [comment]
> > https://doc.dpdk.org/guides-22.11/linux_gsg/nic_perf_intel_platform.html? 这个文档中提到这么句话 Usually 0x:00.x is on socket 0 and 8x:00.x is on socket 1. Note: To get the best performance, ensure that the core and NICs are in the same socket
> > 请问dperf是不是也可以不限制双网卡必须用不同的NUMA，
> > 答：没有限制
> 
> > 只是暂时不支持？
> > 答：没测试过，可能是支持的

在请教一下，结果中的bitsRx 单位是大B还是小b （bits字位和Byte字节），另外client和server上结果差异较大的时候应该以哪个为准

**Comment by pengjianzhang** [comment]
bits
应该是出问题，都不准，检查是否有丢包等错误

**Comment by digger-yu** [comment]
> bits 
一个机器俩网卡的问题还没搞定，暂时先切成两台机器跑了一下
代码里面这个地方的* 8 是生效的么，*8之后还是bit么不成Byte了
net_stats_format_print(((uint64_t)stats->byte_rx) * 8, bits_rx, STATS_BUF_LEN);
net_stats_format_print(((uint64_t)stats->byte_tx) * 8, bits_tx, STATS_BUF_LEN);

**Comment by pengjianzhang** [comment]
dperf支持一个numa上跑两个dperf
例如4G大页
client上配置
socket_mem      2048

server上配置
socket_mem      2048

**Comment by digger-yu** [comment]
> dperf支持一个numa上跑两个dperf 例如4G大页 client上配置 socket_mem 2048
> 
> server上配置 socket_mem 2048

我这里server上统计全是0的原因可能找到了，是中间dut设备学不到server端的arp
dut学到的server的mac是00:00:00:00:00:00
