### ISSUE TITLE
请问dper用做udp server，出现coredump

### ISSUE THREAD

**Issue by sheva7777** [baidu/dperf#243]
client:
mode        client
cpu         0-15
duration    600s
cps         50k
cc          500k
rss         l3l4
flood
protocol    udp
packet_size 64
keepalive   100ms
port        0000:aa:00.0    10.10.10.10   10.10.10.1
client      10.10.10.10     1
server      10.10.10.11      1
listen      8881              10
lport_range 1000 65535
kni

server:
mode            server
protocol        udp

keepalive       100ms
payload_size    64

cpu             0-15
rss             l3l4

duration    100m
port        0000:aa:00.0    10.10.10.11   10.10.10.1
client      10.10.10.10       1
server      10.10.10.11      1
listen          8881              10
kni

**Comment by sheva7777** [comment]
不通过lb可以正常

**Comment by pengjianzhang** [comment]
支持VXLAN

请定位一下在哪里core dump了，谢谢
如果能修复最好
