### ISSUE TITLE
发包能否支持更多的源地址

### ISSUE THREAD

**Issue by xiaozhaohan** [baidu/dperf#245]
当前dperf仅支持变动最后的ip段，导致一个port只能模拟250多个源地址，对于网络设备源地址数量显然是不太够
后期是否能支持255*255或者255*255*255的地址变动，
十分感谢！

**Comment by pengjianzhang** [comment]
请详细说一下背景，需求，谢谢

**Comment by xiaozhaohan** [comment]
dperf做客户端验证一个三层的网络组件的转发性能，网络组件做源地址一致性hash到后端服务器，该设备维护hash快表，源地址的数量增加会导致hash增加，可能会暴露性能问题；因此dperf做客户端时模拟的地址数量过少，不好验证该组件的性能

**Comment by pengjianzhang** [comment]
pktgen能做到吗
