### ISSUE TITLE
测试结果有个疑问，请教一下

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#246]
之前测试环境有点问题，现在调好了，跑了一下，但结果存疑，特来请教一下
参考链接
https://www.zhihu.com/people/artnowben/posts?page=3
https://metonymical.hatenablog.com/entry/2022/02/11/234927

![image](https://user-images.githubusercontent.com/55081697/220233524-b952b053-8c2e-478c-bf2f-a3ae41d3d693.png)
这个图里面的换算，显然是按照字节(Byte)来换算的
93476446880+8228164976=101704611856	           
101704611856byte/1024/1024/1024=94.71980096 GB 

![image](https://user-images.githubusercontent.com/55081697/220234052-132f6624-c223-4edf-851e-f99050fafce4.png)
8,951,794,528	+ 8,733,381,312=	17685175840 单位如果是bit的话，约等于	2108.237247M 
17685175840/8 byte /1024 kb/1024 =  2108 mb 
我的环境都是千兆口，假设测试数据准确，感觉单位是bit 更合理一些

这个问题之前就问过一次，你说的是bits 
Bits and Bytes
One byte = collection of 8 bits
想在确认一下，**这里rx+tx的结果单位是比特还是字节？**

比特(Bit)、字节(Byte)、千字节(KB)、兆字节(MB)、千兆字节(GB)

第二个问题
![image](https://user-images.githubusercontent.com/55081697/220236207-9936eeab-ee15-4b7c-ba5c-04b94e32935b.png)
上图中，百G的口，cps才测了5M
这里的M 单位是指millon吗，500万？

我这个千兆设备的测试结果这里有将近450万？
![image](https://user-images.githubusercontent.com/55081697/220236417-9f23056a-0393-4253-9e84-77383ccae904.png)

如果他的cps测试是准确的，那我这个cps能有5万就不错了，如果我这个cps测试准确，那他这个cps测试结果对于一个百G网卡的设备来说是不是也太低了点

**Comment by pengjianzhang** [comment]
1. bits
2.  每秒是速度，最后是total

**Comment by digger-yu** [comment]
> 1. bits。 bitsRX, bitsTx
> 2. 每秒输出是速度，最后输出的是total

那我这个cps数据是准确的么

**Comment by pengjianzhang** [comment]
准的

**Comment by digger-yu** [comment]
> 准的

请问对于千兆口的设备来说，这个cps算高的么，感觉数据有点夸张 
结果单位如果是比特，那链接里面的结果是不是就不可信了？文章链接还贴在项目主页里的Related Articles里

**Comment by pengjianzhang** [comment]
没有看出问题
