### ISSUE TITLE
unknown config keyword("client_hop")

### ISSUE THREAD

**Issue by ybingbing95** [baidu/dperf#258]
[root@zw-1-1 ~]# cat client.conf 
mode                        client
tx_burst                    128
launch_num                  4
protocol                    udp
cpu                         1 2 3 4
rss                         auto    mq_rx_none
payload_size                128
duration                    180s
cps                         40m
cc                          3000
flood
keepalive                   1ms
port        0000:00:03.0     192.168.1.12  192.168.1.2 fa:16:3e:5a:62:bb
client                      192.168.1.12        100
client_hop
server                      192.168.1.1       4
listen                      80              4

[root@zw-1-1 ~]# /usr/sbin/dperf -c client.conf  &
[1] 6721
[root@zw-1-1 ~]# line 17: unknown config keyword("client_hop")

[1]+  Exit 1                  /usr/sbin/dperf -c client.conf

**Comment by pengjianzhang** [comment]
是最新的版本吗

**Comment by ybingbing95** [comment]
[root@zw-1-1 ~]# /usr/sbin/dperf -v
1.4.0
用的是这个版本

**Comment by pengjianzhang** [comment]
这是主干的特性，你重新编译一下
