### ISSUE TITLE
请教个问题,关于 udp pps的测试

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#259]
[这个链接里关于pps部分的介绍比较少](https://zhuanlan.zhihu.com/p/451341132)
```
PPS（packets perf second）是网络设备的一个重要指标，测试PPS只需要在并发连接数的基础上做少量调整，与带宽测试类似。

降低报文长度，payload_size设置为1
设置合适的并发连接数
提升请求发送速度，如从60秒发送1次，提升为1毫秒发送一次
降低cps，由于并发度连接数较低，应该把新建速度同时调低
```
```
配置文件
mode        client
socket_mem  1024
cpu         0
duration    30s
cps         75
payload_size 1
keepalive    1ms
protocol     udp
cc           1500
port        0000:05:00.1    192.168.10.20 192.168.10.101
client      192.168.10.20     2
server      192.168.10.101     1
listen      80              32
-------------------------------------------------------------
mode        server
socket_mem  1024
cpu         1
duration    60s
payload_size 64
keepalive    1s
protocol        udp
port        0000:05:00.0    192.168.10.101 192.168.10.20
client      192.168.10.20       2
server      192.168.10.101      1
listen      80              32

```

我在千兆网卡上双向测试了一组数据
| payload_size | cps   | cc   | dperf:pktRx | dperf:pktTx | udpRx      | udpTx      | dperf:bitsRx   | dperf:bitsTx   | bitsRX+bitsTX | Mbps        | MBps         |
|--------------|-------|------|-------------|-------------|------------|------------|----------------|----------------|---------------|-------------|--------------|
| 1            | 50    | 100  | 2,203,774   | 2,203,766   | 2,203,722  | 2,203,752  | 1,868,793,664  | 758,095,680    | 2626889344    | 2626.889344 | 328.361168   |
| 1            | 50    | 1000 | 4,488,293   | 4,488,255   | 4,488,248  | 4,488,248  | 3,806,068,608  | 1,543,960,240  | 5350028848    | 5350.028848 | 668.753606   |
| 1            | 50    | 1500 | 3,589,904   | 3,589,863   | 3,589,852  | 3,589,852  | 3,044,231,904  | 1,234,913,072  | 4279144976    | 4279.144976 | 534.893122   |
| 1            | 50    | 3000 | 3,691,521   | 3,691,487   | 3,691,476  | 3,691,476  | 3,130,405,552  | 1,269,871,728  | 4400277280    | 4400.27728  | 550.03466    |
| 1            | 100   | 100  | 2,233,478   | 2,233,443   | 2,233,432  | 2,233,432  | 1,893,983,808  | 768,304,592    | 2662288400    | 2662.2884   | 332.78605    |
| 1            | 100   | 1000 | 10,793,353  | 10,793,316  | 10,793,308 | 10,793,308 | 5,180,822,032  | 9,152,728,736  | 14333550768   | 14333.55077 | 1791.693846  |
| 1            | 100   | 1500 | 11,692,188  | 11,692,119  | 11,692,135 | 11,692,105 | 5,612,262,032  | 9,914,911,472  | 15527173504   | 15527.1735  | 1940.896688  |
| 1            | 100   | 3000 | 10,376,611  | 10,376,569  | 10,376,562 | 10,376,558 | 4,980,785,728  | 8,799,326,176  | 13780111904   | 13780.1119  | 1722.513988  |
| 1            | 10000 | 1000 | 24,959,753  | 24,959,716  | 24,959,705 | 24,959,705 | 11,980,693,888 | 21,165,834,832 | 33146528720   | 33146.52872 | 4143.31609   |
| 1            | 1000  | 1000 | 22,480,050  | 22,479,743  | 22,479,732 | 22,479,732 | 10,790,436,448 | 19,062,817,728 | 29853254176   | 29853.25418 | 3731.656772  |
| 1            | 500   | 1000 | 16,883,535  | 16,883,467  | 16,883,483 | 16,883,453 | 8,104,109,904  | 14,317,174,576 | 22421284480   | 22421.28448 | 2802.66056   |
| 1            | 250   | 1000 | 15,653,776  | 15,653,735  | 15,653,724 | 15,653,724 | 7,513,825,184  | 13,274,362,944 | 20788188128   | 20788.18813 | 2598.523516  |
| 1            | 200   | 1000 | 14,192,685  | 14,192,621  | 14,192,640 | 14,192,610 | 6,812,500,192  | 12,035,338,272 | 18847838464   | 18847.83846 | 2355.979808  |
| 1            | 200   | 1500 | 17,205,395  | 17,205,361  | 17,205,350 | 17,205,350 | 8,258,601,392  | 14,590,141,792 | 22848743184   | 22848.74318 | 2856.092898  |
| 1            | 150   | 1500 | 14,920,984  | 14,920,917  | 14,920,936 | 14,920,906 | 7,162,084,368  | 12,652,933,280 | 19815017648   | 19815.01765 | 2476.877206  |
| 1            | 75    | 1500 | 6,904,919   | 6,904,879   | 6,904,868  | 6,904,868  | 3,314,374,624  | 5,855,333,056  | 9169707680    | 9169.70768  | 1146.21346   |
| 64           | 75    | 1500 | 7,693,364   | 7,693,296   | 7,693,312  | 7,693,282  | 6,523,966,240  | 6,523,909,568  | 13047875808   | 13047.87581 | 1630.984476  |
| 64           | 120   | 1500 | 9,672,354   | 9,672,309   | 9,672,302  | 9,672,298  | 8,202,155,472  | 8,202,113,696  | 16404269168   | 16404.26917 | 2050.533646  |
| 64           | 150   | 1500 | 12,700,221  | 12,700,153  | 12,700,172 | 12,700,142 | 10,769,783,136 | 10,769,725,408 | 21539508544   | 21539.50854 | 2692.438568  |
| 64           | 130   | 1500 | 10,289,277  | 10,289,227  | 10,289,228 | 10,289,216 | 8,725,307,536  | 8,725,260,160  | 17450567696   | 17450.5677  | 2181.320962  |
| 64           | 125   | 1500 | 10,363,174  | 10,363,140  | 10,363,130 | 10,363,129 | 8,787,967,328  | 8,787,938,384  | 17575905712   | 17575.90571 | 2196.988214  |
| 64           | 110   | 1500 | 10,091,573  | 10,091,537  | 10,091,526 | 10,091,526 | 8,557,648,656  | 8,557,619,040  | 17115267696   | 17115.2677  | 2139.408462  |

有几个疑问,想请教一下
通常意义上,1Gbps=1000Mbps 也就是我用的千兆口速率
1. 按Mbps来换算的话,Tx+Rx结果全部超过了端口速率
    测试结果中有没有什么参数可以表示测试结果不可信?
2. 该怎么样调整参数,才可以最快的测出当前设备最高的pps
   cc和cps的参数设置上是否有推荐的经验值,比如cc是cps的几倍这种
3. PPS (Packet Per Second)  这个值是不是只看udpRx(The number of UDP messages received per second.)和udpTx 就行了, 
    是不是可以认为PPS和RPS(received per second )是 1=1的关系? 
4. [知乎的链接](https://zhuanlan.zhihu.com/p/451341132) 推荐的payload_size是1
   [github](https://github.com/baidu/dperf/blob/main/docs/configuration-CN.md)推荐的是 双向PPS测试：设置较小packet_size（如64）
   这个payload_size的值在pps中设置多少比较合适

**Comment by pengjianzhang** [comment]
看一下 是否出现发送失败的计数，如dropTx 等

**Comment by digger-yu** [comment]
> 否出现发送失败的计数，如dropTx

查看了所有的历史日志,dropTx一直都是0

**Comment by jesson1** [comment]
dropTx一直是0是不是可以说明压测还没达到瓶颈？比如我在测试cps、cc的时候，我会逐步调高cc、cps，但如何判断当前cc、cps已经达到瓶颈，看有没有发生丢包吗？

**Comment by pengjianzhang** [comment]
是的，你要看服务器上的数据做个对比，看看链路上，网卡上是否有丢包

**Comment by digger-yu** [comment]
> dropTx一直是0是不是可以说明压测还没达到瓶颈？比如我在测试cps、cc的时候，我会逐步调高cc、cps，但如何判断当前cc、cps已经达到瓶颈，看有没有发生丢包吗？

虽然dropTx一直都是0 ,但bitsRx+bitsTx的总和已经超过了我的端口理论速率, 如果测出来数据已经不准了,在调大cc和cps就没意义了

**Comment by digger-yu** [comment]
> 是的，你要看服务器上的数据做个对比，看看链路上，网卡上是否有丢包
 更新了一下表格中bitsRx+bitsTx换算后的结果,发现没一个是符合预期的 是我换算错了么

**Comment by pengjianzhang** [comment]
你先用仪器测一下网卡吧

**Comment by digger-yu** [comment]
> 你先用仪器测一下网卡吧
spirent 测试仪测出来的结果是没问题的,我千兆网卡测千兆速率是能跑满的
![image](https://user-images.githubusercontent.com/55081697/222097572-edff3d5c-62c5-4d04-9433-aee7f03d8511.png)

但是用dperf不知道什么原因的情况下会有虚高的情况
比如[issue 257](https://github.com/baidu/dperf/issues/257)
100Gbps的网卡,跑出来15000Gbps的带宽

**Comment by pengjianzhang** [comment]
你用如下配置测一下， 贴一下dperf 截图
packe_size 1400
protocol udp

#逐步增大
cc  100  
keepalive 1ms

**Comment by pengjianzhang** [comment]
看中间的截图，不是最后的

**Comment by digger-yu** [comment]
> duration 设置为10m 截图第 120秒的 看中间的截图，不是最后的

![image](https://user-images.githubusercontent.com/55081697/222102574-df341ee7-a910-435b-80a1-f4c4a0a87b77.png)
z中间有很多全0的打印 
左 client侧打印 右server侧打印

**Comment by pengjianzhang** [comment]
duration 设置为10m
截图第 120秒的

**Comment by pengjianzhang** [comment]
finish显示的是累加值，不是速度

**Comment by digger-yu** [comment]
> duration 设置为10m 截图第 120秒的

![image](https://user-images.githubusercontent.com/55081697/222104215-2ef1a92e-6fdf-4ac6-bcd9-9a1dfc8cb917.png) 

finish的值需要除运行时间么,

**Comment by pengjianzhang** [comment]
1. 出现了很多UdpRt
2. 不需要除时间
请多查阅dperf文档，非常抱歉

**Comment by digger-yu** [comment]
> 1. UdpRt
出现udpRt 就是说有很多重传呗,然后呢?  文档中没啥更详细的描述

用excel拉了一下统计数据,bitsRx+bitsTx确实还就只是每秒打印数的求和, 感觉没啥意义, 这个求和数据被我误以为是发送和接受带宽的和 ,给了我很多误导
![image](https://user-images.githubusercontent.com/55081697/222110997-48cfdaeb-0d50-452b-a035-e36cf1d11f24.png)
