### ISSUE TITLE
单向PPS测试

### ISSUE THREAD

**Issue by ybingbing95** [baidu/dperf#260]
server端配置：
mode server
tx_burst 4
protocol udp
cpu 0-7
rss auto mq_rx_none
server 192.168.1.1 1
payload_size 64
duration 300s
keepalive 10us
port 0000:00:03.0 192.168.1.1 192.168.1.11 fa:16:3e:8a:10:34
client 192.168.1.11 100
listen 80 4
client_hop

基于OVS的PPS测试环境，虚机上使用dperf，想要测试单向PPS的最大性能，配置如下。dperf运行时候发现，server端的pktRx依然有统计值，说明server也在发包？有什么方法不让server发包吗，server也发包的话，会影响到实际测试的结果（只需要单向测试）

client端配置：
mode client
tx_burst 4
protocol udp
cpu 0-7 
server 192.168.1.1 1
payload_size 64
duration 120s
cps 40m
cc 3000
keepalive 10us
port 0000:00:03.0 192.168.1.11 192.168.1.1 fa:16:3e:d3:8d:83
client 192.168.1.11 100
client_hop
listen 80 4
flood

**Comment by pengjianzhang** [comment]
server listen 不一样的端口

**Comment by ybingbing95** [comment]
可以了。多谢。已经在推荐了
