### ISSUE TITLE
CPU没跑满，但出现丢包

### ISSUE THREAD

**Issue by jesson1** [baidu/dperf#261]
您好，请教一个问题。
我在测试cps，单核的测试结果和readme给出的结果差的太大了，是CPU性能不够的原因吗？

cpu性能基准测试：
```
sysbench cpu --cpu-max-prime=20000 --threads=1 run
```
结果：
```
CPU speed:
    events per second:   297.37

General statistics:
    total time:                          10.0021s
    total number of events:              2976

Latency (ms):
         min:                                    2.57
         avg:                                    3.36
         max:                                   55.72
         95th percentile:                        4.91
         sum:                                 9996.03

Threads fairness:
    events (avg/stddev):           2976.0000/0.00
    execution time (avg/stddev):   9.9960/0.00
```

客户端配置
```
mode        client
tx_burst        128
launch_num      10
cpu         0
rss  auto mq_rx_none
payload_size    1
duration    2m
cps         30k
port        0000:00:05.0    192.168.2.100   192.168.2.6 52:54:00:8b:79:ec
client      192.168.2.100   100
server      192.168.2.6     1
listen      80              5
```

服务端配置
```
mode        server
tx_burst    128
cpu         0-6
rss  auto mq_rx_none
duration    100m
payload_size    1
port        0000:00:05.0    192.168.2.6   192.168.2.100 52:54:00:88:02:0d
client      192.168.2.100   100
server      192.168.2.6     1
listen      80              5
```

我的CPU没跑满，但已经出现了丢包和socket error 的情况：

![image](https://user-images.githubusercontent.com/26702832/222089188-3188e5b8-07fd-4eb7-8178-dbbbaa633f91.png)

我没有办法去抓包了解发生了什么状况，难道是因为我的网络环境有问题吗

**Comment by pengjianzhang** [comment]
dropTx，出现了丢包

**Comment by jesson1** [comment]
我不太理解，为啥cpu没满，还会出现丢包

**Comment by pengjianzhang** [comment]
研究一下你的网络环境性能

**Comment by jesson1** [comment]
dperf貌似没啥问题，感觉是虚拟网络承受不了这么大压力导致的丢包

**Comment by jesson1** [comment]
并不，感觉还是有问题😯

单核的情况下跑5万cps时会出现丢包（cpu没跑满）：
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/26702832/222192683-262e012c-e518-4bbd-860f-c89f3950e790.png">

设置4核继续跑5万cps，这时没有丢包了：
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/26702832/222192099-338cba60-dea8-45ae-8837-421599e83985.png">

讲道理，如果是我的虚拟网络性能不够，4核5万cps也会丢包才对🤦🏻‍♀️

**Comment by pengjianzhang** [comment]
一个核对应一个队列；应该是队列少 容易出现丢包。
请拉最新的代码，新代码中对错误显示颜色，帮忙测一下，谢谢

**Comment by jesson1** [comment]
好的，我等会来测一下。
上面的问题，我觉得是cpu统计的不对；按照dperf的输出，cpu没满，说明队列是来得及消费的，不应该出现丢包，除非cpu实际已经跑满。
