### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#265]
dperf设计了一个参数,quiet 关闭每秒输出统计数据。
如果用户也配置了,那输出就仅有Test Finished部分
但Test Finished 的数据是统计的历史测试数据的和, 但感觉这里的"和"并没有什么实际的意义,反而给了我很多困扰

建议把Test Finished 换成Test Report ,输出测试后的关键数据
这样是不是就不用查看历史日志来确定throughput cc cps等的值了 ,对于新手来说会不会更便于理解和使用

相对来说dperf的文档相对比较零散,对结果步骤没有很详尽的解释
 [cisco 的TRex](https://trex-tgn.cisco.com/trex/doc/) 的文档可以用海量形容,对每个参数配置都有解释

**Comment by pengjianzhang** [comment]
谢谢，欢迎社区贡献者来一起帮助dperf更好
