### ISSUE TITLE
写了个文档,记录了一下安装配置过程,供新手参考

### ISSUE THREAD

**Issue by digger-yu** [baidu/dperf#267]
https://github.com/digger-yu/blog/blob/main/how%20to%20install%20dperf%20on%20ubuntu.md

由于如下原因仍旧存在,就不pull request了
1.这篇文章中有多处内容与项目中的内容是重复的
2. 有部分内容来源于外部文档（如DPDK文档），可能有copyright与license的冲突
3. 个人化的行文风格
4.文档没有英文版本
5. 部分章节有待完善（如13节）

**Comment by pengjianzhang** [comment]
谢谢 已经放在 Related Articles
