### ISSUE TITLE
请问有没有办法提升单条流的带宽呢?

### ISSUE THREAD

**Issue by markchen7788** [baidu/dperf#269]
大大您好，准备用dperf测试机器的带宽，但是我并不需要非常多的并发连接，有没有可能就靠50条左右的并发连接打满线速（100Gbps）呢？？？我在机器上试了一下大概3w条并发连接才差不多到100Gbps。

**Comment by markchen7788** [comment]
我用iperf打10条左右就差不多到线速100Gbps了

**Comment by pengjianzhang** [comment]
应该可以，请参考文章 https://zhuanlan.zhihu.com/p/609817366
如果喜欢dperf，请加个star，也向周围的小伙伴宣传一下，谢谢

**Comment by jesson1** [comment]
我也在测带宽，dperf的包最大才1500个字节，包太小了，带宽测不满

**Comment by digger-yu** [comment]
@jesson1 

试试这个参数
jumbo
开启巨帧。开启巨帧后，pakcet_size可以设置到9724。 注：packet_size不能超过网络环境的MTU

**Comment by pengjianzhang** [comment]
参考这篇文章，单条流8Gbps
https://dev.to/pengjianzhang/using-dperf-to-test-the-network-performance-of-alibaba-cloud-ecs-4ikj
