### ISSUE TITLE
dperf client tcp socket 有time_wait状态吗

### ISSUE THREAD

**Issue by panzhengyu** [baidu/dperf#274]
我看了一下tcp socket 状态转换相关代码，没找到time_wait的状态转换，压测时，time_wait状态需要考虑吗

**Comment by digger-yu** [comment]
dperf曾经使用了通用的时间轮定时器，一个时间轮定时器消耗32字节，一个socket使用了两个定时器，消耗了64个字节，这对支持几十亿并发连接数的测试仪来说内存消耗有点高，另外频繁的函数回调开销也不可接受。 我去掉了时间轮定时器，借鉴了FreeBSD的timewait定时器，把所有相同的任务放在一个按时间排序的链表中。

参考[design-CN](https://github.com/baidu/dperf/blob/main/docs/design-CN.md)

**Comment by panzhengyu** [comment]
@digger-yu 当测试四层负载均衡器的CPS性能时，4层负载均衡器是有timewait状态的，当4层负载均衡器某个连接处于timewait时，dperf client再次发起的相同的5元组tcp连接时，4层负载均衡清就不新建连接了，是不是有问题？

**Comment by pengjianzhang** [comment]
没有time wait，你要配置较多的地址，使得dperf再一次轮到这个地址时， L4LB上已经超时即可

**Comment by panzhengyu** [comment]
好的，不考虑timewait，大大减少处理逻辑，能提供更好的性能。使用更多的源IP来规避这个，也是很好的解决办法。

**Comment by pengjianzhang** [comment]
总结得很到位！！！
