### ISSUE TITLE
使用多核设备报错，Number of rx queues not power of

### ISSUE THREAD

**Issue by tkheyan09** [baidu/dperf#281]
配置信息，使用的虚拟机环境
[root@localhost build]# cat  client-cps.conf          
mode            client
tx_burst        128
launch_num      10
cpu             0 1 2
payload_size    1
duration        10m
cps             2m
rss    l3

#port           pci             addr      gateway        [mac]
port            0000:03:00.0    6.6.245.3 6.6.245.1  b4:a9:fc:ab:7a:85

#               addr_start      num
client          6.6.245.3       100

#               addr_start      num
server          6.6.247.3       3
#               port_start      num
listen          80              1
报错信息
[root@localhost build]# vi  client-cps.conf        
[root@localhost build]# ./dperf -c client-cps.conf 
EAL: Detected 8 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:03:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
vmxnet3_dev_configure(): ERROR: Number of rx queues not power of 2
Port0 dev_configure = -22
dev configure fail
port init fail
dpdk init fail

**Comment by stone163mail** [comment]
ERROR: Number of rx queues not power of 2，配置需要2的倍数吧，可以试试4核

**Comment by pengjianzhang** [comment]
dperf 支持vmxnet3，请注意错误提示
如果喜欢dperf 请加个stat 谢谢

**Comment by tkheyan09** [comment]
加了
