### ISSUE TITLE
设备同时运行client和server一段时间后虚拟机死机

### ISSUE THREAD

**Issue by tkheyan09** [baidu/dperf#284]
[root@localhost build]# cat client-cps.conf 
mode            client
tx_burst        128
launch_num      10
cpu             0 1
payload_size    1
duration        10m
cps             2m
rss    l3
socket_mem      512,0
#port           pci             addr      gateway        [mac]
port            0000:03:00.0    6.6.245.3 6.6.245.1  b4:a9:fc:ab:7a:85

#               addr_start      num
client          6.6.245.3       100

#               addr_start      num
server          6.6.247.3       2
#               port_start      num
listen          80              1

[root@localhost build]# cat server-cps.conf       
mode            server
tx_burst        128
cpu             3 4
socket_mem      512
duration        10m
payload_size    1
rss    l3
socket_mem      2048
#numa2
port            0000:0b:00.0    6.6.247.3    6.6.247.1  b4:a9:fc:ab:7a:85

#               addr_start      num
client          6.6.245.3       100

#               addr_start      num
server          6.6.247.3       2

#               port_start      num
listen          80              1
[root@localhost build]# 
![439a4160d3b75b595a1e81b89d72a77](https://user-images.githubusercontent.com/8122654/226656883-81944824-db13-4e30-b618-02a05fccc320.png)

**Comment by tkheyan09** [comment]
8核
[root@localhost ~]# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
stepping        : 1
microcode       : 0xb000038
cpu MHz         : 2099.998
cache size      : 20480 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid rdseed adx smap xsaveopt arat md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
bogomips        : 4199.99
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual
power management:
内存20G
[root@localhost ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:             19          19           0           0           0           0
Swap:             3           0           3
[root@localhost ~]#
num信息
[root@localhost ~]# numastat
                           node0
numa_hit                41371494
numa_miss                      0
numa_foreign                   0
interleave_hit             33041
local_node              41371494
other_node                     0
[root@localhost ~]#
网卡信息

Network devices using DPDK-compatible driver
============================================
0000:03:00.0 'VMXNET3 Ethernet Controller 07b0' drv=igb_uio unused=vmxnet3
0000:0b:00.0 'VMXNET3 Ethernet Controller 07b0' drv=igb_uio unused=vmxnet3

Network devices using kernel driver
===================================
0000:02:00.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens32 drv=e1000 unused=igb_uio *Active*

**Comment by tkheyan09** [comment]
单独运行client一段时间后也挂死
[root@localhost build]# cat client-cps.conf
mode            client
tx_burst        128
launch_num      10
cpu             0 1 2 3
payload_size    1
duration        5h
cps             2k
rss    l3
socket_mem      512,0
#port           pci             addr      gateway        [mac]
port            0000:03:00.0    6.6.245.3 6.6.245.1  b4:a9:fc:ab:7a:85

#               addr_start      num
client          6.6.245.3       100

#               addr_start      num
server          6.6.247.3       4
#               port_start      num
listen          80              1

**Comment by pengjianzhang** [comment]
用一个cpu测一下，

**Comment by pengjianzhang** [comment]
是不是大页分配重叠了?
