### ISSUE TITLE
单个的client最大连接数问题？

### ISSUE THREAD

**Issue by jr981008** [baidu/dperf#286]
有个疑问
作为客户端。deperf 是如何实现单个节点支持1亿+的tcp连接，tcp4元祖限制了本地65535端口，对于单个ip
如果server和client 都只有1台的情况下 是需要n个ip实现  n\*65535最大连接吗？
配置限制最大支持ip是255，dperf 单个client 最多支持255\*65535个tcp连接吗？

**Comment by pengjianzhang** [comment]
服务器上可以监听很多个端口

**Comment by jr981008** [comment]
我的场景是要压测长连接服务器性能 ，千万tcp连接单台
对于这一台server ，使用一个dperf client节点理论上我最多压测 到连接数 255*65535吗？

**Comment by pengjianzhang** [comment]
已上的公式是用dperf client压测 dperf server
如果压测单个IP:Port 的确只能是254 * 65535
