### ISSUE TITLE
关于并发模型设计请教

### ISSUE THREAD

**Issue by Rioyisme** [baidu/dperf#287]
dperf 是否可以通过epoll 实现，而不用多线程？现在的网关、L4负载均衡设备、防火墙等也基本上使用epoll 来处理并发会话？

**Comment by pengjianzhang** [comment]
主流七层网关是用linux 内核的tcp协议栈，选用socket + epoll是常见的做法，如nginx，envoy，haproxy
主流的4层网关、防火墙是基于报文处理的，并没有使用epoll，如dpvs，lvs等
dperf是基于DPDK+用户态协议栈，完全bypass了linux kernel，没有使用epoll，性能有数量级的提升，详见设计文档
欢迎交流，探讨，如果喜欢dperf，请加个star，谢谢

**Comment by Rioyisme** [comment]
> 主流七层网关是用linux 内核的tcp协议栈，选用socket + epoll是常见的做法，如nginx，envoy，haproxy 主流的4层网关、防火墙是基于报文处理的，并没有使用epoll，如dpvs，lvs等 dperf是基于DPDK+用户态协议栈，完全bypass了linux kernel，没有使用epoll，性能有数量级的提升，详见设计文档 DPDK与epoll+socket是两个差别比较大的技术栈/方案 欢迎交流，探讨，如果喜欢dperf，请加个star，谢谢

目前主流四层防火墙/网关主要是以多线程来处理会话数据包的吗？

**Comment by pengjianzhang** [comment]
是的
