### ISSUE TITLE
dperf服务端启动之后未监听80端口

### ISSUE THREAD

**Issue by xurongyukevin** [baidu/dperf#293]
1.vmware exsi搭建的centos7.9环境，虚拟网卡；
2.防火墙都已经关掉。

dperf启动后，未监听80端口
下面这是我的server的配置，启动后我用10.75.2.185的客户端访问curl -i 10.75.2.132无法访问，可以ping同无法访问
mode        server
cpu         0
duration    10m
socket_mem  512
port        0000:02:01.0    10.75.2.132  10.75.2.185
client      10.76.2.185       1
server      10.75.2.132       1
listen      80                1
![image](https://user-images.githubusercontent.com/130275514/230760121-09ba51dd-7d33-4f64-a732-8efea7c8179e.png)
![image](https://user-images.githubusercontent.com/130275514/230760162-7da8d6ec-e5ef-40db-8585-b4d75e750427.png)
![image](https://user-images.githubusercontent.com/130275514/230760224-ea84d1fd-d6e0-4091-8b7c-1d0ee3dbd1ec.png)

**Comment by pengjianzhang** [comment]
protocol http
增加配置看看

**Comment by xurongyukevin** [comment]
试了没啥效果
![image](https://user-images.githubusercontent.com/130275514/230760679-38648fd8-1629-4c30-a8d9-4b98f46662fb.png)

**Comment by xurongyukevin** [comment]
![Uploading image.png…]()

**Comment by pengjianzhang** [comment]
dperf bypass kernel了 用这个命令看不到dperf的监听端口
在客户端用curl访问一下
如果喜欢dperf 请加个star 谢谢

**Comment by xurongyukevin** [comment]
还是不行
![image](https://user-images.githubusercontent.com/130275514/230760927-cde77069-c165-46b5-8d94-6704292f5eb2.png)

**Comment by pengjianzhang** [comment]
是不是 二层不通

**Comment by xurongyukevin** [comment]
从客户端能ping通服务端，但是无法访问，客户端未装dperf只是在服务端配置了客户端的ip

**Comment by pengjianzhang** [comment]
把client dperf放在同一个网段

**Comment by xurongyukevin** [comment]
![image](https://user-images.githubusercontent.com/130275514/230761132-649920aa-fda1-4d3e-977d-c7e54f4f1949.png)

**Comment by xurongyukevin** [comment]
他们就是同一个网段的
服务端10.75.2.132 客户端10.75.2.185

**Comment by xurongyukevin** [comment]
能推断出是啥问题吗，大佬

**Comment by pengjianzhang** [comment]
配置写错了

**Comment by xurongyukevin** [comment]
能具体说下吗，搞了好几天了

**Comment by xurongyukevin** [comment]
能帮忙看下吗

点击链接直接加入会议：
https://meeting.tencent.com/dm/aH1tvGCYanyt

#腾讯会议：769-738-590

复制该信息，打开手机腾讯会议即可参与

**Comment by pengjianzhang** [comment]
client 10.76.2.185 1   
改成
client 10.75.2.185 1

**Comment by xurongyu-cloud** [comment]
改了之后curl还是访问不通，我只想用这个做服务端。然后用其他压测软件，测试。有时间帮看下，然后我帮你宣传宣传，我们主要用这个代替测试仪。啥时候有时间腾讯会议或者todesk帮我看下，我用这个是刚需

**Comment by pengjianzhang** [comment]
给我邮箱发个腾讯会议 pengjianzhang@gmail.com

**Comment by xurongyu-cloud** [comment]
可以用todesk吗，我这边没法语音用腾讯会议，然后微信语音和你说我的微信18230066448

**Comment by pengjianzhang** [comment]
问题是否已解决？

**Comment by xurongyu-cloud** [comment]
还没解决，最近太忙了，准备周末看下



---原始邮件---
发件人: "Jianzhang ***@***.***&gt;
发送时间: 2023年4月20日(周四) 上午10:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baidu/dperf] dperf服务端启动之后未监听80端口 (Issue #293)




 
问题是否已解决？
