### ISSUE TITLE
请问dperf在client端显示存在udpdrop  这里的丢包指的是client端由于某种原因在发包过程中产生的丢包，还是client端在收到server端的回复包的时候由于某一种原因产生的丢包

### ISSUE THREAD

**Issue by 13691126988** [baidu/dperf#295]

**Comment by pengjianzhang** [comment]
client收到一个UDP报文，但是报文没有匹配到连接，就会丢包。
如果喜欢dperf，请给项目加个star，谢谢

**Comment by 13691126988** [comment]
![image](https://user-images.githubusercontent.com/99714089/230874886-af0ca339-fb8c-4c7c-8f6f-3c52d3662fbd.png)
如图所示，其中client端udptx的数据包小于udprx的数据包，这样有哪些原因呢？还注意到udptx+udpdrop=udprx

**Comment by 13691126988** [comment]
> client收到一个UDP报文，但是报文没有匹配到连接，就会丢包。 如果喜欢dperf，请给项目加个star，谢谢

![image](https://user-images.githubusercontent.com/99714089/230874886-af0ca339-fb8c-4c7c-8f6f-3c52d3662fbd.png)
如图所示，其中client端udptx的数据包小于udprx的数据包，这样有哪些原因呢？还注意到udptx+udpdrop=udprx

**Comment by pengjianzhang** [comment]
配置发一下

**Comment by 13691126988** [comment]
> 配置发一下

![image](https://user-images.githubusercontent.com/99714089/231029877-8bb0fd9d-3e0d-4a0d-b1e4-04711635237a.png)
![image](https://user-images.githubusercontent.com/99714089/231029930-71627b9b-d3aa-45b0-85f7-6940b64eb969.png)
这是client端和server端的配置，由于我的测试需要，我client端发送的包大小和server端发送的包大小不一样

**Comment by pengjianzhang** [comment]
你用dperf client直接打 dperf server看看是否丢包，然后把pps降低看看是否丢包。
可能是中间的DUT丢包了。
给项目加个star吧，谢谢~

**Comment by 13691126988** [comment]
> 你用dperf client直接打 dperf server看看是否丢包，然后把pps降低看看是否丢包。 可能是中间的DUT丢包了。 给项目加个star吧，

好的，确实是中间的DUT设备的dhcp数据包导致的，不是dperf的问题，感谢大大

**Comment by pengjianzhang** [comment]
请在周围小伙伴中推荐一下dperf，另外请给项目加个star，谢谢~
