### ISSUE TITLE
支持海光、Intel、AMD平台吗，对比博通25G、100G网卡，Mellanox 25G网卡、Intel 25G、100G网卡能否支持？

### ISSUE THREAD

**Issue by zhaobijie** [baidu/dperf#298]
如题：
请问目前版本能支持海光、Intel、AMD平台吗？
对比博通25G、100G网卡，Mellanox 25G网卡、Intel 25G、100G网卡能否支持？

**Comment by pengjianzhang** [comment]
支持
如果喜欢dperf，请加个star，谢谢
