### ISSUE TITLE
在dperf client中配置pipeline的方式测试带宽，在两台服务器server1和server2之间接入被测设备后，带宽会降低

### ISSUE THREAD

**Issue by 13691126988** [baidu/dperf#301]
请问dperf上配置pipeline方式测试的原理是什么，会自动随着中间网络线路的能力而自动适配好带宽吗？

**Comment by pengjianzhang** [comment]
不会，pipeline表示一次发送多个请求，不等待响应

**Comment by 13691126988** [comment]
如果我是用一下配置在两台服务器直连的情况下达到了线速
![image](https://user-images.githubusercontent.com/99714089/234754608-ef0dc18a-d29f-4454-85ad-27613d45dc43.png)

但是在接入中间被测设备后，网络流量降低，也没有发生丢包，为什么呢？这不能表示是因为pipeline自动适配中间网络的线路能力而自动适配好带宽吗？

**Comment by pengjianzhang** [comment]
中间设备的原因吧

**Comment by 13691126988** [comment]
> pipeline表示一次发送多个请求，不等待响应

我查阅网络资料以及dperf代码后发现，pipeline指的是将多个socket中发的udp请求包按顺序组合起来一起发送，发送过程中不需要等待dperf client端对每个udp包的响应，与HTTP Pipelining技术相同是吗？

**Comment by 13691126988** [comment]
> 是的，是类似的

请问dperf client端在使用pipeline这个参数发送udp数据包的时候，会启用网络拥塞控制吗？

**Comment by pengjianzhang** [comment]
不会，udp协议不涉及拥塞控制

**Comment by 13691126988** [comment]
> 不会，udp协议不涉及拥塞控制

那么pipeline与cc（连接数）之间会相互配合来发送udp包，这个数值是只由dperf client端的conf参数配置来决定的，还是同时受到网络线路环境的影响呢？

**Comment by pengjianzhang** [comment]
不受网络线路影响

**Comment by 13691126988** [comment]
> 不受网络线路影响

请问pipeline 100在1秒内的发包数有一个值吗？

**Comment by pengjianzhang** [comment]
请参考一下配置文档，与pipeliine keepalive 相关

**Comment by 13691126988** [comment]
> 请参考一下配置文档，与pipeliine keepalive 相关

请问配置pipeline参数的时候，keepalive=1ms这样子配置可以吗？
