### ISSUE TITLE
请问10g网卡打不满的原因，并且用了4个cpu，只有单个cpuyou usage

### ISSUE THREAD

**Issue by wangxexplorer** [baidu/dperf#309]
seconds 54                 cpuUsage 100 8   8   8
pktRx   4,849,310          pktTx    4,849,970          bitsRx   2,327,748,320      bitsTx  2,095,229,920      dropTx  0
tcpRx   4,849,310          tcpTx    680                udpRx    0                  udpTx   0
arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0
tosRx   0                  otherRx  0                  badRx    0
synRx   0                  synTx    670                finRx    10                 finTx   10                 rstRx   0          rstTx 4,849,290
synRt   670                finRt    0                  ackRt    0                  pushRt  0
tcpDrop 0                  udpDrop  0
skOpen  0                  skClose  340                skCon    1,920              skErr   330
httpGet 0                  http2XX  10                 httpErr  0
ierrors 0                  oerrors  0                  imissed  50,631

client配置：
mode                        client
tx_burst                    10
launch_num                  10
cpu                         1-4
payload_size                1000
duration                    1m
cps                         2000
cc                          3000
keepalive                   1us

#port                       pci             addr         gateway            mac
port                        0000:07:00.1    10.84.10.20   10.84.10.10   3c:fd:fe:be:16:71

#                           addr_start      num
client                      10.84.10.20         100

#                           addr_start      num
server                      10.84.10.10       4
#                           port_start      num
listen                      80              5

**Comment by pengjianzhang** [comment]
请参考 dperf FAQ 带宽测试部分
https://zhuanlan.zhihu.com/p/561093951

**Comment by wangxexplorer** [comment]
> 请参考 dperf FAQ 带宽测试部分 https://zhuanlan.zhihu.com/p/561093951

改成protocol为udp 就上去了，但是还想问一下  server的 tx 返回给client的还是只有2G+，这个是什么因素导致的呢

**Comment by pengjianzhang** [comment]
参考一下 配置说明文档 检查一下配置吧 主要是调一下参数
