### ISSUE TITLE
请问dperf client使用pipeline配合keepalive=0ms的方式发udp包与keepalive=1ms和cc配合的方式发udp包，为何在加入中间被测网络设备后，后者可以实现恒定的发包，而前者的发包数目下降？

### ISSUE THREAD

**Issue by 13691126988** [baidu/dperf#311]

**Comment by pengjianzhang** [comment]
中间设备的问题吧
你用dper client直接打dperf server 排除一下

**Comment by 13691126988** [comment]
> 中间设备的问题吧 你用dper client直接打dperf server 排除一下

用keepalive=1ms的方式发包就没有这样的问题，所以想咨询一下是不是pipeline方式有什么特殊的机制，比如说我设置pipeline=100  、cc=100、client数目=100，可以得到一个理论上每一秒的发包数目吗？

**Comment by pengjianzhang** [comment]
pipeline会成倍增大pps，大概率是中间设备的问题，你先把pipeline从1开始，逐步上升

**Comment by 13691126988** [comment]
> pipeline会成倍增大pps，大概率是中间设备的问题，你先把pipeline从1开始，逐步上升

请问pipeline=100的时候，发包是按顺序依次发100个包，还是同时从100个socket发包，并行发100个包呢？这个涉及到了我们中间设备的处理方式

**Comment by pengjianzhang** [comment]
pipeline是指单个socket的发包

**Comment by pengjianzhang** [comment]
是的
首次发送的时候发送100个请求，如果不出现丢包，这样这个连接里会始终保持着100个请求，理论上带宽会上升100倍

**Comment by 13691126988** [comment]
> 是的 pineline是连接内的调节，首次发送的时候发送100个请求，如果不出现丢包，这样这个连接里会始终保持着100个请求，理论上带宽会上升100倍；这个概念与http pipeline是一样的 cc是连接数量的调节

”pineline是连接内的调节，首次发送的时候发送100个请求，如果不出现丢包，这样这个连接里会始终保持着100个请求“，那如果出现100个请求发生丢包，该连接会怎么样呢？                                         ————谢谢大大，目前周围人都开始用dperf了

**Comment by pengjianzhang** [comment]
pipeline只能用于UDP，如果request丢包，那么带宽会降下来一些，连接不受影响
问一下周围的小伙伴，有没有加star啊~~

**Comment by 13691126988** [comment]
> pipeline只能用于UDP，如果request丢包，那么带宽会降下来一些，连接不受影响；启用pipeline之后 dperf不检测丢包 问一下周围的小伙伴，有没有加star啊~~

也就是说，看似设置了pipeline=100，一次发送了100个请求，但是由于request丢包，所以可能一次只是成功发送了50个请求并响应。就是通过这种方式调节了带宽。
这样子理解对吗？

**Comment by pengjianzhang** [comment]
是的

**Comment by 13691126988** [comment]
> pipeline只能用于UDP，如果request丢包，那么带宽会降下来一些，连接不受影响；启用pipeline之后 dperf不检测丢包 问一下周围的小伙伴，有没有加star啊~~

”启用pipeline之后 dperf不检测丢包“，这种情况下，dperf client端查看丢包，是通过udpTx和udpRx的差值来体现的吗？如果udpTx=udpRx，则在dperf的上下行中没有发生丢包？

**Comment by 13691126988** [comment]
> 是的

理解了，谢谢大大

**Comment by pengjianzhang** [comment]
是否丢包可以通过测试结束后的total总数来看

**Comment by 13691126988** [comment]
> 是否丢包可以通过测试结束后的total总数来看

![image](https://github.com/baidu/dperf/assets/99714089/31c3c817-bfcb-4fce-8da6-3284a04ad98f)
类似这种就是不丢包


![image](https://github.com/baidu/dperf/assets/99714089/36c7d568-a393-4e14-a7e6-6f031a4c52ff)
这种就是丢包吗？
