### ISSUE TITLE
麦洛斯ConnectX-4 Lx网卡使用dperf初始化失败

### ISSUE THREAD

**Issue by opheliaKyouko** [baidu/dperf#313]
执行./dperf -c ../test/bond/bond.conf提示：
![image](https://github.com/baidu/dperf/assets/24988715/8feabd36-9bdd-42e1-bf6e-4e114f29c051)

目前环境：
1. 已经加载mlx5内核模块
![image](https://github.com/baidu/dperf/assets/24988715/98df8681-68d2-4750-a967-f9a71a75fcea)

2. 配置文件已经按文档修改
![image](https://github.com/baidu/dperf/assets/24988715/db5f999c-a65e-4e54-a539-cb389a2ec7c2)

3. 尚有大页可用
![image](https://github.com/baidu/dperf/assets/24988715/c49d2d11-90ea-417f-b7fb-aa1f0c141610)

**Comment by opheliaKyouko** [comment]
补充dpdk-devbind -s
![image](https://github.com/baidu/dperf/assets/24988715/28606c97-5bb5-4344-8097-5bb07c04d1c4)

**Comment by pengjianzhang** [comment]
mlx网卡与其他网卡不太一样，请参考我的知乎文章，有一篇讲mlx网卡的
建议先不要用bond，先把单个网卡用起来
如果喜欢dperf，请给项目加个star，谢谢

**Comment by opheliaKyouko** [comment]
自问自答一下：
1. mlx驱动编译时要加上dpdk

**Comment by opheliaKyouko** [comment]
自问自答一下：

**Comment by opheliaKyouko** [comment]
自问自答一下：

1. mlx内核模块编译时候记得带上dpdk
`./mlnxofedinstall –dpdk –force –skip-unsupported-devices-check`

2. dpdk编译的时候需要配置mlx网卡支持
修改config/common_base  CONFIG_RTE_LIBRTE_MLX5_PMD=y

3. 重新编译dperf，可以扫描到mlx网卡

**Comment by pengjianzhang** [comment]
欢迎把你的经验写一篇文章，投稿到dperf
