### ISSUE TITLE
如何合理描述dperf输出

### ISSUE THREAD

**Issue by opheliaKyouko** [baidu/dperf#314]
问题背景：
    使用自研用户态协议栈(基于dpdk)做rpc打流测试时出现大量超时重传，乱序重传问题。但是改用内核态进行rpc通信则问题消失(通过tcpdump查看)。遂采用dperf来诊断网络环境。

执行dperf输出如下：
客户端：
![925132c8acbf48f8da5d3070a6051d0](https://github.com/baidu/dperf/assets/24988715/7435e7c9-66a5-4b44-8f26-fc159c4983cd)
服务端：
![27911e40fc7e84bdae45bf391ae0036](https://github.com/baidu/dperf/assets/24988715/e9c7ba84-e491-4033-90cd-a36e16443e99)

根据docs/statistics.md可知：
1. 客户端出现rstRx：RST（复位）报文的作用是中断或重置一个TCP连接。当一个TCP连接处于异常状态或需要立即终止时，TCP端点可以发送RST报文来强制关闭连接。

**Comment by opheliaKyouko** [comment]
2. 客户端出synRt：现每秒重传TCP SYN报文的个数，重传意味着丢包。
3. 客户端出skErr：现每秒出错的并发连接数
4. 服务端出现rstTx：服务端发送的rst报文数
5. 服务端出现imissed：由于接收buffer不够，导致网卡硬件丢包的累计数。

现在问题是：1. 如何理解imissed含义，是如何统计的。2. 这是否可以解释为何内核态无重传但dpdk用户态出现重传和乱序

**Comment by pengjianzhang** [comment]
不适合测RPC哦

**Comment by pengjianzhang** [comment]
是不是配置有问题，服务器返回rst 通常是端口不对，通常是协议不对，IP不对，端口不对等
imissed是硬件统计数据，由于接收buffer不够，导致网卡硬件丢包的累计数
