### ISSUE TITLE
普通网卡如何与dpdk驱动的网卡进行通信呢？

### ISSUE THREAD

**Issue by CP3164094** [baidu/dperf#315]
您好，我现在有一个需求，需要验证普通可以接收到dpdk发送的数据包。我应该怎样使用dpdk驱动的网卡发送数据包至普通网卡呢，感谢！

**Comment by pengjianzhang** [comment]
要实现ARP、IP、TCP/UDP协议，请参考一下dperf的代码，如：
1. dperf可以响应来自普通网卡的ping
2. dperf可以向nginx(运行在普通网卡上)发送http请求

如果喜欢dperf，请给项目加个star，谢谢

**Comment by CP3164094** [comment]
> 

我最初是想验证dpdk的收发数据包的顺序问题，请问dper可以做到么？

**Comment by CP3164094** [comment]
> 要实现ARP、IP、TCP/UDP协议，请参考一下dperf的代码，如：
> 
> 1. dperf可以响应来自普通网卡的ping
> 2. dperf可以向nginx(运行在普通网卡上)发送http请求
> 
> 如果喜欢dperf，请给项目加个star，谢谢

我最初是想验证dpdk的收发数据包的顺序问题，请问dper可以做到么？

**Comment by pengjianzhang** [comment]
没有理解你的问题 ^_^

**Comment by CP3164094** [comment]
是这样的，我最初的需求是需要验证dpdk驱动下的网卡收发数据包的顺序能不能够保证，所以我自己写了个程序，但是接收不到数据包，于是领导就i调整方向，让我验证一下dpdk驱动的网卡发送数据包，普通网卡能不能接收到！

**Comment by pengjianzhang** [comment]
可以试一下 dperf udp协议 做试验，dperf client发送报文给普通网卡，开启flood

**Comment by CP3164094** [comment]
> dperf ud

好的，感谢您，我试一下去
