### ISSUE TITLE
dpdk22.11.1编译问题

### ISSUE THREAD

**Issue by CP3164094** [baidu/dperf#316]
您好，我本地dpdk的路径，以及dperf的路径如下所示
![image](https://github.com/baidu/dperf/assets/16473101/1fa9aa27-bd92-41ff-a01a-4dd293b209e7)
当我输入make后，会报如下错误
![image](https://github.com/baidu/dperf/assets/16473101/b955d040-65c6-484e-a6c8-bdf7200f84d4)
我该如何解决呢

**Comment by pengjianzhang** [comment]
请参考一下我的知乎文章，看看是不是编译步骤不对

**Comment by Ericlighting** [comment]
在~/.bashrc中添加下图的环境变量试试（路径可能不一样）
![image](https://github.com/baidu/dperf/assets/40377014/dae020cf-f6de-4d2a-80ba-138d64255e3a)
还不行的话把dpdk库所在位置也加上
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu

**Comment by CP3164094** [comment]
> 在~/.bashrc中添加下图的环境变量试试（路径可能不一样） ![image](https://user-images.githubusercontent.com/40377014/239180970-dae020cf-f6de-4d2a-80ba-138d64255e3a.png) 还不行的话把dpdk库所在位置也加上 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu

您好，我是先执行了ubuntu install script,还需要再执行make么？
我输入dperf run XXXX.py后，告诉我找不到dperf，我想这是不是要make？但是make后就又报和上边一样的错！所以我还是需要在bashrc中进行您提供的那个语句添加？

**Comment by Ericlighting** [comment]
ubuntu install 

> > 在~/.bashrc中添加下图的环境变量试试（路径可能不一样） ![image](https://user-images.githubusercontent.com/40377014/239180970-dae020cf-f6de-4d2a-80ba-138d64255e3a.png) 还不行的话把dpdk库所在位置也加上 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu
> 
> 您好，我是先执行了ubuntu install script,还需要再执行make么？ 我输入dperf run XXXX.py后，告诉我找不到dperf，我想这是不是要make？但是make后就又报和上边一样的错！所以我还是需要在bashrc中进行您提供的那个语句添加？

“ubuntu install script / dperf run XXXX.py”是你自己定义的“ubuntu dperf“的可执行程序吗?
我是按照先编译dpdk再编译dperf的顺序弄得，完全没有任何问题

**Comment by CP3164094** [comment]
我也是这么个顺序，先编译dpdk，再编译dperf，不过我dpdk是22.11.1，使用meson+ninja编译的！我现在就有这个问题
![image](https://github.com/baidu/dperf/assets/16473101/73c0ce4e-cc3a-422f-8d19-1bab919654f2)

**Comment by zcj88** [comment]
请问您有解决吗？我也遇到了同样的问题

**Comment by pengjianzhang** [comment]
请参考文章，注意DPDK的编译参数
https://dperf.org/doc/html/compile-dpdk-22.11
https://dperf.org/doc/html/compile-dperf-on-dpdk-23
