### ISSUE TITLE
请问dperf的payload能够超过MTU吗？

### ISSUE THREAD

**Issue by markchen7788** [baidu/dperf#317]
貌似只有大的请求才会使得LVS利用网卡的tso和gro使得吞吐提高，小的http请求不能合包，下面是apache ab 获取50M文件的LVS抓包和dperf获取1514包大小请求的LVS抓包。请问大大有办法或者有计划做这个功能吗？
ab:
![图片](https://github.com/baidu/dperf/assets/50443757/6e68a363-ab3c-4134-99c9-64afcd911faf)
dperf:
![图片](https://github.com/baidu/dperf/assets/50443757/a0761fd0-daa1-451c-9086-dfc9e9e6932f)

**Comment by pengjianzhang** [comment]
dperf主要关注性能测试。
可以详细说一下为什么需要这个功能？

**Comment by markchen7788** [comment]
> dperf主要关注性能测试。 可以详细说一下为什么需要这个功能？ LVS是报文级别的转发，并不需要tso, gro。
主要是我用dperf进行带宽测试LVS的大包吞吐只有25Gbps左右，但是iperf却有70Gbps左右，dperf的conf文件应该是没有错，我用其它负载均衡设备测试能够有100G的吞吐。检查了一下才发现dperf没有合包而ab和iperf都能够合包，所以最后我都不知道该怎么取LVS的最大带宽值了。不过看起来LVS确实应该更关心的是pps而不是bps。

**Comment by pengjianzhang** [comment]
带宽是所有性能指标里面最容易打上去的，需要调整一下配置。

protocol udp
keepalive 1ms
cc 1000 
packet_size 1400

逐步增大cc
