### ISSUE TITLE
虚拟机收不到包

### ISSUE THREAD

**Issue by Mengyuan-L** [baidu/dperf#318]
准备测一下kvm虚拟机中的dpdk性能，但是虚拟机始终收不到包，配置如下：
使用的是DPDK 23， 
服务器端将一个82599分成几个VF, 将某个VF通过-device vfio-pci,host=0000:xx:xx.0的方式在qemu中传递给虚拟机。
虚拟机中绑定uio_pci_generic的driver, 也能正常启动dperf的server。
客户端是另一台物理机，直接用其自己的另一个82599网卡发送数据。
两台物理网卡用网线直连。
在配置文件中，互相以对方的ip地址和mac作为gateway。
这样的配置下服务器端接收不到包，请问一下有没有什么看法，感激不尽。

另外：
如果在服务器端在非虚拟器环境中，同样使用VF来作为dpdk的服务器端端口，客户端保持不变，配置文件不变，这样的设置服务器端能够正常接受到包。

**Comment by pengjianzhang** [comment]
请先诊断一下连通性。服务器不启动dperf时，它们是否2层互通。
如果喜欢dperf，请给项目加个star，谢谢~

**Comment by Mengyuan-L** [comment]
我还刚接触dpdk没多久，不确定这能不能测试连通性，我在服务器端VF还在使用kernel driver的时候，将其和客户端的网卡设置在同一网关内。这个时候我通过客户端ping服务器中的VF的ip可以显示ping通。
之后当我unbind VF，再用dperf启动服务器端，同时客户端用dperf client发包，log几乎和下图一样，偶尔有一些变动，绝大多数都是0 （客户端设置的是100cps）。

> seconds 114                 cpuUsage 0   
> pktRx   0                  pktTx    0                  bitsRx   0                  bitsTx  0                  dropTx  0                 
> tcpRx   0                  tcpTx    0                  udpRx    0                  udpTx   0                 
> arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
> tosRx   0                  otherRx  0                  badRx    0                 
> synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 0         
> synRt   0                  finRt    0                  ackRt    0                  pushRt  0                 
> tcpDrop 0                  udpDrop  0                 
> skOpen  0                  skClose  0                  skCon    0                  skErr   0                 
> httpGet 0                  http2XX  0                  httpErr  0                 
> ierrors 0                  oerrors  0                  imissed  0                 
> 
> 
> seconds 115                 cpuUsage 0   
> pktRx   2                  pktTx    0                  bitsRx   3,432              bitsTx  0                  dropTx  0                 
> tcpRx   0                  tcpTx    0                  udpRx    1                  udpTx   0                 
> arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
> tosRx   0                  otherRx  1                  badRx    0                 
> synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 0         
> synRt   0                  finRt    0                  ackRt    0                  pushRt  0                 
> tcpDrop 0                  udpDrop  1                 
> skOpen  0                  skClose  0                  skCon    0                  skErr   0                 
> httpGet 0                  http2XX  0                  httpErr  0                 
> ierrors 0                  oerrors  0                  imissed  0

**Comment by pengjianzhang** [comment]
用kernel 的客户端去ping dperf服务器 看看通不通

**Comment by Mengyuan-L** [comment]
谢谢您快速的答复！客户端用kernel的driver去ping或者curl  dperf服务器，都可以ping 通或者获得“hello dperf!”

**Comment by pengjianzhang** [comment]
应该是方面的问题
请向周围的小伙伴介绍一下dperf哦，谢谢~~

**Comment by Mengyuan-L** [comment]
所以您觉得是客户端物理机和客户端机器上的网卡的问题吗？

**Comment by Mengyuan-L** [comment]
我检查了一下客户端机器可能是主板太老，不支持VF，启动dpdk需要在grub里面加上”pci=assign-busses“。现在是直接用的网卡的PF，不知道这个有没有关系。再请问一下一般这种情况应该怎么样配置或者有什么替代方法吗。感激不尽

**Comment by pengjianzhang** [comment]
按道理PF是没问题的，你这种情况我没遇到过，可以尝试一下：
1. 用igb_uio驱动
2. 换dpdk版本，用早期的版本，如19.11

**Comment by Mengyuan-L** [comment]
您好，我更换了一台客户端物理机又来重复上述实验。在过程中成功过一次（dperf客户端和服务器正常接收包），但是无法复现。而且有一些奇怪的现象，不知道您有没有什么想法。
我首先还是检查客户端和虚拟机（服务器端）的连通性。
（1）在服务器端和客户端都用kernel driver的时候，我通过以下命令设置服务器端的ip：

> sudo ip link set enp0s4 down &&
> sudo ip address add 10.10.22.99/24 brd 10.10.22.110 dev enp0s4 &&
> sudo ip link set enp0s4 up

(99是服务器ip，110是客户端ip)
发现无法正常设置服务器端的ip（用ifconfig看不到ip），但是有的时候重复多次之后用ifconfig检查能看到ip。
客户端可以正常设置ip。
在服务器端运气好设置成功ip的情况下，客户端可以ping通服务器端。

后来发现netplan可以成功设置ip，不知道这边的问题是什么。

(2) 在服务器端使用dperf启动server之后，能够在客户端使用内核driver通过ping/curl成功。但是客户端使用dperf基本上不成功，只成功了一次。我猜测是不是还是两方无法定位到对方，但是考虑到成功过一次，不知道这块还能怎么样继续检查看看

(3) 观测到服务器端使用dperf启动server之后，能够在客户端使用内核driver通过ping/curl成功，之后客户端使用dperf无法连接，然后在客户端取消dpdk再次启用内核driver，无法ping通。在服务器端dperf 不断的情况下，物理重启客户端，重启之后用内核driver再ping 服务器，还是ping不同。是不是可能还是两者之间无法定位的问题，不知道您有什么看法？感谢

**Comment by pengjianzhang** [comment]
建议找一位精通网络的小伙伴帮你看一下。
如下建议同参考：

1）IP应该这样配，broadcast配错了
ip address add 10.10.22.99/24 brd 10.10.22.255 

2） 客户端上启用dperf server验证一下，在服务器上curl 验证一下

3）解释不了，你可以arping测试一下能否学习到ARP

4）引入第三台机器，做客户端运行curl，在之前的两个机器上运行dperf sever是否有问题？

5） 检查一下配置是否把MAC地址写错，可能是学习不到MAC地址

**Comment by Mengyuan-L** [comment]
谢谢，我把两者连到交换机上，看起来彼此能互相通信。但是遇到了丢包问题，能不能麻烦再看看。这是我客户端的配置

> mode        client
> cpu         0
> duration    30s
> tx_burst 4
> cc  1
> cps  1
> packet_size 500
> keepalive 1us
> protocol udp
> port        0000:04:00.0    10.10.10.247   10.10.10.1
> client      10.10.10.247     1
> server      10.10.10.152      1
> listen      80              1

这是服务器端的配置:

> mode        server
> cpu         0
> duration    20m
> port        0000:00:05.0    10.10.10.152   10.10.10.1 
> client      10.10.10.247     1
> server      10.10.10.152      1
> listen      80               1
> 
> 然

后在运行过程中，数据大致如下
服务器端：

> seconds 280                cpuUsage 7   
> pktRx   238,550            pktTx    0                  bitsRx   954,200,000        bitsTx  0                  dropTx  0                 
> tcpRx   0                  tcpTx    0                  udpRx    238,550            udpTx   0                 
> arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
> tosRx   0                  otherRx  0                  badRx    0                 
> synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 0         
> synRt   0                  finRt    0                  ackRt    0                  pushRt  0                 
> tcpDrop 0                  udpDrop  238,550           
> skOpen  0                  skClose  0                  skCon    0                  skErr   0                 
> httpGet 0                  http2XX  0                  httpErr  0                 
> ierrors 0                  oerrors  0                  imissed  0     

客户端：

> seconds 16                 cpuUsage 14  
> pktRx   0                  pktTx    994,025            bitsRx   0                  bitsTx  3,976,100,000      dropTx  757,824           
> tcpRx   0                  tcpTx    0                  udpRx    0                  udpTx   994,025           
> arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
> tosRx   0                  otherRx  0                  badRx    0                 
> udpRt   994,025            udpDrop  0                  tcpDrop  0                 
> skOpen  0                  skClose  0                  skCon    1                  skErr   0                 
> ierrors 0                  oerrors  0                  imissed  0   

不知道这种丢包问题可能是什么原因呢？感谢

**Comment by pengjianzhang** [comment]
把压力降低试试
keepalive 1ms

**Comment by Mengyuan-L** [comment]
把客户端的keepalive 设置成1ms, 其他保持不变
客户端:
> seconds 17                 cpuUsage 0   
> pktRx   3                  pktTx    1,000              bitsRx   8,512              bitsTx  4,000,000          dropTx  0                 
> tcpRx   0                  tcpTx    0                  udpRx    2                  udpTx   1,000             
> arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
> tosRx   0                  otherRx  1                  badRx    0                 
> udpRt   1,000              udpDrop  2                  tcpDrop  0                 
> skOpen  0                  skClose  0                  skCon    1                  skErr   0                 
> ierrors 0                  oerrors  0                  imissed  0  

服务器端:
> seconds 38                 cpuUsage 0   
> pktRx   1,001              pktTx    0                  bitsRx   4,000,480          bitsTx  0                  dropTx  0                 
> tcpRx   0                  tcpTx    0                  udpRx    1,000              udpTx   0                 
> arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
> tosRx   0                  otherRx  1                  badRx    0                 
> synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 0         
> synRt   0                  finRt    0                  ackRt    0                  pushRt  0                 
> tcpDrop 0                  udpDrop  1,000             
> skOpen  0                  skClose  0                  skCon    0                  skErr   0                 
> httpGet 0                  http2XX  0                  httpErr  0                 
> ierrors 0                  oerrors  0                  imissed  0

**Comment by Mengyuan-L** [comment]
补充一下：我发现在dperf server起来的情况下，能ping通，但是curl提示

> curl: (7) Failed to connect to 10.10.10.152 port 80 after 0 ms: Connection refused

**Comment by pengjianzhang** [comment]
阅读一下配置文档
server.conf的'client'没有包含客户端IP，或者端口不对

**Comment by Mengyuan-L** [comment]
您好，这是客户端的配置
> mode client
> cpu 0
> duration 30s
> tx_burst 4
> cc 1
> cps 1
> packet_size 500
> keepalive 1ms
> protocol udp
> port 0000:04:00.0 10.10.10.247 10.10.10.1
> client 10.10.10.247 1
> server 10.10.10.152 1
> listen 80 1

这是服务器端的配置:

> mode server
> cpu 0
> duration 20m
> port 0000:00:05.0 10.10.10.152 10.10.10.1
> client 10.10.10.247 1
> server 10.10.10.152 1
> listen 80 1

然后收发的1s数据大概是这样
客户端:

> seconds 17 cpuUsage 0
> pktRx 3 pktTx 1,000 bitsRx 8,512 bitsTx 4,000,000 dropTx 0
> tcpRx 0 tcpTx 0 udpRx 2 udpTx 1,000
> arpRx 0 arpTx 0 icmpRx 0 icmpTx 0
> tosRx 0 otherRx 1 badRx 0
> udpRt 1,000 udpDrop 2 tcpDrop 0
> skOpen 0 skClose 0 skCon 1 skErr 0
> ierrors 0 oerrors 0 imissed 0

服务器端:

> seconds 38 cpuUsage 0
> pktRx 1,001 pktTx 0 bitsRx 4,000,480 bitsTx 0 dropTx 0
> tcpRx 0 tcpTx 0 udpRx 1,000 udpTx 0
> arpRx 0 arpTx 0 icmpRx 0 icmpTx 0
> tosRx 0 otherRx 1 badRx 0
> synRx 0 synTx 0 finRx 0 finTx 0 rstRx 0 rstTx 0
> synRt 0 finRt 0 ackRt 0 pushRt 0
> tcpDrop 0 udpDrop 1,000
> skOpen 0 skClose 0 skCon 0 skErr 0
> httpGet 0 http2XX 0 httpErr 0
> ierrors 0 oerrors 0 imissed 0

如果这种情况我的理解是服务器端能允许接收包，说明client的ip和port在范围之内，同时说明对于client而言，服务器的ip/mac 端口也都正确。不知道这种情况还有可能是什么样的问题。多次请教麻烦您了。

**Comment by pengjianzhang** [comment]
server.conf 加上protocol udp

**Comment by Mengyuan-L** [comment]
改成udp之后好了，感谢这么多次及时的回复，帮了非常大的忙！也是属于自己看文档不够仔细。会在交流会/报告/(如果有的话)上介绍dperf, 希望更多人能了解使用这个软件。

**Comment by pengjianzhang** [comment]
欢迎写一篇技术博客文章投到dperf

**Comment by CP3164094** [comment]
> 我在服务器端VF还在使用kernel driver的时候，将其和客户端的网卡设置在同一网关内。这个时候我通过客户端ping服务器中的VF的ip可以显示ping通。
> 之后当我unbind VF，再用dperf启动服务器端，同时客户端用dperf client发包，log几乎和下图一样，偶尔有一些变动，绝大多数都是0 （客户端设置的是100cps）。

您好，您这是怎么运行成功的，您能不能写个从头到尾的运行文档，感谢

**Comment by Mengyuan-L** [comment]
> > 我在服务器端VF还在使用kernel driver的时候，将其和客户端的网卡设置在同一网关内。这个时候我通过客户端ping服务器中的VF的ip可以显示ping通。
> > 之后当我unbind VF，再用dperf启动服务器端，同时客户端用dperf client发包，log几乎和下图一样，偶尔有一些变动，绝大多数都是0 （客户端设置的是100cps）。
> 
> 您好，您这是怎么运行成功的，您能不能写个从头到尾的运行文档，感谢

我感觉这边有一个困扰我很久的问题在于说，使用VF之后，VF有自己的mac地址，所以在路由器端设置成固定ip+mac就方便服务器端和路由器端找到对方。关于运行文档，我觉得我现在的配置还是有点问题，参考[#issue 319 ](https://github.com/baidu/dperf/issues/319), 等我对照FAQ搞清楚之后，我考虑写一下我遇到的问题和对应的解决方法（我也是网络小白，怕误人子弟）。
