### ISSUE TITLE
dperf启动失败，not enough ports available

### ISSUE THREAD

**Issue by colintsao** [baidu/dperf#321]
你好，想使用dperf测试新建连接数，但是启动失败了，已配置了大页、也绑定了网卡，还是无法启动：
```
[root@bsg build]# ./dperf  -c dperf_client.conf
EAL: Detected 24 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: No available hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
not enough ports available: avail 0 require 1
port init fail
dpdk init fail
```
配置信息如下：
```
[root@bsg build]# cat dperf_client.conf 
mode            client
tx_burst        128
launch_num      10
cpu             0

payload_size    1
duration        2m
cps             5k

#port           pci             addr          gateway       [mac]
port            0000:02:00.1    172.17.1.247  172.17.1.1    

#               addr_start      num
client          172.17.1.247    1

#               addr_start      num
server          172.17.1.115    1
#               port_start      num
listen          80              5
```
绑定信息如下：
```
[root@bsg build]# /opt/dpdk-19.11/usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:02:00.1 'NetXtreme BCM5720 Gigabit Ethernet PCIe 165f' drv=uio_pci_generic unused=tg3

Network devices using kernel driver
===================================
0000:02:00.0 'NetXtreme BCM5720 Gigabit Ethernet PCIe 165f' if=eth0 drv=tg3 unused=uio_pci_generic *Active*
```

**Comment by pengjianzhang** [comment]
请查一下DPDK官网 19.11版本是否支持 NetXtreme BCM5720

**Comment by colintsao** [comment]
查了下官网，好像的确不支持这个型号，那我虚拟化以后再试下

**Comment by pengjianzhang** [comment]
可以看下新版本的DPDK是否支持
如果喜欢dperf，请给项目加个star，谢谢~~

**Comment by gaochonghong** [comment]
在vmware虚拟机上安装了dpdk-19.11.14 + dperf-main，运行dperf客户端也报了not enough ports available: avail 0 require 1错误。
具体报错信息如下：
[root@localhost dperf-main]# ./build/dperf -c test/http/client-cps.conf 
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:0b:00.0 on NUMA socket -1
EAL:   probe driver: 15ad:7b0 net_vmxnet3
not enough ports available: avail 0 require 1
port init fail
dpdk init fail

网卡信息如下
[root@localhost http]# /root/dpdk-stable-19.11.14/usertools/dpdk-devbind.py -s

Network devices using kernel driver
===================================
0000:0b:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens192 drv=vmxnet3 unused=uio_pci_generic *Active*
0000:13:00.0 'VMXNET3 Ethernet Controller 07b0' if=ens224 drv=vmxnet3 unused=uio_pci_generic *Active*
查看dpdk说明，应该是支持VMXNET3 网卡的，请问会是什么原因呢

**Comment by pengjianzhang** [comment]
是不是没有绑定网卡啊

**Comment by pengjianzhang** [comment]
没有成功，提示了你这两个网卡仍然是"using kernel driver"


要先关掉网卡：ifconfig ens192 down
vmxnet3帮igb_uio试试

**Comment by sunny123g** [comment]
网卡down了之后，启动成功了，感谢！

**Comment by pengjianzhang** [comment]
如果喜欢dperf，请加个star哦~
