### ISSUE TITLE
How to configure IP in conf file?

### ISSUE THREAD

**Issue by tonychen007** [baidu/dperf#325]
I have two network cards.
A's ip is 10.0.0.2, not support dpdk.
B's intel, supporting dpdk, and I have already bound it.

I want to use this machine as a server, the only available network card with ip is 10.0.0.2. I can use it to access internet.

In the conf file,  I conf as such:
#port       pci            addr       gateway  mac
port        0000:06:00.0   10.0.0.2   10.0.0.1  xxxx
client      10.0.0.27      1
server    10.0.0.2       1
listen     80                  1

10.0.0.27 is my laptop, not installing dperf and dpdk.
AM I right? But I fail to curl 10.0.0.2 from 10.0.0.27. Iptables and firewall have been removed.

**Comment by pengjianzhang** [comment]
you could use A as a client to run curl, and use B as the dperf server (supposing IP is 10.0.0.27)
config:

mode server
port 0000:06:00.0 10.0.0.27 10.0.0.2
client 10.0.0.2 1
server 10.0.0.27 1

**Comment by ljluestc** [comment]
Check Network Connectivity: Ensure that both network cards are properly connected, and the cables are in working condition.

Verify DPDK Binding: Confirm that you have correctly bound the DPDK-compatible network card (B) to the DPDK driver. You can use the dpdk-devbind.py script to check the current driver binding status.

Verify DPDK Configuration: Make sure that you have correctly configured the DPDK environment variables and settings, including the number of memory channels, hugepages, and memory allocation for the DPDK application.

Check Network Settings: Double-check the network settings on both the server and the laptop to ensure they are in the same subnet (10.0.0.x) and that there are no IP conflicts.

Check Server Routing: Confirm that the server has proper routing configured to forward packets from the 10.0.0.2 network to the internet and back.

Debug Logs: Check the DPDK application logs or system logs (such as syslog) for any error messages or indications of network connectivity issues.
