### ISSUE TITLE
tcp流不完整

### ISSUE THREAD

**Issue by imuk1** [baidu/dperf#329]
我在阿里云单机上使用两个网卡，一个作为客户端一个作为服务端，通过阿里云的流量镜像功能把服务端的流量镜像到另一台设备上，然后抓包，发现三次握手和四次挥手都不完整，我的使用场景是要做流量解析，如果流不完整会当异常流量处理。

客户端配置
    mode        client
    cpu         1
    duration    5s
    socket_mem 2048
    cps         1k
    port        0000:00:09.0    172.18.241.127  172.18.255.253 00:16:3e:12:51:69
    client      172.18.241.127     10
    server      172.18.241.126      1
    listen      80              1

服务端配置
    mode        server
    tx_burst 128
    payload_size 1400
    cpu         0
    duration    10m
    socket_mem 2048
    port        0000:00:08.0    172.18.241.126   172.18.255.253 00:16:3e:1e:a6:fc
    client      172.18.241.127       100
    server      172.18.241.126      1
    listen      80              1

![图片](https://github.com/baidu/dperf/assets/136443473/7c5f4996-f905-4735-bf0e-651785179b7d)

**Comment by imuk1** [comment]
> 为什么要用dperf呢？dperf主要用来做L4性能测试 你可以试一下 client dperf，服务器nginx 在nginx上抓包看看

我们会把所有业务的流量镜像到另一个业务中做旁路分析，目的是测试旁路流量解析的性能，想通过这个工具生成一些背景流模拟高并发和新建的场景，测试我们在解析这些流量的时候会不会丢包，如果流不完整我们很容易发现并处理掉了，体现不出来正常流量的处理性能

**Comment by zrgtester** [comment]
我测试并发连接数的时候，并发连接数较大的时候也发现有些tcp连接不全的问题。

**Comment by kiddingl** [comment]
我们遇见了类似的问题，http流量没有响应数据@pengjianzhang

**Comment by pengjianzhang** [comment]
@kiddingl  请详细说明一下，包括怎么组网，哪些设备，dperf配置等

**Comment by kiddingl** [comment]
问题找到了，payload_size设置的太大，超过镜像网卡接受的mtu了，通过减小payload大小可以正常显示，也可以通过关闭jumbo来解决，关闭jumbo会带来性能暴跌

**Comment by pengjianzhang** [comment]
@kiddingl 
1. 能不能把你的场景写个文档，我把文章链接放到 dperf 主页上，可以供其他人参考；
2. 能否向周围小伙伴宣传一下 dperf，加个 star，谢谢
