### ISSUE TITLE
How to set gateway in conf?

### ISSUE THREAD

**Issue by SdotChen** [baidu/dperf#330]
如果使用可编程ASIC做为网关，conf文件里port一栏应该如何设置？

**Comment by SdotChen** [comment]
As I dont know how the gateway respond it, I need to set the logic in ASIC, thanks

**Comment by pengjianzhang** [comment]
通常网关是三层交换机/被测设备/dperf server，设置网关的IP，MAC地址可选

**Comment by SdotChen** [comment]
server/client是给网关发送ARP请求收到response才认为链路是正常的吗？我想让server一直运行

**Comment by pengjianzhang** [comment]
如果指定了MAC地址，dperf就不去探测，否则会用ARP探测，如果没有收到ARP响应就认为连通性不正常

**Comment by SdotChen** [comment]
这个指定的mac地址一定要真实存在吗

**Comment by pengjianzhang** [comment]
dperf只向这个MAC地址发送报文
