### ISSUE TITLE
keepalive参数咨询

### ISSUE THREAD

**Issue by zrgtester** [baidu/dperf#331]
我在测试tcp连接数的时候，server的keepalive配置为60s，client的keepalive也配置为60s，没有配置num，请问这样可以吗？

我看参数讲解中client端的keepalve解释如下：

**dperf client每隔'interval'时间发送一个请求；当'interval'为0时，client收到udp响应后会立刻发起新请求。
dperf client在发送完'num'个请求后关闭连接。**

我这样配置是60s发送一个请求的意思吗？server端会不会超时断开连接呢！

**Comment by pengjianzhang** [comment]
建议server端的keepalive 大于client

**Comment by zrgtester** [comment]
我在测试防火墙的并发性能的时候，在client运行时间到结束的时候有的连接通过挥手断开，这个时候总的连接数地于设置的cc，发现又有新建连接数产生，这种情况怎么避免呢？多谢，加星了。

**Comment by pengjianzhang** [comment]
1. 你可以手动停止client，ctl +c 
2. 可能是一个bug，我要确认下

**Comment by pengjianzhang** [comment]
已经修复了，请用主分支最新代码
