### ISSUE TITLE
cps/cc testing

### ISSUE THREAD

**Issue by SdotChen** [baidu/dperf#332]
想通过dperf测cps/cc的性能，但是conf文件不知道怎么调（已经参考了README的推荐文章）。由于使用100G网卡，我尝试增大cps，增大到10m还能承受，但是增大到20m时，cpu usage就都100了，增加cpu即server数量到12个也不起作用，请教一下如何配置，才能提升CPS？

目前conf文件如下
`mode        client
tx_burst    1024
launch_num  3
cpu         0-5 
duration    120s
cps         20m 
payload_size    1   
slow_start  10  
port        0000:05:00.0    6.6.241.31   6.6.241.1  
client      6.6.241.31     200 
server      6.6.241.1      6   
listen      80             1   
`

`mode        server
tx_burst    1024
cpu         0-5 
duration    1500s
payload_size    1   
port        0000:05:00.0    6.6.241.1   6.6.241.31
client      6.6.241.31      200 
server      6.6.241.1       6   
listen      80             1`

**Comment by SdotChen** [comment]
sorry for code above, here are pics
![image](https://github.com/baidu/dperf/assets/40907552/52ba5aca-4fc6-4c81-b520-b03d4505289c)
![image](https://github.com/baidu/dperf/assets/40907552/953bd87b-1770-40f5-81cc-c4caab23e5fb)

**Comment by pengjianzhang** [comment]
1. 增加Listen 端口数
2. 增加CPU数量，注意关闭超线程

**Comment by SdotChen** [comment]
![image](https://github.com/baidu/dperf/assets/40907552/5dc0b212-03b1-454d-91e7-add015e29df1)
![image](https://github.com/baidu/dperf/assets/40907552/15c4b2e4-878e-4b36-9c35-7016540301d4)
这是当前的效果，由于关闭了超线程，只有10核，而且大页最多分配了56G。
请问这个数值是否正常？

**Comment by SdotChen** [comment]
![image](https://github.com/baidu/dperf/assets/40907552/f02d30e0-b1c2-4a9b-b68b-16a7db8d6dc8)

这是当前的效果，由于关闭了超线程，只有10核，而且大页最多分配了56G。
请问这个数值是否正常？

**Comment by SdotChen** [comment]
好的。不过目前有一个场景需要测量rtt，我看net_stats.c中，服务端或者设置了keepalive就不打印rtt。
具体而言，我们DUT的环境可能会影响测试结果，而且需要兼顾吞吐量，得加keepalive这一栏。如果我把net_stats.c中修改一下，设置了keepalive也打印rtt，由于你是首包rtt，我不设置cc，而设置cps和keepalive那栏的num来新建连接和释放连接，以此观察rtt，请问这样测得的值合理吗？谢谢

**Comment by pengjianzhang** [comment]
如果没有cc，keepalive是不可以设置的

**Comment by SdotChen** [comment]
> 如果没有cc，keepalive是不可以设置的

那设置cc呢，我主要关注rtt

**Comment by pengjianzhang** [comment]
目前测试cps的时候可以输出rtt吧

**Comment by SdotChen** [comment]
是可以的，参考https://metonymical.hatenablog.com/entry/2022/02/11/234927里边的tput、cps、cc测试，也就只有cps会输出rtt，但是我需要兼顾吞吐量，如果把cps增大，server端的packet_size调大，rtt会很高都到30ms了，并且伴随很多的丢包和重传

**Comment by pengjianzhang** [comment]
我建议你用两个客户端，一个测吞吐，打背景流量，另一个测cps

**Comment by SdotChen** [comment]
好的，我去试试

**Comment by SdotChen** [comment]
> 如果没有cc，keepalive是不可以设置的

请问是为什么呢，cps是每秒新建连接数，cc是最大并发量

**Comment by pengjianzhang** [comment]
当前就是这样设计的
