### ISSUE TITLE
如何统计分发到每个IP的连接数？

### ISSUE THREAD

**Issue by zhakao99** [baidu/dperf#333]
你好，请问dperf可以查看分发到每个IP的连接数吗？

**Comment by pengjianzhang** [comment]
不能，如果喜欢dperf，请加个star哦，谢谢~

**Comment by zhakao99** [comment]
好的，谢谢

**Comment by zhakao99** [comment]
还有个问题想请教，dperf无法统计分发到每个IP的连接的话，那在使用dperf进行压测时如果还要验证负载均衡器高负载分发流量功能的正确性，是还需要借助其他工具？因为dperf的缘起是为了测试负载均衡器，我一开始以为是会带有各IP连接数统计功能来方便测试均衡算法的分发。

**Comment by pengjianzhang** [comment]
一般负载均衡上会有统计信息的

**Comment by pengjianzhang** [comment]
算法测试可以用其他工具，dperf主要测性能
