### ISSUE TITLE
请问从dperf测试结果来看，明显发包和收包不相等，但是dropTx和udpDrop都是等于0，作何解释？

### ISSUE THREAD

**Issue by 13691126988** [baidu/dperf#334]
![image](https://github.com/baidu/dperf/assets/99714089/d2e73e34-b5b6-46c7-8ba6-1c9097e20216)

以下是我的配置文件
![image](https://github.com/baidu/dperf/assets/99714089/785132c4-084c-4fad-800f-f1078207883b)

**Comment by pengjianzhang** [comment]
看起来是server->client这个链路上丢包了
