### ISSUE TITLE
初始化接口失败

### ISSUE THREAD

**Issue by tmacrzy** [baidu/dperf#337]
Esxi上安装的centos7.6,接口类型VMXNET3
DPDK：19.11.10
Dperf:1.5.0

执行时提示：
port init fail
dpdk init fail

**Comment by pengjianzhang** [comment]
vmxnet3是支持的，是不是没有按照指导操作，例如绑定网卡，配置1G大页，如果喜欢dperf，请加个star哦，谢谢

**Comment by tmacrzy** [comment]
能留个联系方式么？我早上发你百度邮箱提示账号不存在

**Comment by pengjianzhang** [comment]
github账号上可以看到我邮箱
pengjianzhang@gmail.com
