### ISSUE TITLE
server IP地址数目必须少于或等于CPU数目吗？能否多于cpu数目

### ISSUE THREAD

**Issue by tangning9495** [baidu/dperf#338]
目前有个业务性能测试需求，需要在server端模拟大量的vip，去进行http访问。但是机器逻辑核只有48核，请问这是只支持48个server IP地址吗？高于48，就会提示：Error: cpu num less than server ip num at 'client' mode （此处是不是应该是at 'server' mode?）

**Comment by tangning9495** [comment]
想知道如何配置才能使用高于硬件核数的server IP数目呢？

**Comment by pengjianzhang** [comment]
目前不支持

**Comment by pengjianzhang** [comment]
你只用dperf做服务器吗？

**Comment by pengjianzhang** [comment]
server ip数量的规模是多少？
