### ISSUE TITLE
RTT 数据

### ISSUE THREAD

**Issue by Mengyuan-L** [baidu/dperf#341]
您好我想看看延时之内的数据，我看统计里有RTT这个数据，但是我在实际跑的时候没有这个的输出，请问一下是不是只有TCP才能支持还是说需要特殊的configuration。还有就是请教一下RTT这边的first packet是什么意思 （The average rtt of the first packet, the unit is us.）感谢！

**Comment by pengjianzhang** [comment]
每个连接的收包rtt

**Comment by Mengyuan-L** [comment]
谢谢解答，但是我在udp/http的设置下没有看到rtt的输出，请问是在config文件需要设置吗

**Comment by Mengyuan-L** [comment]
谢谢！
