### ISSUE TITLE
dperf @ DPDK SUMMIT 2023

### ISSUE THREAD

**Issue by pengjianzhang** [baidu/dperf#346]
I will give a speak about dperf on DPDK Summit 2023 at September 13.

slides
https://static.sched.com/hosted_files/dpdksummit2023/f5/dpdk-summit-2023-pengjianzhang.pdf?_gl=1*t7zbkj*_ga*MjE0MzY5MDE2Ni4xNjg5OTg3MTk5*_ga_XH5XM35VHB*MTY5NDY5MTYyNi4zMS4xLjE2OTQ2OTIwODUuNjAuMC4w

Video
https://www.youtube.com/watch?v=J0Km2egpZvk&list=PLo97Rhbj4ceJf9p-crjGvGvn8pMWrJ_cV&index=25

**Comment by shunop** [comment]
我看地址是在爱尔兰演讲，请问支持国内平台直播吗

**Comment by pengjianzhang** [comment]
不清楚啊

**Comment by mannicui** [comment]
您好！我最近再测试vdpa 需要再一个host 上两个vm 之间测试，两个vf是在ovs 的桥上。网关怎么配置呢？请教一下

**Comment by pengjianzhang** [comment]
请新开一个issue讨论，谢谢

**Comment by mannicui** [comment]
您好！
我新开了一个issues , 请帮忙看一下，谢谢

发件人: Jianzhang Peng ***@***.***>
发送时间: 2023年8月28日 11:40
收件人: baidu/dperf ***@***.***>
抄送: Manni Cui ***@***.***>; Comment ***@***.***>
主题: Re: [baidu/dperf] dperf @ DPDK SUMMIT 2023 (Issue #346)


请新开一个issue讨论，谢谢
