### ISSUE TITLE
dperf运行失败，提示无可用大页，但实际已配置

### ISSUE THREAD

**Issue by zcj88** [baidu/dperf#350]
dperf运行失败，提示无可用大页，但实际在/boot/grub2/grub.cfg已配置
![Screenshot from 2023-08-04 13-19-05](https://github.com/baidu/dperf/assets/141379788/8a3fd920-a401-4ffc-8837-2473b248f419)

**Comment by pengjianzhang** [comment]
要配置1G大页，你的大页是2M

**Comment by zcj88** [comment]
1. cat /proc/cpuinfo | grep pdpe1gb  用这个命令查看了不支持1G大页，所以就按照图片中的2设置成了2M大页，最终按照3的方式重新设置成1G大页
![Uploading Screenshot from 2023-08-04 15-19-39.png…]()

2.现在不提示大页的问题了，又继续出现无端口可用的情况，但实际DPDK已经绑定了端口呢，再麻烦您帮忙回复下，谢谢~
![2](https://github.com/baidu/dperf/assets/141379788/69e1009b-719a-4662-b32e-b0f738613a61)

**Comment by zcj88** [comment]
![Screenshot from 2023-08-04 15-19-39](https://github.com/baidu/dperf/assets/141379788/b8cecb91-c7e9-40a3-a067-36b76c56b0d1)
图片上传错了，o(╯□╰)o

**Comment by pengjianzhang** [comment]
1. 大页数量多配置一点，比如 1024 个 4M大页
2. 是不是pci配置不对
请把配置贴一下

**Comment by zcj88** [comment]
配置如图：
![3](https://github.com/baidu/dperf/assets/141379788/e65d3c13-6e92-457b-99cd-aea996b9da3c)

**Comment by pengjianzhang** [comment]
是不是你的网卡不支持dpdk，查一下DPDK官网支持的网卡列表

**Comment by zcj88** [comment]
谢谢大神，应该是Realtek RTL8111不支持DPDK，还一直奇怪为什么同样配置的方式，另一台机器intel的网卡就配置成功了，这个怎么都不行，终于找到原因了o(╯□╰)o

**Comment by pengjianzhang** [comment]
喜欢dperf，请点个star哦， 谢谢
