### ISSUE TITLE
运行client-cc.conf提示error：insufficient sockets

### ISSUE THREAD

**Issue by zcj88** [baidu/dperf#352]
client端运行client-cc.conf提示图片中错误，请问怎么解决啊，谢谢~
![cc_c](https://github.com/baidu/dperf/assets/141379788/2805dfe7-e155-4b40-878e-2c15f25a73fa)

**Comment by zcj88** [comment]
server端配置如下，可以运行起来
![cc_s](https://github.com/baidu/dperf/assets/141379788/c74f7dc1-3f99-481e-a5a4-0e9f3e719d42)

**Comment by pengjianzhang** [comment]
测并发要有足够的客户端IP，增加client ip
参考 主页文章 FAQ

**Comment by zcj88** [comment]
我把num从1改为100，还是一样的问题呢

**Comment by pengjianzhang** [comment]
cc改为1k 试试

**Comment by zcj88** [comment]
是可以的，谢谢您，cc设置到100K都可以通，现在client端skCon是100K, server端也是100K，如果要测出最上限，是不是要一直试啊？

**Comment by pengjianzhang** [comment]
是的

**Comment by pengjianzhang** [comment]
能不能写一篇文章 总结一下怎么用dperf测试并发 谢谢

**Comment by zcj88** [comment]
好的，等我完成手头上的工作后就整理出来，测试CPS又遇到点小问题，马上再提交下请教您

**Comment by zcj88** [comment]
请问同样是这个提示error，尝试修改了很多参数还是error，要怎么处理呀？谢谢~
![image](https://github.com/baidu/dperf/assets/141379788/489da54a-30f5-4355-8871-5b2717ca8559)

**Comment by pengjianzhang** [comment]
请贴一下 text格式的配置文件

**Comment by zcj88** [comment]
mode                        client
tx_burst                    16
launch_num                  10
cpu                         1

payload_size                1
duration                    10m

cps                         0.5m
cc                          1k
keepalive                   60s

#port             pci            clientaddr    serveraddr        [servertmac]
port            0000:0a:00.0   6.6.245.1      6.6.245.130    00:92:10:00:3c:db

#                           addr_start      num
client                      6.6.245.1       20

#                           addr_start      num
server                      6.6.245.130       1
#                           port_start      num
listen                      80              32

**Comment by zcj88** [comment]
[cc.txt](https://github.com/baidu/dperf/files/12356110/cc.txt)

**Comment by pengjianzhang** [comment]
没有复现
1. 请用最新的dperf测一下
2. 把你的环境贴一下
   OS CPU kernel dperf版本
3. 把你的配置文件内容直接贴出来
