### ISSUE TITLE
CPS测试遇到的一些疑问

### ISSUE THREAD

**Issue by zcj88** [baidu/dperf#353]
1、测试CPS时，server和client端都设置运行60s，但client端到时间不能停止，需手动按ctrl+c才能停止；
2、测试过程中出现很多imissed/skErr/dropTx等红色提示，需要管它们吗，还是直接看skopen值即可？
3、skopen值是看测试过程中的值，还是最终结束后的值？
4、CPS测试过程中，skopen值是陆续增加到client端所设定的CPS值，例设置500k，大概测试30s左右就达到500K，此时就出现很多红色提示，若改为200K就几乎没有，这个CPS值的设定怎么确定呢？
谢谢~

**Comment by pengjianzhang** [comment]
> 1、测试CPS时，server和client端都设置运行60s，但client端到时间不能停止，需手动按ctrl+c才能停止；

 启动爬坡时间不包括在duration

>  2、测试过程中出现很多imissed/skErr/dropTx等红色提示，需要管它们吗，还是直接看skopen值即可？ 
需要

> 3、skopen值是看测试过程中的值，还是最终结束后的值？ 
测试中

> 4、CPS测试过程中，skopen值是陆续增加到client端所设定的CPS值，例设置500k，大概测试30s左右就达到500K，此时就出现很多红色提示，若改为200K就几乎没有，这个CPS值的设定怎么确定呢？ 谢谢~
逐步调整参数，增加资源，CPU个数，IP数量，端口数量等

**Comment by zcj88** [comment]
1、测试CPS时，server和client端都设置运行60s，但client端到时间不能停止，需手动按ctrl+c才能停止；

启动爬坡时间不包括在duration——提问人员答复：试了下client端设置30s会和server端的60s差不多同时停止

**Comment by pengjianzhang** [comment]
测试时 server长期跑， client 一般ctl +c停止

**Comment by zcj88** [comment]
好的，就是前提不能出现红色的提示，一旦出现就要调整参数哈？
