### ISSUE TITLE
请教一下代码中的RSS问题

### ISSUE THREAD

**Issue by CChuancey** [baidu/dperf#358]
我想问下`rss_hash_key_symmetric`数组为什么是固定值？
下面是我的分析：
rss.c中定义了一个`rss_hash_key_symmetric`数组，在`rss_init`中使用`rte_convert_rss_key`将其转换为`rss_hash_key_symmetric`中。后面又用[rte_softrss_be()](https://doc.dpdk.org/api-21.11/rte__thash_8h.html#a00a9d49d177be1bf3ea42e0825b310bb)来计算出RSS的hash值。如果在client工作时启用了RSS，需要根据`config`遍历所有可能的socket，挑出满足与NIC的RSS计算出hash一致的socket。
这样如何保证：使用这个固定的`rss_hash_key_symmetric`就能计算出与NIC的RSS一致的socket？这个数组有什么特别之处吗？

**Comment by pengjianzhang** [comment]
rss_hash_key_symmetric 是一个特别的Key，能够使得rx/tx两个方向的rss哈希值一样

**Comment by CChuancey** [comment]
> 

感谢，我明白了
