### ISSUE TITLE
dperf测试nginx性能

### ISSUE THREAD

**Issue by sunny123g** [baidu/dperf#359]
请问dperf可以作为客户端，用来测试nginx的性能吗？
在dperf的客户端配置文件中，怎么配置服务端端口吗？
[root@localhost http]# cat client-cps.conf 
mode        client
cpu         0
duration    10s
cps         10k
port        0000:13:00.0    172.17.1.152   172.17.1.1
client      172.17.1.152      1
server      172.17.1.105     1
listen      80                      1

**Comment by pengjianzhang** [comment]
可以，只支持HTTP协议，不支持HTTPS
请参考配置文档，以及知乎文章
listen 80 1  就向80端口发送请求

**Comment by sunny123g** [comment]
测试并发数，上限为65535，若将lport_range的上限改为大于65535，就会报错line 13: error，配置如下

      1 mode        client
      2 cpu         0
      3 duration    60s
      4 cc         100000
      5 keepalive   60s
      6 cps         30k
      7 port        0000:13:00.0    172.17.1.152   172.17.1.1
      8 #port        0000:1b:00.0    172.17.1.209   172.17.1.1
      9 #client      172.17.1.209     1
     10 client      172.17.1.152     1
     11 server      172.17.1.105     1
     12 listen      80              1
     13 lport_range 1 65538

line 13: error

查看代码将#define NETWORK_PORT_NUM    65536改为#define NETWORK_PORT_NUM    250000
运行几秒后，出现段错误。

请问如果将并发数调大呢？

**Comment by pengjianzhang** [comment]
增加client ip数
增加listen 端口数

**Comment by sunny123g** [comment]
1、client ip数是真实网卡的数量，还是虚拟的？
看说明：在client模式下，'client'数量需要与'port'的数量一致，并且一一对应。做过dpdk绑定的网卡，数量有限。
2、listen端口是服务端监听端口，如果服务器只监听一个端口，是不是就不能改了？
