### ISSUE TITLE
支持一台机器上模拟出多个源IP发起请求负载测试吗

### ISSUE THREAD

**Issue by a1198457636** [baidu/dperf#360]
请问支持一台机器上模拟出多个源IP发起请求负载测试吗

**Comment by pengjianzhang** [comment]
可以，用'client' 配置一个C段IP，可以配置多个'client'

**Comment by a1198457636** [comment]
> 可以，用'client' 配置一个C段IP，可以配置多个'client'

支持TCP和UDP协议的压测吗？谢谢

**Comment by pengjianzhang** [comment]
支持，请阅读配置手册，喜欢dperf请加个star，谢谢

**Comment by a1198457636** [comment]
> 支持，请阅读配置手册，喜欢dperf请加个star，谢谢

好的谢谢，已经关注项目了
