### ISSUE TITLE
not enough ports available: avail 0 require 1

### ISSUE THREAD

**Issue by TAO-PAN** [baidu/dperf#361]
执行之后报错怎么解决呢？ 
 ./build/dperf -c test/http/server-cps.conf
EAL: Detected CPU lcores: 16
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
TELEMETRY: No legacy callbacks, legacy socket not created
not enough ports available: avail 0 require 1
port init fail
dpdk init fail

**Comment by pengjianzhang** [comment]
是不是没有绑网卡，
参考 readme上 FAQ 文章 最后一节
