### ISSUE TITLE
dperf启动成功，ip不通 端口监听不存在

### ISSUE THREAD

**Issue by TAO-PAN** [baidu/dperf#362]
使用命令./build/dperf -c  test/http/server-cps.conf启动dperf   ,
server-cps.conf内容如下
mode        server
cpu         0
duration    10m
port        0000:06:00.2    6.6.241.27   6.6.241.1 8c:1c:da:44:ef:fa
client      6.6.241.1       1
server      6.6.241.27      1
listen      80              1

启动后dperf进程存在，但是80端口没有查找到监听，用客户端（6.6.241.1） ping 6.6.241.27 也不通。
启动后dperf会输出，只截取了部分日志
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:06:00.2 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb

seconds 26                 cpuUsage 0   
pktRx   0                  pktTx    0                  bitsRx   0                  bitsTx  0                  dropTx  0                 
tcpRx   0                  tcpTx    0                  udpRx    0                  udpTx   0                 
arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
tosRx   0                  otherRx  0                  badRx    0                 
synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 0         
synRt   0                  finRt    0                  ackRt    0                  pushRt  0                 
tcpDrop 0                  udpDrop  0         
请问这个怎么解决

**Comment by pengjianzhang** [comment]
1. dperf bypass kernel了，用Linux命令是查不到的
2.  8c:1c:da:44:ef:fa 是 6.6.241.1的MAC地址吗，clint与dperf同一个网段 可以不配网关MAC地址，dperf可以学习到

**Comment by TAO-PAN** [comment]
不配置网关启动会报错 bad gateway. dperf cannot find gateway`s Macaddress please check the link ,
8c:1c:da:44:ef:fa是6.6.241.1的mac地址，client与dperf通过网线直连的。

**Comment by TAO-PAN** [comment]
1.6.6.241.1学习不到6.6.241.27 
2.这是运行完的汇总信息
-----------------------
dperf Test Finished
Version: 1.6.0-dev
License: Apache 2.0
Author:  Jianzhang Peng
-----------------------

Total Numbers:
pktRx   0                  pktTx    2                  bitsRx   0                  bitsTx  672                dropTx  0
tcpRx   0                  tcpTx    0                  udpRx    0                  udpTx   0
arpRx   0                  arpTx    2                  icmpRx   0                  icmpTx  0
tosRx   0                  otherRx  0                  badRx    0
synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 0
synRt   0                  finRt    0                  ackRt    0                  pushRt  0
tcpDrop 0                  udpDrop  0
skOpen  0                  skClose  0                  skCon    0                  skErr   0
httpGet 0                  http2XX  0                  httpErr  0
ierrors 0                  oerrors  0                  imissed  0
3.网卡支持的 inter的I350网卡

**Comment by pengjianzhang** [comment]
连接到交换机上试试，不要直连

**Comment by pengjianzhang** [comment]
你用dpdk自带的testpmd试试能不能跑起来
你用什么网卡，dpdk版本是多少

**Comment by TAO-PAN** [comment]
./dpdk-devbind.py -s 

Network devices using DPDK-compatible driver
============================================
0000:06:00.2 'I350 Gigabit Network Connection 1521' drv=uio_pci_generic unused=igb
 intel I350网卡

**Comment by pengjianzhang** [comment]
dperf没有测试过千兆网卡
试试igb_uio驱动

**Comment by TAO-PAN** [comment]
我使用这个机器的其他网绑定dpdk  ,使用igb_uio驱动
网卡信息:
Network devices using DPDK-compatible driver
============================================
0000:02:00.0 'Ethernet Controller X710 for 10GbE SFP+ 1572' drv=igb_uio unused=i40e,uio_pci_generic
启动dperf报错
./build/dperf -c test/http/server-cps.conf > a.txt & 
[1] 2407
[root@localhost dperf]# EAL: Detected 16 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:02:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1572 net_i40e
eth_i40e_dev_init(): Failed to init adminq: -66
ethdev initialisation failed
EAL: Requested device 0000:02:00.0 cannot be used

**Comment by pengjianzhang** [comment]
X710是支持的，给我邮箱pengjianzhang@gmail.com 发个腾讯会议，一起看下

**Comment by TAO-PAN** [comment]
目前怀疑可能是硬件问题导致dpdk收不到包 ，我明天换个机器安装试试

**Comment by TAO-PAN** [comment]
我更换机器后，目前测试6.6.241.1可以ping通6.6.241.27了 ，但是客户端使用curl  ab等工具测试都提示连接拒绝，这是curl后dperf的输出
seconds 338                cpuUsage 0   
pktRx   1                  pktTx    1                  bitsRx   592                bitsTx  432                dropTx  0                 
tcpRx   1                  tcpTx    0                  udpRx    0                  udpTx   0                 
arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                 
tosRx   0                  otherRx  0                  badRx    0                 
synRx   0                  synTx    0                  finRx    0                  finTx   0                  rstRx   0          rstTx 1         
synRt   0                  finRt    0                  ackRt    0                  pushRt  0                 
tcpDrop 0                  udpDrop  0                 
skOpen  0                  skClose  0                  skCon    0                  skErr   0                 
httpGet 0                  http2XX  0                  httpErr  0                 
ierrors 0                  oerrors  0                  imissed  0    
请问该如何排查

**Comment by pengjianzhang** [comment]
请仔细阅读配置手册，client , server部分
