### ISSUE TITLE
使用dperf测试Mellanox网卡与Xilinx Ultrascale+ UDP 100Gbps IP核之间通信性能

### ISSUE THREAD

**Issue by liubenyuan** [baidu/dperf#363]
我在Xilinx Ultrascale+ FPGA上实现了一个100G UDP IP核，我想使用dperf测试一下这个Ip核的性能，顺便也想深入学习一下dperf这个工具。是顺着您的文章：https://zhuanlan.zhihu.com/p/484252751 来到这里提issue的

这边实验设置是，
  1. 一块双口Mellanox MCX623106A DX网卡，有两个QSFP56接口，我们叫他端口1和端口2
  2. 两根100G AOC线及光模块
  3. 一块FPGA开发板，上面有两个QSFP28接口，其中1个例化了一个100G UDP核，用户端TX数据和RX数据回环短接，方便测试。这个叫端口3
  4. 操作系统是Archlinux 6.4.11 xanmod内核，安装了开源的mstflint工具，目前可以显示固件版本号，也可以在系统中看到两个网卡

我想先安装驱动，然后按照以下几个流程测试，想请问下是否可行？应该如何做呢，有没有tutorial？
  1. 需要先按照zhihu的教程做么？
  2. 测试项目1：mellanox网卡回环测试。Port1 ping Port2，或者此时用dperf测试端口1到端口2的吞吐性能。这样做的目的是先保证一个正确的工作环境，同时学习dperf的使用方法
  3. 测试项目2：mellanox端口1到FPGA端口3测试。使用dperf测试mellanox网卡与用户设备的通信性能。

目前对于dperf和100G我还是新手，上述描述不对的地方请指正。

**Comment by pengjianzhang** [comment]
可以做，请参考一下readme上文章，以及配置手册
