### ISSUE TITLE
在VDPA +ovs 卸载的情况下下怎么使用dperf

### ISSUE THREAD

**Issue by mannicui** [baidu/dperf#364]
1.我们公司自己的网卡，想测试一下vdpa+ovs 卸载情况下,两个vf 的性能。测试一下pps 和bps ，两个vf 的绑定两个虚拟机，两个vf 的代表口都加到了ovs 桥上。我在虚拟机里面装了dpdk19..11 和dperf, 用的是udp 文件夹下的配置文件，但是报错了。
[root@test01 dperf-main]# ./build/dperf -c server-cps.conf
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: PCI device 0000:00:05.0 on NUMA socket -1
EAL:   probe driver: 1af4:1000 net_virtio
socket allocation succeeded, size 0.01GB num 65535
Error: bad gateway. dperf cannot find gateway's MAC address. Please check the link.

配置文件如下：
[root@test01 dperf-main]# vi server-cps.conf

mode        server
cpu         0
duration    10m
port        0000:00:05.0    1.1.1.2  1.1.1.3
client      1.1.1.3         1
server      1.1.1.2         1
listen      80              1
~

**Comment by pengjianzhang** [comment]
client server 互指就可以了

**Comment by mannicui** [comment]
我就是互指的啊，显示Error: bad gateway. dperf cannot find gateway's MAC address. Please check the link.

发件人: Jianzhang Peng ***@***.***>
发送时间: 2023年8月28日 14:25
收件人: baidu/dperf ***@***.***>
抄送: Manni Cui ***@***.***>; Author ***@***.***>
主题: Re: [baidu/dperf] 在VDPA +ovs 卸载的情况下下怎么使用dperf (Issue #364)


client server 互指就可以了

**Comment by mannicui** [comment]
这是client
mode        client
cpu         0
duration    10m
port        0000:00:05.0    1.1.1.3  1.1.1.2
client      1.1.1.3         1
server      1.1.1.2         1
listen      80              1
~

**Comment by pengjianzhang** [comment]
把mac地址配上

**Comment by mannicui** [comment]
就在这个dperf 的client-cps.conf 和server-cps.conf的配置文件里都要配置么？随便写mac吗？感谢

发件人: Jianzhang Peng ***@***.***>
发送时间: 2023年8月28日 14:33
收件人: baidu/dperf ***@***.***>
抄送: Manni Cui ***@***.***>; Author ***@***.***>
主题: Re: [baidu/dperf] 在VDPA +ovs 卸载的情况下下怎么使用dperf (Issue #364)


把mac地址配上

**Comment by pengjianzhang** [comment]
请参考配置文档
client上配置server的MAC
server上配client的MAC

**Comment by mannicui** [comment]
谢谢，请问支持dpdk 支持21.11 吗？

发件人: Jianzhang Peng ***@***.***>
发送时间: 2023年8月28日 16:04
收件人: baidu/dperf ***@***.***>
抄送: Manni Cui ***@***.***>; Author ***@***.***>
主题: Re: [baidu/dperf] 在VDPA +ovs 卸载的情况下下怎么使用dperf (Issue #364)


请参考配置文档
client上配置server的MAC
server上配client的MAC

**Comment by pengjianzhang** [comment]
支持

**Comment by mannicui** [comment]
你好，我刚才用dpdk21 编译报错了，麻烦帮我看看，谢谢

***@***.*** home]# cd dperf-main
***@***.*** dperf-main]# make -j8 RTE_SDK=/home/dpdk-stable-21.11.5 RTE_TARGET=$TARGET
Makefile:23: /home/dpdk-stable-21.11.5/mk/rte.extapp.mk: No such file or directory
make: *** No rule to make target '/home/dpdk-stable-21.11.5/mk/rte.extapp.mk'.  Stop.

发件人: Jianzhang Peng ***@***.***>
发送时间: 2023年8月28日 19:24
收件人: baidu/dperf ***@***.***>
抄送: Manni Cui ***@***.***>; Author ***@***.***>
主题: Re: [baidu/dperf] 在VDPA +ovs 卸载的情况下下怎么使用dperf (Issue #364)


支持
