### ISSUE TITLE
请教一下代码中的预取操作

### ISSUE THREAD

**Issue by CChuancey** [baidu/dperf#365]
请问一下，在`src/loop.h`的`client_recv_mbuf`函数中，使用到了`mbuf_prefetch`操作。
1. 这个预取有什么作用？
2. 为什么要预取？
3. 预取操作和包处理操作是并行的吗？
4. 预取个数为什么是4？
谢谢！

**Comment by pengjianzhang** [comment]
提升访存效率，看看dpdk文档
