### ISSUE TITLE
统计数据异常，指标synRt和skErr

### ISSUE THREAD

**Issue by owenstake** [baidu/dperf#366]
统计数据异常，指标synRt和skErr，能帮忙看下原因么？
统计数据如下：
![image](https://github.com/baidu/dperf/assets/45960823/de10d86a-707d-439d-a9ad-225d06476d44)

模型图：
![image](https://github.com/baidu/dperf/assets/45960823/70863d25-bda5-4a5a-b194-65c8e6d4920a)

配置文件如下：
server端配置:
```bash
mode            server
cpu             64-71
socket_mem      0,10240
duration        1d
payload_size    1
protocol        http
#port   pci             addr            gateway(ovs-vtep)       outer-mac(ovs-vtep)
port    0000:81:00.0    2.2.2.2         1.1.1.1                 00:11:22:33:44:55
#port   0000:81:00.0    2.2.2.2         10.0.0.1                8c:2a:8e:55:73:ff
client  1.1.1.1         1
server  2.2.2.2         8
listen  80              1
```

client端配置:
```bash
mode            client
cpu             1-8
socket_mem      10240,0
tx_burst        32
payload_size    1
launch_num      1
payload_size    1
duration        2d
protocol        http
keepalive 1ms 5
cps             10
#port           pci             addr            gateway(ovs-vtep)       outer-dmac(ovs-vtep)
port            0000:02:00.0    10.0.0.2        10.0.0.1                8c:2a:8e:55:73:ff
#port           0000:02:00.0    10.0.0.2        10.0.0.1

#vxlan          vni             inner-smac          inner-dmac          vtep-local  num vtep-remote(ovs)        num
vxlan           1000            00:11:22:33:44:55   8c:2a:8e:55:73:97   10.0.0.2    8   10.0.0.1                1

#       addr_start      num
client  1.1.1.1         1
server  2.2.2.2         8
listen  80              1

```

**Comment by pengjianzhang** [comment]
用bond了么？

你用1个CPU 试试

protocol udp
keepalive 1ms

**Comment by owenstake** [comment]
> 用bond了么？
> 
> 你用1个CPU 试试
> 
> protocol udp keepalive 1ms

client端 还是 server端？

**Comment by pengjianzhang** [comment]
全部

**Comment by owenstake** [comment]
> protocol udp
> keepalive 1ms

统计结果
client端
![image](https://github.com/baidu/dperf/assets/45960823/bc59c996-87b2-43bb-87a1-0febe3b81ac5)

server端
![image](https://github.com/baidu/dperf/assets/45960823/aa88b56b-98ad-4559-8fa7-71ddce22915f)

**Comment by pengjianzhang** [comment]
nat网关做NAT了吗？

**Comment by owenstake** [comment]
> nat网关做NAT了吗？

没有。

**Comment by pengjianzhang** [comment]
server上没有收到数据啊

**Comment by owenstake** [comment]
> server上没有收到数据啊

我调整了下nat网关配置，现在的统计 是这样的

**Comment by owenstake** [comment]
> 用bond了么？
> 
> 你用1个CPU 试试
> 
> protocol udp keepalive 1ms

我调整了下nat网关，现在统计是这样的
![image](https://github.com/baidu/dperf/assets/45960823/866effac-381c-46f7-ad3a-a43a83a6cc56)

![image](https://github.com/baidu/dperf/assets/45960823/70d38589-0c4c-488f-9855-0fc2ba27fda6)

**Comment by owenstake** [comment]
> > 用bond了么？
> > 你用1个CPU 试试
> > protocol udp keepalive 1ms
> 
> 我调整了下nat网关，现在统计是这样的 ![image](https://user-images.githubusercontent.com/45960823/263891428-866effac-381c-46f7-ad3a-a43a83a6cc56.png)
> 
> ![image](https://user-images.githubusercontent.com/45960823/263891441-70d38589-0c4c-488f-9855-0fc2ba27fda6.png)

这算是正常了么

**Comment by owenstake** [comment]
> > 用bond了么？
> > 你用1个CPU 试试
> > protocol udp keepalive 1ms
> 
> 我调整了下nat网关，现在统计是这样的 ![image](https://user-images.githubusercontent.com/45960823/263891428-866effac-381c-46f7-ad3a-a43a83a6cc56.png)
> 
> ![image](https://user-images.githubusercontent.com/45960823/263891441-70d38589-0c4c-488f-9855-0fc2ba27fda6.png)

@pengjianzhang  这算是正常么

**Comment by pengjianzhang** [comment]
比较正常，但是还是有些丢包，client上发生了重传

**Comment by pengjianzhang** [comment]
看起来是 client没有识别服务器返回的报文，都丢掉了，是不是vxlan格式问题

**Comment by owenstake** [comment]
> 比较正常，但是还是有些丢包，client上发生了重传

回到 protocal http 的情况，现在的统计如下
server端
![image](https://github.com/baidu/dperf/assets/45960823/598339a7-d153-40f7-9706-07b928f2ff9d)
client端
![image](https://github.com/baidu/dperf/assets/45960823/00fe3990-353b-459a-bf01-10962cadb4f3)

**Comment by owenstake** [comment]
> > 比较正常，但是还是有些丢包，client上发生了重传
> 
> 回到 protocal http 的情况，现在的统计如下 server端 ![image](https://user-images.githubusercontent.com/45960823/263892393-598339a7-d153-40f7-9706-07b928f2ff9d.png) client端 ![image](https://user-images.githubusercontent.com/45960823/263892423-00fe3990-353b-459a-bf01-10962cadb4f3.png)

nat网关bond0抓包，抓到服务端的回包
![image](https://github.com/baidu/dperf/assets/45960823/b23b1c8a-a1f2-47de-93c4-9b516f768ed8)

**Comment by owenstake** [comment]
目前抓包，只有两次握手的报文（syn 和 syn+ack），没有最后一次的 握手报文（ack报文）

**Comment by pengjianzhang** [comment]
client不单独发ACK，ACK是和数据一起发的

**Comment by owenstake** [comment]
> > > 比较正常，但是还是有些丢包，client上发生了重传
> > 
> > 
> > 回到 protocal http 的情况，现在的统计如下 server端 ![image](https://user-images.githubusercontent.com/45960823/263892393-598339a7-d153-40f7-9706-07b928f2ff9d.png) client端 ![image](https://user-images.githubusercontent.com/45960823/263892423-00fe3990-353b-459a-bf01-10962cadb4f3.png)
> 
> nat网关bond0抓包，抓到服务端的回包 ![image](https://user-images.githubusercontent.com/45960823/263892836-b23b1c8a-a1f2-47de-93c4-9b516f768ed8.png)

@pengjianzhang  讲道理，抓包有syn+ack，client 应该不会有 synRt(重传) 啊。

**Comment by owenstake** [comment]
@pengjianzhang  我这个配置文件 有问题么？

**Comment by pengjianzhang** [comment]
看起来没问题
是不是你的NAT没有把服务器的回包转给客户端啊

**Comment by pengjianzhang** [comment]
client检查到报文不符合要求，识别为other。
请对照vxlan_input（）函数检查一下。
贴一下nat转给client的报文截图

**Comment by owenstake** [comment]
> client检查到报文不符合要求，识别为other。 请对照vxlan_input（）函数检查一下。 贴一下nat转给client的报文截图

![image](https://github.com/baidu/dperf/assets/45960823/3e2c0cb4-0af8-4b86-829e-abf5617c0fc8)

**Comment by pengjianzhang** [comment]
看看vxlan封装的报文

**Comment by owenstake** [comment]
> 看看vxlan封装的报文

这个ovs-tcpdump 抓不到，有解封装后的报文 应该就可以吧。

**Comment by owenstake** [comment]
> 看看vxlan封装的报文
可以抓到bond0出去的syn+ack 报文
![image](https://github.com/baidu/dperf/assets/45960823/b62e35ed-b803-4c2e-9799-05546a19a2dd)

**Comment by pengjianzhang** [comment]
vni不对，要与配置中相同

**Comment by owenstake** [comment]
@pengjianzhang 后续我会整理一个短文出来，给dperf捧场

**Comment by pengjianzhang** [comment]
谢谢  也麻烦在周围同事、朋友中间宣传一下
