### ISSUE TITLE
如何在一定的并发和PPS基础上，加大流量

### ISSUE THREAD

**Issue by alongpan** [baidu/dperf#369]
目标：在固定的并发下，测试出来被测目标能承受pps和bps的最大值。
操作：所以根据以上条件，CC固定的不能变；通过keepalive将pps也调到了稳定值，所以keepalive也固定了，现在需要在这基础上继续加大流量，但是增加packet_size后pps就降下来了，这个应该怎么设置呢？

**Comment by pengjianzhang** [comment]
增加CPU个数
