### ISSUE TITLE
Can dperf return large responses?

### ISSUE THREAD

**Issue by happybigeyes** [baidu/dperf#372]
基于目前的 CPS HTTP新建打流的模板 可以配置回包的数量 模拟或接近HTTP 21K的标准测试

**Comment by pengjianzhang** [comment]
http 21K是什么

**Comment by happybigeyes** [comment]
1. 应用层吞吐量

&nbsp;

测试方法：在开启应用识别引擎的前提下，通过发送平均21K大小HTTP页面来测试设备应用层最大吞吐量，且只能计算成功获得HTTP响应的连接。

（说明：选取大小为21K的页面，是基于该厂商对多家高校、运营商等典型网络环境的长期流量统计，总结得出对于每Gbps的流量，包速率采用185Kpps、平均包长670字节、新建连接速率5000个/秒，能够比较准确地描述实际流量，可以作为实际性能测试的流量模型。将流量换算为HTTP页面，恰好为21K。）





说简单一点就是client&nbsp; http 每个连接能请求到21K字节的固定或随机内容 能反映设备在真实环境的表现（高并发的吞吐值 ）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/dperf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 上午9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/dperf] 希望加入HTTP 21K 的功能测试 (Issue #372)





 
http 21K是什么

**Comment by pengjianzhang** [comment]
如果是测吞吐的话，服务器用nginx就可以了

**Comment by happybigeyes** [comment]
nginx 性能达不到 是测试防火墙

**Comment by pengjianzhang** [comment]
试试fstack nginx, t-trx
或者 jumbo frame，9K大包

**Comment by pengjianzhang** [comment]
正在考虑在下个版本支持，请帮忙测试

**Comment by hgkiller** [comment]
好建议

**Comment by pengjianzhang** [comment]
请测试这个分支：
https://github.com/pengjianzhang/dperf

配置：
mode                    server
protocol               http
payload_size       21k
send_window      6

**Comment by happybigeyes** [comment]
发现一个BUG ，在使用HTTP 21K测试时候，超过十几分钟，就不回包了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/dperf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月4日(星期三) 晚上9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/dperf] 希望加入HTTP 21K 的功能测试 (Issue #372)





 
请测试这个分支：
 https://github.com/pengjianzhang/dperf
 
配置：
 mode                    server
 protocol               http
 payload_size       21k
 send_window      6

**Comment by pengjianzhang** [comment]
拉最新代码

**Comment by pengjianzhang** [comment]
please refer 
https://dperf.org/doc/html/dperf-http-server

**Comment by happybigeyes** [comment]
How to determine send_window 's&nbsp; &nbsp;value? How to adjust this parameter


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/dperf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月10日(星期二) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/dperf] Can dperf return large responses? (Issue #372)





 
please refer
 https://dperf.org/doc/html/dperf-http-server

**Comment by pengjianzhang** [comment]
Use the default value (4), increase it if you want it to be faster, decrease it if you find an error
