### ISSUE TITLE
dperf make error on ubuntu 22.4

### ISSUE THREAD

**Issue by zcj88** [baidu/dperf#375]

**Comment by zcj88** [comment]
1、测试环境
ubuntu 22.4 + dpdk23.03
2、DPDK编译成功，路径如下：
![企业微信截图_16958122192057](https://github.com/baidu/dperf/assets/141379788/6c3e6899-490a-4f5a-af00-7748c6022e4c)

3、dperf make出错，如下：
![企业微信截图_16958121695303](https://github.com/baidu/dperf/assets/141379788/86e2d2c6-47e3-41cd-8251-d26d91f79dca)

**Comment by pengjianzhang** [comment]
谢谢反馈

**Comment by zcj88** [comment]
> 谢谢反馈
> 
> 请参考文章，注意编译DPDK的参数 https://dperf.org/doc/html/compile-dperf-on-dpdk-23
我实际按照链接中的要求重新弄了下，没有lib64文件夹，只有lib文件夹，make还是同样出错的情况
![image](https://github.com/baidu/dperf/assets/141379788/dd587fae-89cd-4fe9-a7fb-da650a140fc1)

**Comment by pengjianzhang** [comment]
看一下meson build的输出，如果看到drivers->net->kni，则表明kni编译进去了

===============
Drivers Enabled
===============

common:
	cpt, dpaax, iavf, idpf, octeontx, cnxk, qat, sfc_efx,

bus:
	auxiliary, cdx, dpaa, fslmc, ifpga, pci, platform, vdev,
	vmbus,
mempool:
	bucket, cnxk, dpaa, dpaa2, octeontx, ring, stack,
dma:
	cnxk, dpaa, dpaa2, hisilicon, idxd, ioat, skeleton,
net:
	af_packet, ark, atlantic, avp, axgbe, bnx2x, bnxt, bond,
	cnxk, cpfl, cxgbe, dpaa, dpaa2, e1000, ena, enetc,
	enetfec, enic, failsafe, fm10k, gve, hinic, hns3, i40e,
	iavf, ice, idpf, igc, ionic, ixgbe, **kni**, memif,
	netvsc, nfp, ngbe, null, octeontx, octeon_ep, pfe, qede,
	ring, sfc, softnic, tap, thunderx, txgbe, vdev_netvsc, vhost,
	virtio, vmxnet3,

**Comment by zcj88** [comment]
![image](https://github.com/baidu/dperf/assets/141379788/807f584e-b0da-425d-8de7-9fe7e399f993)
有kni呢

**Comment by pengjianzhang** [comment]
能找到头文件吗 mydpdk/include/rte_kni.h

**Comment by zcj88** [comment]
没找到呢，但我确实没安装上kernel-devel
![image](https://github.com/baidu/dperf/assets/141379788/607d3b58-7538-47b7-8a50-453593465451)

**Comment by pengjianzhang** [comment]
ubuntu上的包是这个
linux-kernel-headers kernel-package

**Comment by zcj88** [comment]
提示如下，
![image](https://github.com/baidu/dperf/assets/141379788/6244ae8b-2322-48e2-8ec9-84667d315edc)
dpdk-23.07/mydpdk/include/rte_kni.h文件也有，但还是make出错
![image](https://github.com/baidu/dperf/assets/141379788/cd43ea20-4dd2-4926-851e-552dc5693d1d)

**Comment by pengjianzhang** [comment]
可能是DPDK的一个BUG吧

**Comment by pengjianzhang** [comment]
你用的是ubuntu什么版本

**Comment by zcj88** [comment]
22.04 LTS

**Comment by pengjianzhang** [comment]
please refer to build 
https://dperf.org/doc/html/compile-dperf-on-ubuntu-22.04

**Comment by zcj88** [comment]
已编译成功，谢谢帮忙~~

**Comment by zcj88** [comment]
您好，我是在上面这些环境下运行dperf，出错提示，修改很多参数，还是一样运行不了呢，如图：
ubuntu 22.04 + dpdk23.07，intel i211芯片
![image](https://github.com/baidu/dperf/assets/141379788/c5d3bcdd-eb44-4c65-8fcf-490182af0812)

**Comment by pengjianzhang** [comment]
please read documents at dperf.org

**Comment by zcj88** [comment]
您好，我重新装了系统重新按照您给的方式编译，运行dperf时提示缺少库文件，不清楚要怎么处理呢，
按照的是这里的步骤：https://dperf.org/doc/html/compile-dperf-on-ubuntu-22.04
![image](https://github.com/baidu/dperf/assets/141379788/f6a3952d-cc3e-4b1a-87a2-29dbb6039133)

**Comment by zcj88** [comment]
cd dperf
export PKG_CONFIG_PATH=/root/dpdk/dpdk-23.07/mydpdk/lib            //执行了这个路径后解决
make
