### ISSUE TITLE
dpdk18.11版本编译dperf 1.1.0以上版本报错

### ISSUE THREAD

**Issue by amberlipp** [baidu/dperf#376]
# rpm -qa | grep dpdk
dpdk-devel-18.11.8-2.el7.x86_64
dpdk-18.11.8-2.el7.x86_64

# cd dperf; make
  CC src/main.o
  CC src/socket.o
  CC src/config.o
  CC src/client.o
  CC src/mbuf_cache.o
  CC src/udp.o
  CC src/port.o
  CC src/mbuf.o
  CC src/arp.o
  CC src/icmp.o
  CC src/tcp.o
  CC src/tick.o
  CC src/http.o
  CC src/net_stats.o
  CC src/flow.o
  CC src/work_space.o
  CC src/cpuload.o
  CC src/config_keyword.o
  CC src/socket_timer.o
  CC src/ip.o
  CC src/eth.o
  CC src/server.o
  CC src/dpdk.o
  CC src/ctl.o
  CC src/icmp6.o
  CC src/neigh.o
  CC src/vxlan.o
  CC src/csum.o
  CC src/kni.o
  CC src/bond.o
  CC src/lldp.o
  CC src/rss.o
  LD dperf
src/bond.o: In function `bond_create':
/root/dperf/src/bond.c:37: undefined reference to `rte_eth_bond_create'
/root/dperf/src/bond.c:43: undefined reference to `rte_eth_bond_xmit_policy_set'
src/bond.o: In function `bond_config_slaves':
/root/dperf/src/bond.c:60: undefined reference to `rte_eth_bond_slave_add'
src/bond.o: In function `bond_wait':
/root/dperf/src/bond.c:80: undefined reference to `rte_eth_bond_active_slaves_get'
collect2: error: ld returned 1 exit status
make[1]: *** [dperf] Error 1
make: *** [all] Error 2

**Comment by pengjianzhang** [comment]
Thanks.
This DPDK package do not link to the bond library by default.
