### ISSUE TITLE
dperf测试LVS吞吐性能时，没有产生流量

### ISSUE THREAD

**Issue by jiawen94** [baidu/dperf#382]
你好，我最近在用dperf 1.5 测试lvs吞吐时，发现流量产生不了。请问dperf配置文件是否有错误的地方？
lvs 配置(暂时先配置一个real server，负载均衡tcp流量)
```
global_defs {
  router_id LVS_MAIN
  max_auto_priority 99
}
virtual_server 192.168.80.18 42023 {
  delay_loop 3
  lb_algo rr
  lb_kind NAT
  persistence_timeout 86400
  protocol TCP

  }
  real_server 172.30.18.11 42023 {
    weight 1
    TCP_CHECK {
      connect_timeout 3
    }

  }
}
```

dperf server配置
```
mode    server
cpu     3
tx_burst    1024
protocol    tcp
duration	660s
packet_size	512
keepalive   10us
port	0000:08:00.0	172.30.18.11	172.30.18.1	68:ed:a4:0d:9e:4e
client	192.168.80.9	1
server	172.30.18.11	1
listen	42023	1

payload_random
socket_mem  0
```
dperf client 配置
```
mode    client
tx_burst    1024
mode    client
launch_num  10
cpu 4
protocol    tcp
packet_size	512

duration	660s

cps	10
cc	50
keepalive   10us

port	0000:08:00.1	192.168.80.9	192.168.80.18	68:ed:a4:0d:9e:4b

client	192.168.80.9	1
server	192.168.80.18	1
listen	42023	1
```

拓扑(所有网口连在三层交换机上，dperf 服务端和客户端是在同一张网卡的两个网口上)：
dperf client 192.168.80.9---LVS WAN 192.168.80.18 ---LVS LAN 172.30.18.1---dperf server 172.30.18.11

**Comment by jiawen94** [comment]
![image](https://github.com/baidu/dperf/assets/29114225/73ec1635-08cb-4a95-a321-b9dc649a589c)
左边服务端，右边客户端

**Comment by jiawen94** [comment]
DUT能ping通dperf server的地址，但是无法获取到dperf server的监听端口
![image](https://github.com/baidu/dperf/assets/29114225/abdbcf52-7afc-44e4-a41d-be93a1054e1f)

**Comment by jiawen94** [comment]
1. lvs和dperf设置udp协议，dperf能够正常接收包
2. 我怀疑是lvs无法探测到dperf server的端口，因为dperf server这么配置的话，只接收从WAN口192.168.80.9的包，而不接收LAN口 172.30.18.1发来的探测包。
```
client	192.168.80.9	1
```
所以我在dperf server配置文件中增加了一个client配置
```
client	192.168.80.9	1
client        172.30.18.1     1 #让lvs探测到dperf server的端口
```
目前只是发包成功，我再抓个包验证一下

**Comment by Sincere001** [comment]
您好，我想问下，您的dperf，server端是配置在rs机器还是lvs机器呢

**Comment by pengjianzhang** [comment]
rs

**Comment by Sincere001** [comment]
> rs

谢谢

**Comment by Sincere001** [comment]
您好，我在启动客户端和服务端时均报错，想问下您该怎么解决
报错信息如下
EAL: Could not find space for memseg. Please increase CONFIG_RTE_MAX_MEMSEG_PER_TYPE and/or CONFIG_RTE_MAX_MEM_PER_TYPE in configuration.
EAL: Couldn't remap hugepage files into memseg lists
EAL: FATAL: Cannot init memory
EAL: Cannot init memory
rte_eal_init fail
dpdk_eal_init fail
dpdk init fail



client端配置
mode&nbsp; &nbsp; &nbsp; &nbsp; client
cpu&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0
cc&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 50
cps&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;50
duration&nbsp; &nbsp; 60s
tx_burst&nbsp; &nbsp; 1024
protocol&nbsp; &nbsp; tcp
keepalive&nbsp; &nbsp;10us
port&nbsp; &nbsp; &nbsp; &nbsp; 0000:81:00.1&nbsp; &nbsp; &nbsp;39.135.131.135 39.135.131.129&nbsp; &nbsp;04:b0:e7:f7:44:2c
client&nbsp; &nbsp; &nbsp; 39.135.131.135&nbsp; &nbsp; &nbsp; 2
server&nbsp; &nbsp; &nbsp; 39.135.131.134&nbsp; &nbsp; &nbsp; 1
listen&nbsp; &nbsp; &nbsp; 80&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1



server端配置
mode&nbsp; &nbsp; &nbsp; &nbsp; server
cpu&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;0
duration&nbsp; &nbsp; 60s
tx_burst&nbsp; &nbsp; 1024
protocol&nbsp; &nbsp; tcp
keepalive&nbsp; &nbsp;10us
port&nbsp; &nbsp; &nbsp; &nbsp; 0000:81:00.1&nbsp; &nbsp; &nbsp;39.135.131.135 39.135.131.129&nbsp; &nbsp;04:b0:e7:f7:44:2c
client&nbsp; &nbsp; &nbsp; 39.135.131.155&nbsp; &nbsp; &nbsp; 2
server&nbsp; &nbsp; &nbsp; 39.135.131.130&nbsp; &nbsp; &nbsp; 1
listen&nbsp; &nbsp; &nbsp; 80&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/dperf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/dperf] dperf测试LVS吞吐性能时，没有产生流量 (Issue #382)





 
rs
