### ISSUE TITLE
使用dperf作为客户端测试nginx性能

### ISSUE THREAD

**Issue by lx123789** [baidu/dperf#383]
dperf作为客户端，测试nginx
在192.168.1.2装了dperf，192.168.1.133为nginx，端口832
第一步：绑定网卡
[root@bsg dperf-main]# /root/dpdk-stable-19.11.14/usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:18:00.1 'Device 0103' drv=uio_pci_generic unused=ngbe

第二步：配置文件内容：
<img width="535" alt="image" src="https://github.com/baidu/dperf/assets/46477245/ea0059c8-8c74-4e18-b5d7-537e216ce799">
环境ping  curl都通，但是httpGet为0，结果如下：
<img width="959" alt="image" src="https://github.com/baidu/dperf/assets/46477245/fa926a02-5ba7-4ccf-a597-dd9abb6909b8">
请问可能是哪边的问题。

**Comment by HBSDLJZ** [comment]
请问这个问题解决了吗？
