### ISSUE TITLE
dperf测试吞吐量

### ISSUE THREAD

**Issue by lx123789** [baidu/dperf#384]
我想测一下向nginx 发送ipv4 ipv6双栈混合流量（IPv4和IPv6的流量比例1:1），流量大小为5Gbps，TCP新建为5000CPS（一个TCP会话中含有多个不同URL的Get和Post），并发连接不低于25万。
目前情况是，我用了两台dperf，一个打ipv4流量，一个打ipv6。我这边有几个问题想问下：

1. 同时打ipv4和ipv6，cps、cc的数量是要v4 v6加起来的吗

2.流量大小可以看 bitsRx 的值吗，结果没有满足5Gbps，要怎么调一下。

3. 分析结果显示丢包和skErr，是并发数不满足了吧

4. 支持测post吗？

如果其他参数配置有问题的地方可以指点一下谢谢。

ipv4配置：
```
mode        client
cpu         0
duration    60s
cc          130000
keepalive   60s
cps         5k
port        0000:18:00.1    192.168.1.2   192.168.1.1 c0:b8:e6:77:e6:ed  
client      192.168.1.2     100
server      192.168.1.133     1
listen      832   1     
http_path   /index.html 
protocol    http
```

ipv6配置：
```
mode    client
cpu      0
duration    60s
cps         5k
cc          130000
keepalive   60s
port    0000:18:00.0    fd12:3456:789a:bcde::5    fd12:3456:789a:bcde::1 c0:b8:e6:77:e6:ed
client   fd12:3456:789a:bcde::5     100
server  fd12:3456:789a:bcde::119      1
listen      832          1      
http_path   /index.html  
protocol     http
```

结果：
ipv4
<img width="961" alt="image" src="https://github.com/baidu/dperf/assets/46477245/5b1d5e7d-3e93-4bf4-b1d3-9379411a297e">

ipv6
<img width="960" alt="image" src="https://github.com/baidu/dperf/assets/46477245/3bde1aaf-f404-44bd-8cfe-8a2c13f830af">

**Comment by pengjianzhang** [comment]
please refer documents at dperf.org
