### ISSUE TITLE
dperf 可以实现在多port情况下，收包和发包分别用不同port 吗？

### ISSUE THREAD

**Issue by hgkiller** [baidu/dperf#391]
```
dperf 可以实现在多port情况下，收包 和 发包分别用不同port 吗？ 
比如client端，有两个port,  一个port 用来发包，一个 port 用来收包？
                        或者更复杂一点，每个port 可以绑定不同的vlan？
```

**Comment by pengjianzhang** [comment]
说一下背景吧 这个需求比较奇怪

**Comment by hgkiller** [comment]
比如要测试一台DDOS设备，设备进包 和 出包用的不同端口，不同vlan， 如果用dperf 作为客户端，怎么需要支持多port , 同时收包和发包也要使用不同port, 如下图：

**Comment by pengjianzhang** [comment]
通常情况下是不需要这个特性的，一个ip落在一个端口，rxtx在同一个端口。你们做金牌赞助吧，特别支持下

**Comment by hgkiller** [comment]
基本大部分DDOS 设备都是单向的，只关心进来的包，服务器返回的包可能走的是另一条路了，如下：

**Comment by hgkiller** [comment]
> 通常情况下是不需要这个特性的，一个ip落在一个端口，rxtx在同一个端口。你们做金牌赞助吧，特别支持下

**Comment by pengjianzhang** [comment]
用交换机是不是可以解决这个问题

**Comment by hgkiller** [comment]
交换机可以是可以，但那不是还得需要一台强悍的交换机吗

**Comment by pengjianzhang** [comment]
这个特性不适合加到dperf
