### ISSUE TITLE
dperf运行出错提示： work space init error

### ISSUE THREAD

**Issue by zcj88** [baidu/dperf#394]
client-cc-conf文件设置如下：
![image](https://github.com/baidu/dperf/assets/141379788/cdf874b3-351b-4606-b7fa-3e0734275f94)

dperf运行出错提示如下： work space init error
![image](https://github.com/baidu/dperf/assets/141379788/8d676df0-f046-45af-9a83-24f99dc7126a)

如果cc和cps设置大一点，dperf运行就会提示Error: insufficient sockets. 
请问要怎么解决呢，目前运行下来，client端都会出现这种情况，server-conf可以正常运行，谢谢~

**Comment by pengjianzhang** [comment]
please refer https://dperf.org/doc/html/dperf-faq

**Comment by zcj88** [comment]
1、上面的配置参数不变的情况下，把大页内存配置到8G，现象依旧；
![image](https://github.com/baidu/dperf/assets/141379788/3cc5bb18-6cb0-4ae6-be88-e35b954848cb)

2、IP数量低于100，或者CC和cps值比上面图片值大一些都会提示：Error：insufficient sockets
![image](https://github.com/baidu/dperf/assets/141379788/208b1b24-8fe1-403d-b7df-c6264d4f7620)
3、运行server.conf是可以的
![image](https://github.com/baidu/dperf/assets/141379788/23bdf0b7-1cd7-4c2c-85c2-df32bb297ae6)

请问还有其他原因吗，我加载的是UIO驱动，谢谢~

**Comment by amberlipp** [comment]
dperf初始化时客户端和服务端的打流的socket链接就会创建，这个问题会不会是系统内核socket连接数的限制，试试改大一些呢

**Comment by amberlipp** [comment]
当前环境的系统内存有多少？ free -m查看下呢

**Comment by zcj88** [comment]
> 当前环境的系统内存有多少？ free -m查看下呢 看了下源码，基于当前并发数、连接数的配置预估的内存数，需要大页内存至少15.63G以上； 你这边调整到8G大页应该还不够，如果系统内存充足的话，可以预设大页为32G试试 cat /proc/meminfo可以查看当前大页内存配置情况

我的系统内存只有16G，分配了8G大页，free还有6G多，我之前其实有测试成功过，但是最近一直卡住在要么Error: insufficient sockets，要么 work space init error，过不去了，试了好多平台复盘不出问题

**Comment by amberlipp** [comment]
建议增加内存条试试

**Comment by pengjianzhang** [comment]
请拉最新代码，增加了出错处理的提示

**Comment by zcj88** [comment]
这个问题的根本原因已找到，可能因为我的配置太低，把listen数量改低就能正常运行，conf配置文档默认32对我来说太多了，改为1或5都运行成功
