### ISSUE TITLE
新建连接数测试统计结果解读

### ISSUE THREAD

**Issue by ChristmasE** [baidu/dperf#396]
你好，使用dperf测试新建连接数客户端设置CPS=50k，当客户端skOpen稳定在50k时，服务端的skOpen一直是大于50k的（此时skCon不为0），这种情况怎么看实际的新建连接数呢？

**Comment by pengjianzhang** [comment]
以客户端为准，服务器端作为参考，由于统计的时间掐的没有那没准，50K左右，都可以认为是准确的。
