### ISSUE TITLE
如何使用 dperf测试高并发 CC 场景，并使用 post 请求，附带 payload

### ISSUE THREAD

**Issue by tangning9495** [baidu/dperf#397]
<img width="790" alt="7d3b7753e550918e4d9ae44f7" src="https://github.com/baidu/dperf/assets/56678507/f9861305-4486-43a2-b986-bc340cd79b2e">
<img width="905" alt="8d42f09b59fe3a331db9656e0ceb104c" src="https://github.com/baidu/dperf/assets/56678507/66c090ff-e868-4fdd-8368-81725fc17c6f">

如图，将 req 中的 GET 改成 POST，然后client 设置 payload 1000，进行了尝试。但是抓包发现，没有payload，只有/path上有数据，测试结果也不尽人意，这样的大包相比 包长64的情况，并发数下降了12倍（从350W降到28万），感觉和真实的场景也不太一样，数据不确定有没有参考价值。

**Comment by tangning9495** [comment]
想请问一下作者，怎么样修改才能满足这一测试场景呢？

**Comment by pengjianzhang** [comment]
对于request，是在Path上增加长度，并没有设置到Body；你可以参考一下response的设置。
为什么要用Post呢？
