### ISSUE TITLE
CPS多核模式下报错-怀疑是RSS算法导致的，有没有什么调优的方法呢？

### ISSUE THREAD

**Issue by yingweizhao** [baidu/dperf#398]
作者你好，我使用单核测试的时候可以达到320K的CPS，但是使用多核的时候报错就很严重，基本不能正常工作，还不如单核的性能：
#daemon
mode server
tx_burst 128
cpu 80-87
socket_mem 4096
duration 400s
payload_size 1
rss l3l4
#numa2
port 0000:43:00.1 192.168.31.200 192.168.31.1 00:0d:48:73:a2:6c

# addr_start           num
client 192.168.31.1 20

# ad:wqdr_start numserver
server 192.168.31.200 1

# port_start num
listen 80 1

**Comment by pengjianzhang** [comment]
client用的是dperf吗，试试rss auto

**Comment by yingweizhao** [comment]
client用的也是dperf-同一台机器，我的内存插槽没有满配，服务器是两个海光CPU，64核心128现场，rss auto基本只能跑在1个Core上面，
巨页内存：
[root@localhost ~]# cat /proc/meminfo |grep -i huge
AnonHugePages:      8192 kB
HugePages_Total:      64
HugePages_Free:       52
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB
CPU架构：
[root@localhost ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             128
NUMA node(s):          8
Vendor ID:             HygonGenuine
CPU family:            24
Model:                 2
Model name:            Hygon C86 7380 32-core Processor
Stepping:              2
CPU MHz:               1200.000
CPU max MHz:           2200.0000
CPU min MHz:           1200.0000
BogoMIPS:              2399.88
Virtualization:        AMD-V
NUMA node0 CPU(s):     0-7,64-71
NUMA node1 CPU(s):     8-15,72-79
NUMA node2 CPU(s):     16-23,80-87
NUMA node3 CPU(s):     24-31,88-95
NUMA node4 CPU(s):     32-39,96-103
NUMA node5 CPU(s):     40-47,104-111
NUMA node6 CPU(s):     48-55,112-119
NUMA node7 CPU(s):     56-63,120-127

**Comment by yingweizhao** [comment]
打吞吐使用RSS算法就工作正常，打CPS就不正常

**Comment by yingweizhao** [comment]
使用的是intel XL710 40g网卡

**Comment by pengjianzhang** [comment]
server ip数与cpu数目一致，不要配置rss。
如果喜欢dperf，请加个star，谢谢

**Comment by yingweizhao** [comment]
好的，谢谢，我试试，加star-没问题，deperf确实非常不错
