### ISSUE TITLE
dperf是否支持同时发送ipv4和ipv6的混合流量

### ISSUE THREAD

**Issue by alongpan** [baidu/dperf#400]
测试需要，双栈混合流量背景流量。一台服务器跑dperf的client和server，且需要在client和server同时发送ipv4、ipv6和接收ipv4、ipv6，是否支持？如何配置呢

**Comment by pengjianzhang** [comment]
不支持。
配两个client 两个 server 
如果喜欢dperf，请加个star，谢谢

**Comment by alongpan** [comment]
一个client里面配置两个port，一个port配ipv4，一个port配置ipv6也不行是吧。
配两个client 两个 server，那就只能用两台服务器来运行两套dperf环境分别跑v4和v6是吗？

**Comment by pengjianzhang** [comment]
一个服务器上可以跑一个client, 一个server

**Comment by alongpan** [comment]
好的
