### ISSUE TITLE
可以支持多server IP吗？比如一个C段

### ISSUE THREAD

**Issue by alongpan** [baidu/dperf#401]
服务器CPU数量有限，要跑多个server ip，是不是就要配置同等或多于server ip数量的cpu？
能否做到server ip数量大于cpu数量呢

**Comment by pengjianzhang** [comment]
暂时不行
可以考虑加入这个特性

**Comment by alongpan** [comment]
增加多server ip之后，rss不能用auto，改l3之后，cc为什么上不去了呢？
原来一个server ip的时候，用auto l3l4会跑到指定上限后停止建连
![image](https://github.com/baidu/dperf/assets/143994951/8c3b3857-e3f0-4e2c-9d5f-24da9356859b)

**Comment by pengjianzhang** [comment]
计划支持server支持多IP，如果是单纯作为性能测试，不需要server 多IP，请说明一下：

1. 什么场景需要server ip数量很多?
2. 如果在多IP的情况下，server只允许配置1个CPU是否满足需求？

**Comment by pengjianzhang** [comment]
客户端IP数量太多，这个需求不太适合开源版本
贵企业可以考虑一下商业支持

**Comment by pengjianzhang** [comment]
主干已经支持了server配置多个IP
