### ISSUE TITLE
dperf测试代理性能

### ISSUE THREAD

**Issue by TAO-PAN** [baidu/dperf#402]
请问下 dperf支持下面场景吗？ 
 client和server之间接一台服务器，服务器上有我的tcp代理程序，基于ip端口的，client请求我的程序，我的程序转发请求至server端

**Comment by pengjianzhang** [comment]
支持。dperf更适合测试4层代理，如L4LB，防火墙等，不支持SSL。
如果喜欢dperf，请加个star，谢谢

**Comment by TAO-PAN** [comment]
好的  我找个环境测下试试的

**Comment by TAO-PAN** [comment]
我的测试环境是两台机器光纤直连，没有经过路由或者交换设备，请求配置port时 网关ip和mac填什么？
