### ISSUE TITLE
Dperf Mellanox 网卡无法生成或者接收流量

### ISSUE THREAD

**Issue by HBSDLJZ** [baidu/dperf#434]
大师，您好。我在三层交换机上直连一个物理机，物理机上安装了DPDK 19.11版本、Dperf，并在英伟达网站上安装了Mellanox的驱动OFED，但是无法正常发收流量，之前在物理机上搭建ESXi平台-虚拟机发收流量是可以的。如下是client配置。
`mode        client
cpu         0
duration    60s
cps         10k
port        0000:5e:00.0    10.10.254.193   10.10.254.87 f4:e9:75:68:ae:e8
client      10.10.254.193   1
server      10.10.250.150   1
listen      80              1`

**Comment by HBSDLJZ** [comment]
您好，这个问题是怎么导致的呢？ 
 
 ./build/dperf -c test/http/client-cps.conf 
EAL: Detected CPU lcores: 104
EAL: Detected NUMA nodes: 2
EAL: Detected shared linkage of DPDK
EAL: RTE_RING tailq is already registered
PANIC in tailqinitfn_rte_ring_tailq():
Cannot initialize tailq: RTE_RING
0: ./build/dperf (rte_dump_stack+0x32) [4aa7d2]
1: ./build/dperf (__rte_panic+0xba) [415f58]
2: /usr/local/lib64/librte_ring.so.23 (7f4e466ff000+0xe2c) [7f4e466ffe2c]
3: /lib64/ld-linux-x86-64.so.2 (7f4e4936d000+0xf9c3) [7f4e4937c9c3]
4: /lib64/ld-linux-x86-64.so.2 (7f4e4936d000+0x1459e) [7f4e4938159e]
5: /lib64/ld-linux-x86-64.so.2 (7f4e4936d000+0xf7d4) [7f4e4937c7d4]
6: /lib64/ld-linux-x86-64.so.2 (7f4e4936d000+0x13b8b) [7f4e49380b8b]
7: /lib64/libdl.so.2 (7f4e48e67000+0xfab) [7f4e48e67fab]
8: /lib64/ld-linux-x86-64.so.2 (7f4e4936d000+0xf7d4) [7f4e4937c7d4]
9: /lib64/libdl.so.2 (7f4e48e67000+0x15ad) [7f4e48e685ad]
10: /lib64/libdl.so.2 (dlopen+0x31) [7f4e48e68041]
11: ./build/dperf (eal_plugins_init+0x288) [49bd38]
12: ./build/dperf (rte_eal_init+0x72f) [4ac05f]
13: ./build/dperf (400000+0x3ec87) [43ec87]
14: ./build/dperf (dpdk_init+0x9) [43ed29]
15: ./build/dperf (main+0x49) [416369]
16: /lib64/libc.so.6 (__libc_start_main+0xf5) [7f4e4848e555]
17: ./build/dperf (400000+0x171f6) [4171f6]
已放弃

**Comment by pengjianzhang** [comment]
你用早期的版本试试
请详细描述一下你的环境 测试方法 步骤

**Comment by HBSDLJZ** [comment]
好的，感谢张大佬 ~~~~
