### ISSUE TITLE
dperf支持vde么

### ISSUE THREAD

**Issue by zhuzongzhen** [baidu/dperf#436]
目前国内有许多设备上网口直连交换芯片来扩充网口，那么dpdk中使用vdev将交换芯片的网口虚拟出来，这种模式dperf能够支持么

**Comment by pengjianzhang** [comment]
我没有这个设备，支持不了。欢迎社区小伙伴来支持。

**Comment by pengjianzhang** [comment]
@zhangpengfei-xyz

**Comment by wen-0323** [comment]
有的，比如国产的SOC飞腾E2000上面的直出mac网口，不是pci总线，这种非PCI设备不能使用dpdk-devbind.py脚本绑定，需要用的是飞腾提供的dpdk-pdevbind.sh脚本工具绑定mac网口驱动，https://blog.csdn.net/developerof/article/details/139580871 这个博客里有说明脚本的实际动作就是把原来的网卡驱动解绑，绑定成uio驱动。
dpdk里针对非pci总线网卡设备支持如下方式：
使用 dpdk-testpmd -l 0,3 --vdev=net_macb, device=3200c000.ethernet 这样的方式
-vdev=net_macb, device=3200c000.ethernet，指定虚拟设备的 pmd 模式为 net_macb 即 macb 驱动，逗号后的参数为 device 用于指
定要使用的平台设备。
这种网口设备与pci总线的网卡设备只是使用的总线不同，测试性能的方法场景都与pci网卡设备一样，期望后续dperf能支持

**Comment by pengjianzhang** [comment]
> 有的，比如国产的SOC飞腾E2000上面的直出mac网口，不是pci总线，这种非PCI设备不能使用dpdk-devbind.py脚本绑定，需要用的是飞腾提供的dpdk-pdevbind.sh脚本工具绑定mac网口驱动，https://blog.csdn.net/developerof/article/details/139580871 这个博客里有说明脚本的实际动作就是把原来的网卡驱动解绑，绑定成uio驱动。 dpdk里针对非pci总线网卡设备支持如下方式： 使用 dpdk-testpmd -l 0,3 --vdev=net_macb, device=3200c000.ethernet 这样的方式 -vdev=net_macb, device=3200c000.ethernet，指定虚拟设备的 pmd 模式为 net_macb 即 macb 驱动，逗号后的参数为 device 用于指 定要使用的平台设备。 这种网口设备与pci总线的网卡设备只是使用的总线不同，测试性能的方法场景都与pci网卡设备一样，期望后续dperf能支持

谢谢关注dperf。可惜我没有这个设备，支持不了

1. 欢迎社区小伙伴来提交代码支持
2. 如果有人能提供环境，我可以来支持
