### ISSUE TITLE
怎样设置请求体和返回体？

### ISSUE THREAD

**Issue by alongpan** [baidu/dperf#438]
设置 payload，但是实际没有payload，是URL增加长度，是否可以随机在reqbody和respbody中增加数据包长度吗？

**Comment by pengjianzhang** [comment]
数据长度目前不能变化

**Comment by alongpan** [comment]
被测设备默认做4层统计，同时也支持解析body，取决是否开启。想测试开启body解析的情况下，看对整体性能的消耗。

**Comment by pengjianzhang** [comment]
http get request只有header没有Body，http response是有Body的

**Comment by alongpan** [comment]
换成http post是不是可以同时都有Body？

**Comment by pengjianzhang** [comment]
是的
现在还不支持post，这个特性在规划中

**Comment by alongpan** [comment]
现在可以临时在get response加上Body吗？

**Comment by pengjianzhang** [comment]
不能
因为get加body不符合规范

**Comment by alongpan** [comment]
好的，还有个问题请教。
设置payload_random后，url是随机了，但并不是每一个get都随机吗，有办法让每一次请求都不一样吗？
背景是我们存数据会做压缩，但如果每条流全都一样，压缩比会很高，跟用户场景不太符合，实际用户场景是不一样的。

**Comment by alongpan** [comment]
> 是的 现在还不支持post，这个特性在规划中

post的特性有大概的时间计划吗？

**Comment by pengjianzhang** [comment]
大概在第二季度

**Comment by alongpan** [comment]
好的

**Comment by pengjianzhang** [comment]
试一下这个分支
https://github.com/pengjianzhang/dperf/tree/post

配置方法：
http_method POST
payload_size 1K

**Comment by alongpan** [comment]
可以了，但是现在payload都是一摸一样的，可以每个包不一致吗？或者多久切换一次也可以
![dperf_post](https://github.com/baidu/dperf/assets/143994951/f85bbaa1-961c-4b81-96fb-fdbc2c8b7070)

**Comment by pengjianzhang** [comment]
暂时做不到

**Comment by alongpan** [comment]
方案1可以的，方案2可能会需要配置较多的cpu。url是否也可以通过方案1这种方式，配置不同的url，轮流发？

**Comment by pengjianzhang** [comment]
你可以用其他工具如ab, hey, wrk发一些不一样的流量，作为补充

**Comment by alongpan** [comment]
好的，多谢

**Comment by pengjianzhang** [comment]
请向周围小伙伴推荐、宣传一下dperf 谢谢

**Comment by alongpan** [comment]
好的
