### ISSUE TITLE
[Bug] kni queue racing may cause kernel panic

### ISSUE THREAD

**Issue by fkcrazy001** [baidu/dperf#458]
**Describe the bug**
在当前dpdk版本中，kni的tx/rx队列只有一个，但看起来会被多个dperf worker同时读取或者写入。

**To Reproduce**
dperf运行足够长时间，kernel可能会panic

**Additional context**
此外，kni模块已经被废除，推荐使用内核的vhost-net模块，如果有需要我可以提pr

**Comment by pengjianzhang** [comment]
欢迎提PR
应该只是worker 0读写kni的

**Comment by fkcrazy001** [comment]
pr已放于 https://github.com/baidu/dperf/pull/459

**Comment by pengjianzhang** [comment]
谢谢 正在review

**Comment by fkcrazy001** [comment]
将评审中出现的commit合并，提交到新的pr

https://github.com/baidu/dperf/pull/481
