### ISSUE TITLE
LVS性能测试CPS只达到20w/s

### ISSUE THREAD

**Issue by zsjlqq** [baidu/dperf#46]
拓扑：
dclient: 3.10.0-1160.49.1.el7.x86_64/内存64G/10G网卡*1
dserver: 3.10.0-1160.49.1.el7.x86_64/内存64G/10G网卡*1
lvs: 5.6.2-1.el7.elrepo.x86_64cx/内存64G/10G网卡*2，一内一外

lvs配置：共提供80-89端口
virtual_server 192.168.90.100 80 {
    delay_loop 6
    lb_algo rr
    lb_kind NAT
    persistence_timeout 0
    protocol TCP
    real_server 192.168.80.101 80 {
        weight 1
    }
}
..........................

dclient配置：
mode                        client
tx_burst                    128
launch_num                  10
cpu                         0
payload_size                1
duration                    2m
cps                         200k
port                        0000:82:00.0  192.168.90.10 192.168.90.1 bc:97:e1:e7:3e:a0
client                      192.168.90.11     20
server                      192.168.90.100    1
listen                      80         10

dserver配置：
mode            server
tx_burst        128
cpu             0
duration        10m
payload_size    1
keepalive       1
port            0000:03:00.1    192.168.80.101  192.168.80.1 bc:97:e1:e7:3e:a1
client          192.168.80.1    150
client          192.168.90.1    150
server          192.168.80.101  1
listen          80              10

结果CPS大概能到20w左右，如果再高就会出现很多skErr，tcpDrop
seconds 255                cpuUsage 13
pktRx   800,284            pktTx    600,218            bitsRx   492,970,520        bitsTx  441,750,464        dropTx  0
arpRx   0                  arpTx    0                  icmpRx   0                  icmpTx  0                  otherRx 2          badRx 0
synRx   200,054            synTx    200,054            finRx    200,102            finTx   200,102            rstRx   0          rstTx 0
synRt   0                  finRt    0                  ackRt    0                  pushRt  0                  tcpDrop 0
skOpen  200,054            skClose  200,064            skCon    183,601            skErr   0
httpGet 200,062            http2XX  200,062            httpErr  0
ierrors 0                  oerrors  0                  imissed  350

能帮忙分析一下CPS没有达到50w左右的原因吗，内存不够？网卡带宽不够？LVS设备需要一些调优手段？dclient直接到dserver至少能测试到百万级的cps能力，可能跟我分配的大页内存有限有关，但也能排除了这两个点的嫌疑，压力肯定够了，问题应该出现在LVS这个点上。

**Comment by pengjianzhang** [comment]
LVS 中断绑核了么

**Comment by zsjlqq** [comment]
> LVS 中断绑核了么 测试CPS 不需要设置keepalive 1 另外 能给项目加个star吗，谢谢

已star，你的中断绑了12个核是吧？我待会试试

**Comment by pengjianzhang** [comment]
VIP0=6.6.234.3
VIP1=6.6.234.4
VIP2=6.6.234.5
VIP3=6.6.234.6
VIP4=6.6.234.7

RS0=6.6.234.210
RS1=6.6.234.211
RS2=6.6.234.212
RS3=6.6.234.213
RS4=6.6.234.214

function add_vs0()
{
    PORT=$1

    VS=$VIP0:$PORT
    ipvsadm -D -t $VS
#    ipvsadm -L -n
    sleep 1

    ipvsadm -A -t $VS -s rr
    ipvsadm -a -t $VS -r $RS0:$PORT -m
    ipvsadm -L -n
}

function add_vs1()
{
    PORT=$1

    VS=$VIP1:$PORT
    ipvsadm -D -t $VS
#    ipvsadm -L -n
    sleep 1

    ipvsadm -A -t $VS -s rr
    ipvsadm -a -t $VS -r $RS1:$PORT -m
    ipvsadm -L -n
}

function add_vs0_port()
{
    add_vs0  80
    add_vs0  81
    add_vs0  82
    add_vs0  83
    add_vs0  84

}

function add_vs1_port()
{
    add_vs1  80
    add_vs1  81
    add_vs1  82
    add_vs1  83
    add_vs1  84

}

iptables -F
ipvsadm --set 200 3 10

#add_vs $VIP0 80

add_vs0_port
add_vs1_port

exit 0

**Comment by pengjianzhang** [comment]
VIP0=6.6.234.3
VIP1=6.6.234.4
VIP2=6.6.234.5
VIP3=6.6.234.6
VIP4=6.6.234.7

RS0=6.6.234.210
RS1=6.6.234.211
RS2=6.6.234.212
RS3=6.6.234.213
RS4=6.6.234.214

function add_vs0()
{
    PORT=$1

    VS=$VIP0:$PORT
    ipvsadm -D -t $VS
    sleep 1

    ipvsadm -A -t $VS -s rr
    ipvsadm -a -t $VS -r $RS0:$PORT -m
    ipvsadm -L -n
}

function add_vs1()
{
    PORT=$1

    VS=$VIP1:$PORT
    ipvsadm -D -t $VS
    sleep 1

    ipvsadm -A -t $VS -s rr
    ipvsadm -a -t $VS -r $RS1:$PORT -m
    ipvsadm -L -n
}

function add_vs0_port()
{
    add_vs0  80
    add_vs0  81
    add_vs0  82
    add_vs0  83
    add_vs0  84

}

function add_vs1_port()
{
    add_vs1  80
    add_vs1  81
    add_vs1  82
    add_vs1  83
    add_vs1  84

}

iptables -F
ipvsadm --set 200 3 10

add_vs0_port
add_vs1_port

exit 0

**Comment by pengjianzhang** [comment]
这是我用过的一个脚本，参考一下。
大概是一个VS  配一个独立的 VIP，对应一个RS。把流量分开一些。
dperf 也是用了多线程。

**Comment by pengjianzhang** [comment]
> 

你可以观察一下LVS的CPU使用率，调中断绑核，不要让中断太高。
这是一个双NUMA服务器，我只用了一个NUMA，12个核都用上了。
