### ISSUE TITLE
[Bug] In the ARM environment, compiling dperf with a DPDK version of RTE_VERSION_NUM(20, 0, 0, 0) or higher results in an error.

### ISSUE THREAD

**Issue by chcchc88** [baidu/dperf#464]
**Describe the bug**
dpdk version：20-11-lts
dperf version：v1.7.0
compiler：       aarch64-linux-gnu-gcc
Compiling dperf error in this environment.

**To Reproduce**
1. Compile the library for dpdk20-11-lts.
2. Specify the libdpdk.pc path in the Makefile file of dperf.
3. Execute make in the dperf directory.
4. Compilation error occurred.

**Expected behavior**
Modify the code of the src/dpdk.c file to resolve compilation errors.

**Screenshots**
<img width="1341" alt="企业微信截图_17204066158736" src="https://github.com/baidu/dperf/assets/51945267/67642008-b041-41f7-95a5-614fd423aea0">

**Comment by pengjianzhang** [comment]
I fixed it in this branch, could you please test it? Thanks.
https://github.com/pengjianzhang/dperf

**Comment by chcchc88** [comment]
The modification compiles correctly, but the reason for this failure is that the header file rte_vect.h is not included. Would it be more appropriate to include this header file, even though currently arm does not support 512-bit wide SIMDs?

**Comment by pengjianzhang** [comment]
could you submit a pull-request to fix it?

**Comment by chcchc88** [comment]
ok
