### ISSUE TITLE
[Feature] Added the function of displaying the rate during streaming.

### ISSUE THREAD

**Issue by chcchc88** [baidu/dperf#466]
**Is your feature request related to a problem? Please describe.**
1. For example, if the configured new creation rate is 2 M, you cannot know whether it is actually 2 M when you send a stream.
2. Unable to obtain the history of the traffic rate.

**Describe the solution you'd like**
Displays various rates in real time while streaming.

**Comment by pengjianzhang** [comment]
1. dperf tries to achieve the configured goals, and you should adjust the appropriate goals
2. dperf prints statistics to the screen every second, which can be used as a history

**Comment by chcchc88** [comment]
<img width="170" alt="企业微信截图_17205038217084" src="https://github.com/baidu/dperf/assets/51945267/8ee6b1b3-20ff-49c3-9e07-222a658353de">
It would be nice if there was a speed display like this.

**Comment by pengjianzhang** [comment]
dperf already has these statistics

**Comment by pengjianzhang** [comment]
我可能没有理解你的意思，请用中文说一下
