### ISSUE TITLE
是否支持100G网卡？

### ISSUE THREAD

**Issue by legend050709** [baidu/dperf#47]
1》使用的是什么dpdk版本？
2》是否支持100G网卡？支持的哪些厂家的什么类型的网卡？（Mellanox，博通？？）

**Comment by pengjianzhang** [comment]
1. DPDK-17.11, 18.11, 19.11, 20.11都测过，21.11尚未测过。新手建议用19.11，老手就不用建议了。
2. 理论上DPDK支持的网卡都支持。
      测试过CX 6 100g， CX 4 25g，vmxnet3 10g，华为hns3，intel 82599。 

我手上网卡有限，希望社区帮忙多测一下。谢谢！

**Comment by legend050709** [comment]
> 1. DPDK-17.11, 18.11, 19.11, 20.11都测过，21.11尚未测过。新手建议用19.11，老手就不用建议了。
>    在此呼吁社区兄弟多在DPDK新版本上测一下，我主要用19.11。
> 2. 理论上DPDK支持的网卡都支持。
>    测试过CX 6 100g， CX 4 25g，vmxnet3 10g，华为hns3，intel 82599。
> 
> 我手上网卡有限，希望社区帮忙多测一下。谢谢！ 有兄弟说X710上FDIR有问题，我手上没这块卡，issue一直挂着，好头疼。

x710是用的i40e的驱动吧，DPDK中i40e_fdir.c中没有对掩码进行设置，并且没有实现该接口。

**Comment by legend050709** [comment]
> 

其他家的100G是否有测试，比如博通的？

**Comment by pengjianzhang** [comment]
没测过，你有这块卡么

**Comment by pengjianzhang** [comment]
> > 1. DPDK-17.11, 18.11, 19.11, 20.11都测过，21.11尚未测过。新手建议用19.11，老手就不用建议了。
> >    在此呼吁社区兄弟多在DPDK新版本上测一下，我主要用19.11。
> > 2. 理论上DPDK支持的网卡都支持。
> >    测试过CX 6 100g， CX 4 25g，vmxnet3 10g，华为hns3，intel 82599。
> > 
> > 我手上网卡有限，希望社区帮忙多测一下。谢谢！ 有兄弟说X710上FDIR有问题，我手上没这块卡，issue一直挂着，好头疼。
> 
> x710是用的i40e的驱动吧，DPDK中i40e_fdir.c中没有对掩码进行设置，并且没有实现该接口。

最新版本也是这样吗？

**Comment by legend050709** [comment]
> > > 1. DPDK-17.11, 18.11, 19.11, 20.11都测过，21.11尚未测过。新手建议用19.11，老手就不用建议了。
> > >    在此呼吁社区兄弟多在DPDK新版本上测一下，我主要用19.11。
> > > 2. 理论上DPDK支持的网卡都支持。
> > >    测试过CX 6 100g， CX 4 25g，vmxnet3 10g，华为hns3，intel 82599。
> > > 
> > > 我手上网卡有限，希望社区帮忙多测一下。谢谢！ 有兄弟说X710上FDIR有问题，我手上没这块卡，issue一直挂着，好头疼。
> > 
> > 
> > x710是用的i40e的驱动吧，DPDK中i40e_fdir.c中没有对掩码进行设置，并且没有实现该接口。
> 
> 最新版本也是这样吗？

新版本DPDK我没有看了，还没有测试过。之前的老版本17.11应该是有问题的，fdir mask的设置问题。

**Comment by pengjianzhang** [comment]
谢谢
