### ISSUE TITLE
[help] ./build/dperf -c test/http/server-cps.conf 启动报错

### ISSUE THREAD

**Issue by Sachi14** [baidu/dperf#49]
[root@localhost dperf-main]# ./build/dperf -c test/http/server-cps.conf
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
port init fail
dpdk init fail

**Comment by pengjianzhang** [comment]
非常感谢使用dperf
请问您用的是什么网卡，是否配置了大页，PCI号是否正确
请参考一下这个文章
https://zhuanlan.zhihu.com/p/451340043
谢谢

**Comment by pengjianzhang** [comment]
请贴一下配置

**Comment by Sachi14** [comment]
[root@localhost dpdk-stable-19.11.11]# ./usertools/dpdk-devbind.py -s

Network devices using DPDK-compatible driver
============================================
0000:02:02.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio unused=e1000

Network devices using kernel driver
===================================
0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens33 drv=e1000 unused=igb_uio *Active*

**Comment by Sachi14** [comment]
# cat /proc/meminfo | grep Huge
AnonHugePages:         0 kB
HugePages_Total:       5
HugePages_Free:        4
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB

**Comment by Sachi14** [comment]
![image](https://user-images.githubusercontent.com/38452105/159218669-aefb9bcc-7268-4601-abef-475a9e9ce134.png)

**Comment by pengjianzhang** [comment]
lspci | grep Eth 看一下

**Comment by Sachi14** [comment]
lspci | grep Eth
02:01.0 Ethernet controller: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)
02:02.0 Ethernet controller: Intel Corporation 82545EM Gigabit Ethernet Controller (Copper) (rev 01)

**Comment by pengjianzhang** [comment]
DPDK 版本
配置

**Comment by Sachi14** [comment]
dpdk-stable-19.11.11
config/common_base默认的

**Comment by pengjianzhang** [comment]
你这是虚拟机环境吗

**Comment by Sachi14** [comment]
嗯嗯，是的

**Comment by pengjianzhang** [comment]
试一下 绑定 uio_pci_generic

**Comment by pengjianzhang** [comment]
贴一下配置文件
dpdk版本是 19.11么？

**Comment by Sachi14** [comment]
[common_base.txt](https://github.com/baidu/dperf/files/8313700/common_base.txt)
嗯dpdk19.11.11版本的

**Comment by pengjianzhang** [comment]
给我留个联系方式 电话沟通一下 pengjianzhang@baidu.com

**Comment by Sachi14** [comment]
modprobe uio_pci_generic
insmod igb_uio.ko 

./usertools/dpdk-devbind.py -b uio_pci_generic 0000:02:02.0
Error: bind failed for 0000:02:02.0 - Cannot bind to driver uio_pci_generic
绑定好像不对

**Comment by pengjianzhang** [comment]
试下DPDK 20.11
或者
升级一下内核

**Comment by pengjianzhang** [comment]
或者 试试其他网卡

**Comment by Sachi14** [comment]
好的，我去试试看

**Comment by pengjianzhang** [comment]
一般万兆网卡用得多；千兆网卡性能较弱，不太适合做性能测试。能给项目加个star吗，谢谢

**Comment by Sachi14** [comment]
好的，加了

**Comment by pengjianzhang** [comment]
从文档上看，DPDK是支持这个网卡的，你能给dperf修一下这个bug吗，我这里没这个环境，谢谢。

**Comment by pengjianzhang** [comment]
qemu-kvm emulated Intel® 82540EM Gigabit Ethernet Controller (qemu e1000 device)
    VMware emulated Intel® 82545EM Gigabit Ethernet Controller
    VMware emulated Intel® 82574L Gigabit Ethernet Controller.

**Comment by pengjianzhang** [comment]
https://doc.dpdk.org/guides/nics/e1000em.html
看来82545EM 只支持vmware虚拟机

**Comment by pengjianzhang** [comment]
你的虚拟机换是啥？ 如果是vmware尽量用vmxnet3网卡

**Comment by Sachi14** [comment]
[root@localhost dperf-main]# ./build/dperf -c test/http/server-cps.conf 
bad client ip range
line 5: error
换了台电脑升级了一下，知道这是啥报错了

**Comment by pengjianzhang** [comment]
贴一下配置

**Comment by Sachi14** [comment]
mode        server
cpu         0
duration    10m
port        0000:06:00.0    6.6.241.27   6.6.241.1
client      6.6.241.1       254
client      6.6.242.1       254
server      6.6.241.27      1
listen      80              1

**Comment by pengjianzhang** [comment]
这是一个buf，在主分支已经修复了，
client 6.6.241.1 250

**Comment by Sachi14** [comment]
好的，十分感谢

**Comment by pengjianzhang** [comment]
v1.0.0 不允许x.x.x.255作为合法的client IP，主分支取消了这个限制

**Comment by pengjianzhang** [comment]
方便 分享一下您的使用场景吗

**Comment by Sachi14** [comment]
研发了一个四层交换系统dpdk+lvs，想测试一下性能

**Comment by pengjianzhang** [comment]
这几篇文章参考一下：
https://zhuanlan.zhihu.com/p/451341132
https://zhuanlan.zhihu.com/p/484613986
https://zhuanlan.zhihu.com/p/453772877

**Comment by pengjianzhang** [comment]
请帮忙宣传一下，谢谢！
https://mp.weixin.qq.com/s/46l09oszc8Z19cZuk9ry9g

**Comment by Sachi14** [comment]
好的
