### ISSUE TITLE
tcp syn包携带payload

### ISSUE THREAD

**Issue by shenlongxing** [baidu/dperf#503]
我想测试在tcp syn包中携带指定 payload，请问可以实现吗

**Comment by pengjianzhang** [comment]
什么背景呢
toa option吗
数据报文不符合协议标准

**Comment by shenlongxing** [comment]
不是toa option，是想在 tcp payload中新增一些自定义数据。确实不是标准的 tcp 协议，这种是不支持的吗？

**Comment by pengjianzhang** [comment]
syn报文加不了payload

你可以自己去修改dperf
如果喜欢dperf 请加个star 谢谢
