### ISSUE TITLE
同子网下client压测server大量丢包

### ISSUE THREAD

**Issue by zhuquechiye** [baidu/dperf#504]
云主机搭建的环境，client和server在同一个子网，cps=10也会丢包，大佬们帮忙看看配置有问题吗？
大页2M
dpdk版本：23.07
dperf版本：1.6

client配置
![image](https://github.com/user-attachments/assets/ca720aa2-3114-46aa-a954-4979a4c6c8d1)

日志
![image](https://github.com/user-attachments/assets/c1e44453-f570-40d5-89b1-61b09d9c2101)

server配置
![image](https://github.com/user-attachments/assets/1e8831ac-539e-4829-81d2-52e352c3c94d)

日志
![image](https://github.com/user-attachments/assets/7c12613c-022d-49da-8746-c5ce10612824)

dpdk绑的虚拟网卡
![image](https://github.com/user-attachments/assets/2604bf05-d3ef-4f79-847f-82cd492366c4)

**Comment by pengjianzhang** [comment]
用最新代码吧

server.conf 里 client配错了

**Comment by zhuquechiye** [comment]
> 用最新代码吧
> 
> server.conf 里 client配错了

<img width="298" alt="image" src="https://github.com/user-attachments/assets/3d79d5ad-55f4-4d85-9d39-996afcbed412">
这一行吗？是另一个子网的云主机的配置，不删会有影响吗？
我两台client压测一台server，cc=1000w，没啥问题。但是cps就是会丢包

client
![image](https://github.com/user-attachments/assets/7500c4f9-59fd-4c69-b04c-e307dfb5e109)
![image](https://github.com/user-attachments/assets/440fa3dd-f6ad-4c00-ab47-519b9f9955eb)

server
![image](https://github.com/user-attachments/assets/a6fb05a5-a1c7-4a97-87e8-78a06403352e)

**Comment by zhuquechiye** [comment]
> 没问题 用最新代码看看，1.6有Bug

好的，多谢大佬

**Comment by zhuquechiye** [comment]
> 你用的哪家的云主机

首都在线

**Comment by pengjianzhang** [comment]
有的厂家的虚拟机RSS有问题，可以试试用1个CPU，规避这个问题

**Comment by zhuquechiye** [comment]
> 有的厂家的虚拟网卡RSS有问题，可以试试用1个CPU，规避这个问题

是版本的问题，换成1.8-dev正常了。有个新问题，测试新建连接时，payload_size=1，所有请求都会是httpErr。文档上这个值会自动适配，1.6版本设置1没httpErr。这个是升级的变更吗
<img width="944" alt="image" src="https://github.com/user-attachments/assets/351ad8c0-f138-44e1-951a-e74df4f34866">

**Comment by pengjianzhang** [comment]
版本变化，手册看这里
https://dperf.org/doc/html/configuration#section19
