### ISSUE TITLE
dperf启动失败，not enough ports available

### ISSUE THREAD

**Issue by jk316** [baidu/dperf#505]
我使用的系统版本是ubuntu22.04，使用的网卡是Mellonax Connect 5 EX系列网卡，报错no enough port available。

### 检查过程：

1. PCI地址，均为0000:65:00.0，是正确的
2. 网卡是否支持。Mellonax Connect 5 EX是支持的，在之前的机器上可以使用。
3. 驱动版本
   Mellonax网卡安装的驱动尝试了4个版本，均报no enough port available：

- MLNX_OFED_LINUX-24.10-1.1.4.0-ubuntu22.04-x86_64.iso （LTS）
- MLNX_OFED_LINUX-24.10-0.7.0.0-ubuntu22.04-x86_64.iso
- MLNX_OFED_LINUX-23.10-3.2.2.0-ubuntu22.04-x86_64.iso （LTS）
- MLNX_OFED_LINUX-5.8-5.1.1.2-ubuntu22.04-x86_64.iso     （LTS）

请问您知道是什么原因导致的no enough port available吗？

**Comment by pengjianzhang** [comment]
testpmd 能正常使用吗?

**Comment by jk316** [comment]
1.testpmd可以使用
![图片](https://github.com/user-attachments/assets/8aaf8ddf-046b-41bb-a86a-a17a7c9e4e90)
2. 我的dpdk 编译过程为：
```
从https://www.dpdk.org/下载源码
tar xvf dpdk-24.03.tar.xz
cd dpdk-24.03
meson setup build
cd build
ninja
meson install
ldconfig

**Comment by pengjianzhang** [comment]
你用testpmd打打流量看看

**Comment by jk316** [comment]
我运行的命令是
```
./dpdk-testpmd -l 0-3 -n 4 -- -a --portmask=0x1 --nb-cores=2 --stats-period 1
```
但是，没有产生流量

**Comment by jk316** [comment]
![微信图片_20241209171034](https://github.com/user-attachments/assets/d8369adf-2305-4aa8-b184-1819d51de5d1)

**Comment by pengjianzhang** [comment]
看一下DPDK的安装目录里 能找到mlx驱动吗

**Comment by jk316** [comment]
1. 我的驱动安装过程如下，没有在dpdk文件夹找到驱动的iso文件
```
在https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/ 网站下载ubuntu22.04的驱动：MLNX_OFED_LINUX-23.10-1.1.9.0-ubuntu22.04-x86_64.iso
mount -o ro,loop MLNX_OFED_LINUX-23.10-1.1.9.0-ubuntu22.04-x86_64.iso /mnt
/mnt/mlnxofedinstall
restart
使用`modinfo mlx5_core` 验证是否安装成功
```

2. 在dpdk安装目录有如下的文件夹`/root/dpdk-24.03/drivers/net/mlx5`，里面有许多C语言文件。
3. 我将mlx5_core.ko 所在的路径：`/lib/modules/5.11.0-27-generic/updates/dkms/mlx5_core.ko` 添加到了PATH中，但是仍然报错not enough ports available

**Comment by pengjianzhang** [comment]
你要看DPDK的安装目录里 有没有Libmlx5.so

**Comment by jk316** [comment]
我的libmlx5.so是在`/usr/lib/x86_64-linux-gnu/libmlx5.so` 中，DPDK的安装目录是在`/usr/local`  下

**Comment by pengjianzhang** [comment]
参考 https://dperf.org/doc/html/compile-dperf-on-dpdk-23 
把DPDK安装到指定目录 如/root/dpdk/dpdk-23.07/mydpdk

**Comment by jk316** [comment]
太感谢了，把dpdk安装到指定目录就可以打流了，感谢您的解答，祝dperf越来越好，会向身边人推荐的！

**Comment by pengjianzhang** [comment]
喜欢dperf就加个star吧，谢谢~

**Comment by jk316** [comment]
哈哈哈哈加了，感谢您的帮助~
