### ISSUE TITLE
dperf启动失败，求帮助

### ISSUE THREAD

**Issue by sheva7777** [baidu/dperf#51]
hello，我想用dperf来测试一下dpvs的cps性能，安装完成后启动server失败
./build/dperf -c test/http/server-cps.conf
EAL: Detected 64 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: Probing VFIO support...
EAL: VFIO support initialized
port init fail
dpdk init fail

大页内存已配置：
cat /proc/meminfo | grep Huge
AnonHugePages:     77824 kB
ShmemHugePages:        0 kB
FileHugePages:         0 kB
HugePages_Total:      49
HugePages_Free:       48
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB

网卡：
mlx cx4

dpdk版本：
19.11.10

内核版本：
5.4

**Comment by pengjianzhang** [comment]
驱动正确安装了么

**Comment by pengjianzhang** [comment]
MLX CX4是支持的

**Comment by sheva7777** [comment]
我看有安装ofed：
ofed_info -s
OFED-internal-5.0-1.0.0.0:

**Comment by pengjianzhang** [comment]
mlx需要加载 modprobe mlx5_ib

参考下
https://zhuanlan.zhihu.com/p/451340043
https://zhuanlan.zhihu.com/p/484252751

**Comment by pengjianzhang** [comment]
编译时打开MLX开关了么

**Comment by pengjianzhang** [comment]
修改config/common_base，打开编译开关

 CONFIG_RTE_LIBRTE_MLX5_PMD=y

**Comment by sheva7777** [comment]
没开，我试下，谢谢

**Comment by pengjianzhang** [comment]
开启了 daemon模式么

**Comment by pengjianzhang** [comment]
看起来ARP正常工作了

**Comment by pengjianzhang** [comment]
你是不是只有一个网卡？ 或者 地址冲突了，抢占了管理口？
dperf运行时，这个网口不能再ssh

**Comment by sheva7777** [comment]
是的 只有一个管理网卡

**Comment by pengjianzhang** [comment]
两个方法：
1. 给网卡配VF，dperf运行在vf上 （推荐）
2. 使用KNI特性，dperf生成虚拟网卡，用于管理，需要使用main分支。这个主要是用来做动态路由的，也可以用来做管理。

**Comment by sheva7777** [comment]
谢谢，我用kni暂时解决了这个问题

**Comment by sheva7777** [comment]
hello，我用dperf做客户端 ，nginx做服务端的时候发现，如果挥手的时候nginx率先发送fin包，dperf回的fin+ack包好像有问题（确认序列号没有加一），导致nginx没有正常关闭连接，重传了第一个fin包，dperf的统计tcpdrop大量增加。我不太懂，不确定是不是这个问题？

**Comment by pengjianzhang** [comment]
谢谢。
应该是一个Bug。
我也发现dperf与curl配合FIN重传了，可能是同一个问题。
请用dperf客户端 配合dperf 服务器测试。 
dperf要求服务器的HTTP响应在一个报文内，如果HTTP响应较大，nginx会把响应放在多个报文中，不满足dperf的要求。

**Comment by sheva7777** [comment]
ok，服务端我需要监听多个端口，我dperf配置
listen      80              5
后，dperf就无法正常启动了

**Comment by pengjianzhang** [comment]
是不是大页配少了，内存不够了

**Comment by sheva7777** [comment]
应该不是，配置两个监听的时候还有40多G的大页内存，配三个监听进程就中断了，用的kni

**Comment by pengjianzhang** [comment]
请把配置贴一下

**Comment by pengjianzhang** [comment]
出错性能也贴下

**Comment by sheva7777** [comment]
mode        server
cpu         0
duration    10m
port        0000:5e:00.0    xxx.xxx.xxx.92   xxx.xxx.xxx.65
client      xxx.xxx.xxx.1       254
server      xxx.xxx.xxx.92      1
kni
listen      80              3

现象和我之前没配kni的现象一样，ssh断开连接了
./build/dperf -c test/http/server-cps.conf
EAL: Detected 64 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'PA'
EAL: Probing VFIO support...
EAL: VFIO support initialized
EAL: PCI device 0000:5e:00.0 on NUMA socket 0
EAL:   probe driver: 15b3:1015 net_mlx5
socket allocation succeeded, size 2.98GB num 49937670
Connection to xxx.xxx.xxx.92 closed by remote host.

**Comment by pengjianzhang** [comment]
你需要给kni接口配置ip，路由
=====配置文件====
daemon
kni             vnic
mode            server
cpu             0 1 2 3
#tx_burst        128
#launch_num      10
#payload_size    1
keepalive
duration       	10d
#jumbo
packet_size     1000
#cps             2m
#port           pci             addr      gateway

#port   		    bond4:2(0000:81:00.0,0000:81:00.1)   10.235.20.11 10.235.20.1 00:00:64:01:01:01
port   		    bond4:2(0000:81:00.0,0000:81:00.1)   10.235.20.11 10.235.20.1
#port   		    bond4:2(0000:81:00.0)   10.235.20.11 10.235.20.1 00:00:64:01:01:01


#               addr_start      num
#client          6.6.215.3	    100

client		10.130.29.1	        60
client		10.235.24.11	    1
client      10.235.22.140       10

#               addr_start      num
server          10.235.20.12    4
#               port_start      num
listen          80              1

====启动脚本====

modprobe uio
insmod  /root/dpdk/dpdk-stable-19.11.10/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
insmod /root/dpdk/dpdk-stable-19.11.10/x86_64-native-linuxapp-gcc/kmod/rte_kni.ko  carrier=on

DEVBIND=/root/dpdk/dpdk-stable-19.11.10/usertools/dpdk-devbind.py

MOD=igb_uio
ifconfig xgbe0 down
ifconfig xgbe1 down

PF0=0000:81:00.0
PF1=0000:81:00.1
$DEVBIND  -b $MOD  $PF0
$DEVBIND  -b $MOD  $PF1

DPERF=/root/dperf/build/dperf
$DPERF  -c /root/t.conf

sleep 10

ip addr > 1.txt
function add_ip()
{
    KNI=$1
    ip addr add  10.235.20.11/26 dev $KNI
    route add default gw 10.235.20.1
}

add_ip vnic0

**Comment by pengjianzhang** [comment]
你用的是mlx网卡，用vf吧
echo 1 > /sys/class/net/xgbe0/device/sriov_numvfs

**Comment by sheva7777** [comment]
我配置daemon参数，会报这个问题/var/log/dperf not exist？

**Comment by pengjianzhang** [comment]
请创建这个目录

**Comment by sheva7777** [comment]
谢谢，看起来可以运行，我晚上测试下dpvs性能看看

**Comment by sheva7777** [comment]
请教下client的cps配置成1m，启动报错：
./build/dperf -c test/http/client-cps.conf
Error: insufficient sockets. worker=0 sockets=1310700 cps's cc=2000000

**Comment by pengjianzhang** [comment]
地址配少了，达不到这个目标，要多配一些client ip，我一般client 配100个

**Comment by sheva7777** [comment]
没有条件配置client ip数量，我配置了20个监听端口，算起来已经可以超过1m了啊

**Comment by pengjianzhang** [comment]
要考虑到超时重传，大概要超好几倍，端口再多配些

**Comment by pengjianzhang** [comment]
加油
