### ISSUE TITLE
server端不回复报文

### ISSUE THREAD

**Issue by yanrongkun** [baidu/dperf#515]
dperf版本：v1.8.0
dpdk版本：19.11.14

client端配置：
> mode            client
> cpu               1
> duration        60s
> cc                  10k
> socket_mem  6144
> keepalive       50ms                50
> port               0000:13:00.0    192.168.168.99   192.168.168.168
> client             192.168.168.99  1
> server            10.103.219.98   1
> listen              80                     1

server端配置：
> mode            server
> cpu               2
> duration        30m
> socket_mem  6144
> port               0000:1b:00.0     10.103.219.98   10.103.218.1
> client             10.103.219.91    1
> server            10.103.219.98    1
> listen              80                      1

client端连接路由器lan口192.168.168.168，做nat后由路由器wan口10.103.219.91发送到server端。

client端统计结果：
![图片](https://github.com/user-attachments/assets/a7d18d57-1574-4aba-9f3d-81ad8f9697e2)

server端统计结果:
![图片](https://github.com/user-attachments/assets/c9e5a460-9ac7-48d5-b47b-adbee32e5274)

在路由器上抓包看到server端回复的报文数目非常少
![图片](https://github.com/user-attachments/assets/3ff24ec8-06f1-4ed6-ad8c-1b42d331b472)

请问一下这可能是什么原因造成的？

**Comment by pengjianzhang** [comment]
dperf主要用在内网做压力测试；看看NAT设备是否正常工作

1. 把压力减少 
    cc 1
    keepalive 1s
2.  服务器用nginx看看

3. 用UDP协议试试

如果喜欢dperf，请加个star吧

**Comment by yanrongkun** [comment]
感谢回复，已加star
